Fix relative link to CONTRIBUTING.md
restic/restic pull request #1003
Opened 2017-06-07 20:47 UTC by fwilhe

The link does not work at the moment, not on github and not in the generated docs. This commit makes it work on github, but still the file is not part of the generated docs. Maybe we should just put an absolute link on the file in the repo on `master` branch there?

2017-06-08 17:02 UTC, fd0 commented
Yeah, good point. Could you please just insert an absolute link? Thanks!

2017-06-08 18:46 UTC, fd0 requested changes
Yeah, good point. Could you please just insert an absolute link? Thanks!

2017-06-08 22:38 UTC, fwilhe commented
> Yeah, good point. Could you please just insert an absolute link? Thanks!

@fd0 Updated.

2017-06-09 18:56 UTC, fd0 commented
Thanks!

2017-06-09 18:56 UTC, merged