Improve restore
restic/restic pull request #1044
Opened 2017-06-16 14:57 UTC by lloeki

This improves restore performance by several orders of magniture by not going through the whole tree recursively when we can anticipate that no match will ever occur.

Here is a sample run restoring one file from a `/` backup of a Debian machine on S3:

```
time (DEBUG_LOG=/tmp/restic-debug.log ./restic restore --include /etc/resolv.conf 1141ffca --target restore)
debug log file /tmp/restic-debug.log
debug enabled
restoring <Snapshot 1141ffca of [/] at 2017-06-15 09:25:24.915676881 +0200 CEST by root@test> to restore
ignoring error for restore/etc/resolv.conf: Lchown: lchown restore/etc/resolv.conf: operation not permitted
There were 1 errors

real	0m5.075s
user	0m0.927s
sys	0m0.183s
```

- time to reach the target file is significantly improved since it doesn't go down every directory before as well as inside `/etc`
- time after having restored the file is very short since it doesn't go down every other directory

(The error about `lchown` is spurious since I'm not running this as root)

I have not included time from the current version since it just takes literally forever.

Timestamps and rights not being restored correctly will be the next unit of work once this is dealt with.

Fixes #982

2017-06-16 14:58 UTC, lloeki commented
Please ignore `SAVEPOINT` commit, this is just WIP archival.

2017-06-16 14:59 UTC, lloeki commented on src/restic/filter/filter.go
> +	strs := strings.Split(str, "/")
There is duplication with `Match` here. This will be dealt with.

2017-06-16 15:03 UTC, lloeki commented on src/restic/filter/filter_test.go
> +	{"/foo", "/foo/bar", true}, // maybe this should be false
There may be some semantic choice to be made here: `/foo` and `/foo/*` are equivalent to `/foo/**` currently. Maybe a single `*` could mean "restore just files at that level and `foo` or `/foo` mean "restore `foo` but if it's a dir, don't go down". I kept the existing behavior as is.

2017-06-16 15:05 UTC, lloeki commented
I have an integration test failing locally, but I can't make sense of it yet (I haven't looked into it, but I will).

2017-06-16 15:07 UTC, lloeki commented
Good, Appveyor [reproduced the same failure](https://ci.appveyor.com/project/fd0/restic/build/1769-master#L103)

2017-06-16 15:36 UTC, lloeki commented on src/cmds/restic/cmd_restore.go
> +		return !matched, !childMayMatch
Reverting that `!` on `childMayMatch` fixes the integration test.

2017-06-16 18:52 UTC, fd0 commented on src/cmds/restic/cmd_restore.go
> +		return !matched, !childMayMatch
Do you know that you can just force-push reworked commits, and they will replace the commits here?

2017-06-16 19:04 UTC, fd0 requested changes
First few comments are in, having an in depth look now.

2017-06-16 19:04 UTC, fd0 commented on .gopath
> +/Users/lloeki/Workspace/go
Remove this file from the PR

2017-06-16 19:04 UTC, fd0 commented on src/cmds/restic/cmd_restore.go
> +	// This could return a `childMayMatch` bool and do some additional testing using filter.Match or something alike
Is this a work-in-progress comment?

2017-06-16 19:04 UTC, fd0 commented on src/restic/filter/filter_test.go
> +	{"/foo", "/foo/bar", true}, // maybe this should be false
You're right, I like your suggestion. Make it so :) We'll need to document this, though.

2017-06-16 19:48 UTC, lloeki commented on src/cmds/restic/cmd_restore.go
> +		return !matched, !childMayMatch
Yes I do, serial abuser of `rebase -i` over here :)

2017-06-16 19:55 UTC, lloeki commented on src/cmds/restic/cmd_restore.go
> +		return !matched, !childMayMatch
Had to leave pronto just as I found the fix but wanted to let you know (AFK for now)

2017-06-16 19:56 UTC, lloeki commented on .gopath
> +/Users/lloeki/Workspace/go
Yep, SAVEPOINT commit

2017-06-16 19:57 UTC, lloeki commented on src/cmds/restic/cmd_restore.go
> +	// This could return a `childMayMatch` bool and do some additional testing using filter.Match or something alike
Yep, SAVEPOINT commit

2017-06-16 19:59 UTC, fd0 commented
I haven't found any other issues, good work already!

2017-06-16 20:39 UTC, fd0 commented on src/cmds/restic/cmd_restore.go
> +		return !matched, !childMayMatch
Heh, nice.  :)

2017-07-06 16:07 UTC, lloeki commented
Regarding this:

```
	{"/foo", "/foo/bar", true}, // maybe this should be false
	{"/*", "/foo", true},       // maybe this should be false
	{"/*", "/foo/bar", true},   // maybe this should be false
	{"/foo", "/foo/bar", true}, // maybe this should be false
```

> You're right, I like your suggestion. Make it so :) We'll need to document this, though.

I'd rather handle it in a separate issue/PR as this seems a bit more involved and I don't want to hold this PR back.

2017-07-06 16:12 UTC, lloeki commented
> Timestamps and rights not being restored correctly will be the next unit of work once this is dealt with.

@fd0 Would you like me to split this fix in a separate PR? I have not worked on it yet although I have some ideas for a fix.

2017-07-07 08:32 UTC, lloeki commented
Hmm, I had a hunch and tested this some more, and the behaviour for exclude filters is incorrect. `./restic restore --exclude /etc/resolv.conf 37b9c56d` skips the whole of `/etc`

2017-07-07 08:35 UTC, lloeki commented
Just to be sure I tested multiple include filters and it behaves as expected: `./restic restore --include /bin/bash --include /etc/resolv.conf 37b9c56d --target restored`.

2017-07-07 10:01 UTC, lloeki commented
The exclusion case is now fixed and its performance improved as well. I made some variable names more explicit (notably semantic of matched vs selected) to make it easier to reason about the code.

2017-07-08 08:14 UTC, fd0 commented
Cool, let me know once you're satisfied with the PR and I'll have a look :)

2017-07-17 06:59 UTC, lloeki commented
Sorry this fell off the radar, go for it!

2017-07-23 10:05 UTC, fd0 commented
Hey, just a quick question: We're switching to the idiomatic Go repository layout (see #1116). May I convert your changes?

2017-07-23 10:12 UTC, lloeki commented
Sure :)

2017-08-06 06:38 UTC, fd0 commented
Hm, it seems I'm not allowed to push into your branch. Could you please check if you've enabled this feature? https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

2017-08-16 13:30 UTC, lloeki commented
Weird, that setting is active:

![screen shot 2017-08-16 at 15 20 07](https://user-images.githubusercontent.com/75445/29365580-ccc604c4-8297-11e7-905c-de171f4f5e7e.png)

Anyway, I rebased.

2017-08-17 19:28 UTC, fd0 commented
Thanks a lot, I'll have a look!

2017-09-04 19:54 UTC, fd0 commented
Please excuse the long time I sat on this PR. It looks great and I've merged it. Thanks a lot for your work!

2017-09-04 19:58 UTC, merged

2017-09-05 07:43 UTC, lloeki commented
Awesome, many thanks!

2017-09-05 08:37 UTC, fd0 commented
Would you like to continue working on the timestamps issue?

2017-09-05 09:15 UTC, lloeki commented
If time is *not* of the essence on that front, yes I can get my hands on it.

2017-09-05 09:28 UTC, fd0 commented
It isn't, but we should probably document that in an issue (and that you'll work on it sometime).

2017-09-05 10:58 UTC, lloeki commented
OK, I created the issue.

2017-09-05 11:17 UTC, fd0 commented
Awesome, thanks!