forget: group-by-tags-only
restic/restic pull request #1196
Opened 2017-08-29 17:17 UTC by mungomat

This is not complete - what if "restic forget --group-by-tags --group-by-tags-only" is given?

2017-08-31 14:54 UTC, fawick commented
Travis fails because the manpage is not up-to-date in the PR. In your branch, could you please call `restic manpage --output-dir doc/man` and add this to the PR? Thanks!

2017-09-03 09:07 UTC, fd0 commented
And it needs a rebase, just like the other PR. Let us know if you need help with the rebase.

2017-09-05 06:56 UTC, middelink commented
Can I suggest to resolve this in a different way? Instead of adding --group-by-tags-only and possibly --group-by-path-ony or --group-by-host-only, make a flag specifying what your ordering needs to be --group-by=[host,path,tags]. Default to "host,path,tags" to keep functionality the same.

2017-09-05 18:38 UTC, fd0 commented
@middelink that is an excellent idea, thank you very much! We can just fill the JSON key according to what's present in `--group-by`.

@mungomat Do you think you can tackle this? Or shall I do that?

2017-09-07 19:12 UTC, fd0 commented
The CI test fail because `cmd_forget.go` is not properly formatted. May I suggest installing the script
`fmt-check` from https://github.com/edsrzf/gofmt-git-hook locally as a
pre-commit hook? It checks formatting before committing automatically, just copy
this script to `.git/hooks/pre-commit`.

2017-09-07 19:16 UTC, fd0 requested changes

2017-09-07 19:16 UTC, fd0 commented on cmd/restic/cmd_forget.go
> +	GroupByTag = strings.Contains( opts.GroupBy, "tag" )
That is very vague. I'd go for splitting `opts.GroupBy` by `,`, then iterate over the results, and use a `switch` statement that reacts on the strings `tag`, `host` and `path` and returns an error if the string is unknown.

What do you think?

2017-09-10 18:49 UTC, fd0 approved these changes

2017-09-10 18:55 UTC, fd0 commented
Good work, thanks!

2017-09-10 18:55 UTC, merged