document how to create a full backup without running restic as root
restic/restic pull request #1483
Opened 2017-12-14 19:05 UTC by dstosberg

### What is the purpose of this change? What does it change?

Add an example section to the documentation that explains how one can use restic to create a full backup without having to run it as root.

### Was the change discussed in an issue or in the forum before?

The idea occurred in discussing issue #1473.

### Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [ ] There's an entry in the `CHANGELOG.md` file that describe the changes for our users
- [ ] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2017-12-14 20:30 UTC, fawick reviewed
This PR is a great idea and very helpful, thanks for contributing to the documentation! I have some questions below.

2017-12-14 20:30 UTC, fawick commented on doc/080_examples.rst
> +   root@a3e580b6369d:/# useradd -m restic
If `sudo` is always used, would it make sense to restrict the login shell  (`-s /bin/false`), too?

2017-12-14 20:30 UTC, fawick commented on doc/080_examples.rst
> +   root@a3e580b6369d:/# sudo -u restic -H -s
There may be a good reason for it which I cannot see, but why two commands instead of, e.g. `sudo -u restic ~restic/bin/restic -r /tmp --exclude /tmp backup /`

Likewise, what is the rationale `-x`? I'd assume  backing up the whole system may  require to access multiple file systems, may it not? In case you really want to have `-x` it needs to be after `backup` as it is not a global flag.

Should `--exclude /tmp` as the repository be added here? Or how about adding `--exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/lost+found"}`

2017-12-19 02:07 UTC, eliasp commented on doc/080_examples.rst
> +   root@a3e580b6369d:/# setcap cap_dac_read_search=+ep ~restic/bin/restic
Although I agree, that restic ideally shouldn't be run as root, assigning `cap_dac_read_search` to the binary directly is dangerous as this would allow now anyone able to execute restic to also ready any system file.

I'd rather handle this by letting systemd control all those aspects.

My WIP service instance unit for restic: `/etc/systemd/system/restic@.service`
```INI
[Unit]
Description=Backup %I using 'restic'
ConditionFileNotEmpty=/etc/restic/%i/restic.env
ConditionPathExists=/etc/restic/%i/backup.exclude

[Service]
ExecStart=/usr/bin/restic backup --cache-dir=/var/cache/restic/%i --one-file-system --exclude-file=/etc/restic/%i/backup.exclude --exclude=/var/cache/* --exclude=/tmp/* --exclude=/var/tmp/* --exclude=/home/*/.cache/* --exclude=/run/* --quiet /
Type=oneshot
EnvironmentFile=/etc/restic/%i/restic.env
DynamicUser=yes
PrivateDevices=yes
CacheDirectory=restic/%i
CacheDirectoryMode=0700
ConfigurationDirectory=restic/%i
ConfigurationDirectoryMode=0700
#SystemCallFilter=@basic-io @file-system @network-io @io-event @ipc @cpu-emulation
#SystemCallErrorNumber=EPERM
AmbientCapabilities=CAP_DAC_READ_SEARCH

# TODO
# fix SystemCallFilter= usage, which currently fails, although the required tls syscall should be included in @default:
#   -- cannot set up thread-local storage: cannot set %fs base address for thread-local storage
# - does restic support sd_notify()? if not, create an RFC or PR
# - ensure systemd's ProtectSystem= (+ related options) is utilized to the fullest
# - set low io class
```

2017-12-19 07:25 UTC, fd0 commented on doc/080_examples.rst
> +   root@a3e580b6369d:/# setcap cap_dac_read_search=+ep ~restic/bin/restic
> Although I agree, that restic ideally shouldn't be run as root, assigning cap_dac_read_search to the binary directly is dangerous as this would allow now anyone able to execute restic to also ready any system file.

Indeed, and that's why the permissions are set like this:

```
   root@a3e580b6369d:/# chown root:restic ~restic/bin/restic
￼   root@a3e580b6369d:/# chmod 750 ~restic/bin/restic
￼```

Did you see that?

2017-12-19 12:27 UTC, eliasp commented on doc/080_examples.rst
> +   root@a3e580b6369d:/# setcap cap_dac_read_search=+ep ~restic/bin/restic
Missed that - sorry about the noise.

2017-12-19 20:13 UTC, fd0 commented on doc/080_examples.rst
> +   root@a3e580b6369d:/# setcap cap_dac_read_search=+ep ~restic/bin/restic
No worries :)

2018-01-07 12:29 UTC, fd0 commented
ping @dstosberg, are you still interested in continuing the work here, or should someone else take over?

2018-01-07 14:18 UTC, fd0 requested changes
Please address the issues in the comments, thanks!

2018-01-08 19:08 UTC, dstosberg commented on doc/080_examples.rst
> +   root@a3e580b6369d:/# sudo -u restic -H -s
Yes, we could easily put `sudo` and the call to `restic` a single command.

The intention for the `-x` was to prevent a clueless reader from backing up his /proc or /sys which might never actually terminate. But you are right, a proper generic exclude list, that works for most people, is a better fit. And `-x` might exclude `/home`, which is quite commonly on a separate filesystem.

2018-01-08 19:13 UTC, dstosberg commented on doc/080_examples.rst
> +   root@a3e580b6369d:/# useradd -m restic
It would not be a bad idea to do that. But personally, I find it very convenient that I can run a shell as user `restic` and use it examine or restore backups.

There are a lot of things that you could do to harden or optimize the setup. But I think that is out of the scope of this chapter.

2018-01-16 16:21 UTC, fd0 approved these changes
LGTM

2018-01-16 16:45 UTC, merged