checker: Optimize checker.Packs()
restic/restic pull request #1548
Opened 2018-01-12 02:26 UTC by ifedorenko

### What is the purpose of this change? What does it change?

Use result of single repository.List() to find both missing and
orphaned data packs. For 500GB repository this eliminates ~100K
repository.Test() calls and improves check time by >30M in my
environment (~45min before this change and ~7min after).

### Was the change discussed in an issue or in the forum before?

See #1541

### Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in a subdir of `changelog/x.y.z` that describe the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/changelog-entry.tmpl))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2018-01-18 21:33 UTC, fd0 requested changes
Awesome idea, great catch, I like it a lot! I've annotated a few minor things, afterwards it's ready to be merged!

2018-01-18 21:33 UTC, fd0 commented on internal/checker/checker.go
> +	case <-ctx.Done():
This check needs to be moved to the loop above (loading the list of IDs from the backend may take some time, and we want to check for the operation being cancelled during the load).

2018-01-18 21:33 UTC, fd0 commented on internal/checker/checker.go
> +		errChan <- PackError{ID: orphanID, Orphaned: true, Err: errors.New("not referenced in any index")}
Use `select` here and check `ctx.Done()`.

2018-01-18 21:33 UTC, fd0 commented on internal/checker/checker.go
> +		errChan <- PackError{ID: missingID, Err: errors.New("does not exist")}
Again, use `select` and check `ctx.Done()`.

2018-01-19 02:05 UTC, ifedorenko commented
I made the requested changes, thank you for the feedback. 

PS: I just realized CONTRIBUTING.md asks for new commits added to the pull request instead of `git commit --amend` I am used to. My apologies, will use new commits the next time.

2018-01-19 12:01 UTC, fd0 commented
Thanks! Don't worry about amending the patches, I've just changed the text in CONTRIBUTING.md slightly, amending commits is also fine. What's the best solution (amending or adding new commits) depends on the situation, use common sense. It's fine here :)

2018-01-19 12:02 UTC, fd0 reviewed
LGTM!

2018-01-19 12:06 UTC, merged