Changed Backend.Load to access consumer callback func WIP
restic/restic pull request #1560
Opened 2018-01-17 05:13 UTC by ifedorenko

This pull request is meant to illustrate one of possible ways to address problems described in #1559.

The idea is to change Backend.Load to access consumer callback func and encapsulate reader open/consume/close logic in single place shared by all clients.

2018-01-19 03:26 UTC, ifedorenko commented
I am done with this prototype and would appreciate some feedback.

The main idea of the change is to let `Backend.Load` retain ownership of the file Reader, which allows the backend implement download-retry logic and guarantee open readers are never leaked by the client.

For example, here is how updated checker code looks like:

```go
packfile, err := fs.TempFile("", "restic-temp-check-")
...
var hash restic.ID
var size int64
err = r.Backend().Load(ctx, h, 0, 0, func(rd io.Reader) (err error) {
	_, err = packfile.Seek(0, io.SeekStart)
	if err == nil {
		err = packfile.Truncate(0)
	}
	if err != nil {
		return err
	}
	hrd := hashing.NewReader(rd, sha256.New())
	size, err = io.Copy(packfile, hrd)
	hash = restic.IDFromHash(hrd.Sum(nil))
	return err
})
if err != nil {
	return errors.Wrap(err, "checkPack")
}
```

Note that content consumer callback must be idempotent to handle download retries.

2018-01-24 20:36 UTC, fd0 commented
This is a very interesting idea, I'll think about it! It's astonishing what you can do with closures.

2018-01-24 20:45 UTC, fd0 commented
Also needs a rebase to master, sorry ;)

2018-02-10 20:29 UTC, fd0 commented
I've thought about your idea, and I like it! This can also be done for `Save()`...

2018-02-11 00:22 UTC, ifedorenko commented
Apart from few TBD method comments, anything you'd like me to fix/change in the pull request?

I don't particularly like how `DefaultLoaderBackend` is injected in backends, but I don't know how to do this better/cleaner in Go. Any suggestions?

Also, I prefer to deal with `Save` separately. I don't see how to apply callback to Save, or at least what advantages that would provide, to be honest.

2018-02-11 13:40 UTC, fd0 requested changes
Let's leave `Save` out for now, we'll talk about it in a different issue.

I also don't like how the `DefaultLoaderBackend` is used, it touches way too much points for so few lines of code. IMHO, the abstraction is not worth it and makes the code more complicated. At the moment, I'd prefer to just copy the few lines into every backend. We should add tests for that into the backend tests, to make sure the backends properly deal with the function we pass into `Load()` (close the file on error, passes back the error returned by the func etc.)

The modification of the `Backend` `Load()` method looks fine to me, and I also like the way it improves the code using a backend!

So, what we need to do in my opinion:
 * Remove the `DefaultLoaderBackend`, copy the code into each backend
 * Process the commits that I've added inline

2018-02-11 13:40 UTC, fd0 commented on internal/restic/backend.go
> +		return err
Add `_ = rd.Close()` here to make it explicit (remove the `defer` below)

2018-02-11 13:40 UTC, fd0 commented on internal/restic/backend.go
> +	defer rd.Close() // ignore errors closing the reader
Remove the defer, I've been bitten by defer before, and I prefer to have this dealt with explicitly.

2018-02-11 13:40 UTC, fd0 commented on internal/restic/backend.go
> +	return consumer(rd)
Then we need to deal with the error here explicitly also, e.g.:
```go
err = consumer(rd)
if err != nil {
  _ = rd.Close()
  return err
}
return rd.Close()
```

2018-02-11 13:40 UTC, fd0 commented on internal/backend/utils.go
> +		buf, err = ioutil.ReadAll(rd)
Hm, I'm not sure if we should use the same `err` variable within the func and outside. That may lead to problems when the func is called repeatedly. What are your thoughts?

What about this:
```go
err = be.Load(ctx, h, 0, 0, func(rd io.Reader) (ierr error) {
￼		buf, ierr = ioutil.ReadAll(rd)
        return ierr
￼￼})
```

This happens a lot further down in the commit.

2018-02-11 13:40 UTC, fd0 commented on internal/repository/repack.go
> +		// TODO very similar code in checker, consider moving to utils.go
Don't leave "TODO" comments, I consider this a code smell ;)

2018-02-11 17:35 UTC, ifedorenko commented
@fd0 I replaced `restic.DefaultLoaderBackend` with `backend.DefaultLoad` func. 

I still don't like the idea of copy&pasting the same Load implementation in all backends, especially given how many comments you had around error handling, but not sure if the new `backend.DefaultLoad` is much better compared to my original proposal. What do you think?

(I'll update the pull request according to your other comments hopefully today, but may take few days)

2018-02-12 05:02 UTC, ifedorenko commented
I am done with the code changes but still need to do git history grooming. I'll prepare pull request for merge tomorrow if you don't see any other problems. Please let me know.

2018-02-16 20:50 UTC, fd0 approved these changes
LGTM!

I don't really like having to call `backend.DefaultLoad` everywhere, but I failed to come up with a better idea, so we're going to use that.

2018-02-16 21:55 UTC, ifedorenko commented
Okay I'll finish the pull request later tonight.

2018-02-17 22:25 UTC, fd0 approved these changes

2018-02-17 22:25 UTC, merged