doc: Add more info about using pre-compiled builds.
restic/restic pull request #1673
Opened 2018-03-15 18:12 UTC by rawtaz

### What is the purpose of this change? What does it change?
Add more information about the availability and usage of pre-compiled builds from both the stable releases page at GitHub and the restic beta build site.

### Was the change discussed in an issue or in the forum before?
Yes, in https://forum.restic.net/t/readthedocs-debian-install-feedback/513.

### Checklist
- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/changelog-entry.tmpl))
- [ ] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2018-03-15 20:04 UTC, fd0 requested changes
LGTM, just a minor thing :)

Thanks!

2018-03-15 20:04 UTC, fd0 commented on doc/020_installation.rst
> +the `restic beta download site <https://beta.restic.net>`__. These too are
You could use the following link, then the latest build is always shown on to:

https://beta.restic.net/?sort=time&order=desc

2018-03-15 23:07 UTC, rawtaz commented
I fixed the URL earlier today 👍

2018-03-18 18:50 UTC, fd0 approved these changes

2018-03-18 19:00 UTC, merged