Minor doc fixes/improvements
restic/restic pull request #1675
Opened 2018-03-18 16:10 UTC by oliver

### What is the purpose of this change? What does it change?

Two minor doc fixes, one minor doc improvement.

### Was the change discussed in an issue or in the forum before?

No, not that I know of.

### Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/changelog-entry.tmpl))
- [ ] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2018-03-18 18:59 UTC, fd0 requested changes

2018-03-18 18:59 UTC, fd0 commented on doc/040_backup.rst
> +    $ restic -r /tmp/backup backup ~/work --exclude="*.c" --exclude-file=exclude
For the record: This is not strictly necessary, but I think it's a good idea. Shells will resolve `--exclude *.c`, but won't resolve `--exclude=*.c`.

2018-03-18 18:59 UTC, fd0 commented on doc/040_backup.rst
> +For example maybe you want to backup files that have a certain filename
Good catch!

2018-03-18 18:59 UTC, fd0 commented on doc/040_backup.rst
> +Pathes in the listing file should be absolute. Relative pathes will be
The plural of "path" is "paths", can you please correct that?

I'm not sure if it's a good idea to recommend absolute paths for a file used with `--files-from`. There are plenty of use cases where it's important to specify relative paths. I'm fine with the hint that relative paths will be interpreted in context with the current directory (although that's basic knowledge the reader needs to be familiar with anyway), but I think we should not recommend that the file names in the file should be absolute. Can you remove the first sentence here? Thanks!

2018-03-18 18:59 UTC, fd0 commented
Thanks for taking the time to improve the documentation, it means a lot for the project! :)

2018-03-18 19:56 UTC, oliver commented
Oops, I had made a mistake when experimenting with that option, and had thought that the paths are interpreted as relative to the listing file location (not relative the CWD).

You're right, it is not necessary to document this behaviour for relative paths since they behave just as expected. I would add a note that both kinds of paths are allowed; but maybe even that note is superfluous.

2018-03-18 20:01 UTC, fd0 commented
> I had made a mistake when experimenting with that option, and had thought that the paths are interpreted as relative to the listing file location (not relative the CWD).

Ah, that explains the desire to document this ;)

2018-03-21 19:54 UTC, fd0 approved these changes

2018-03-21 19:55 UTC, merged