key: Add --new-password flag for non-interactive password changes
restic/restic pull request #1720
Opened 2018-04-15 00:45 UTC by mholt

### What is the purpose of this change? What does it change?

Makes it possible to change the password non-interactively.

I was unsuccessful trying to do it in a script by piping into stdin; restic expects 1000 bytes and the error check is wrong so it always returns an error even on early EOF; but even when corrected, I can only seem to pass one input, not two. Anyway, the whole thing doesn't matter if there's a nifty flag. :smile: 

### Was the change discussed in an issue or in the forum before?

Closes #827 

Also see https://forum.restic.net/t/changing-repo-password-without-prompt/591?u=matt

/cc @robbat2 and @HLeithner

### Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

2018-04-15 11:02 UTC, fd0 requested changes
Hey, thanks for taking a stab at implementing this! Unfortunately, you implemented something slightly different: We try hard to not take a password as a command-line parameter (because all other users of the same system are allowed to read the command-line, so they could get the password), but to read it from a file.

Would you mind changing `--new-password` to `--new-password-file` according to the proposal in the issue, and read the password from the file?

This can then also be used with third-party programs, like `restic passwd --new-password-file <(pass restic/backup/foo)`.

Thanks!

2018-04-15 14:05 UTC, mholt commented
Sure, makes sense. I've made the change!

2018-04-20 12:31 UTC, fd0 commented
Looks good, I've taken the liberty of squashing the commits, and I'll merge this after the tests ran. Thank you for your contribution!

2018-04-20 12:41 UTC, fd0 approved these changes

2018-04-20 12:52 UTC, merged