Added documentation about what happens if you run out of space during a backup
restic/restic pull request #1841
Opened 2018-06-11 21:25 UTC by jernst

### What is the purpose of this change? What does it change?

Document what happens if the repository runs out space during the backup.

### Was the change discussed in an issue or in the forum before?

https://forum.restic.net/t/limited-backup-destination-space/733/6

### Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [n/a] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [n/a] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [n/a] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2018-06-12 07:18 UTC, fd0 approved these changes
LGTM, thanks!

2018-06-13 00:12 UTC, MarkMielke requested changes

2018-06-13 00:12 UTC, MarkMielke commented on doc/040_backup.rst
> +some additional data in the repository, but the snapshop will never be
Typo on snapshot?

2018-06-13 00:12 UTC, MarkMielke commented on doc/040_backup.rst
> +created as it only would be written at the very (successful) end of
Suggest "would only"

2018-06-13 00:34 UTC, MarkMielke approved these changes

2018-06-14 17:13 UTC, merged