Add example to spot path expansion errros
restic/restic pull request #2022
Opened 2018-10-05 14:05 UTC by moritzdietz

What is the purpose of this change? What does it change?
--------------------------------------------------------
This change adds informational text to the [FAQ](doc/faq.rst). 
The information added describes on how to find out if there is a user based error for file path expansion not working as intended in a restic command.

As the wording goes: I am open to any suggestions to either rephrase it or to make it more clear if something isn't.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
Yes, on IRC.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2018-10-06 08:34 UTC, moritzdietz commented
Yes that is correct and mentioning it does not hurt :)
I will add it.

Sent from my iPhone

> On 5. Oct 2018, at 20:22, Matt Holt <notifications@github.com> wrote:
> 
> Some expansions are handled by restic, though, right? Like glob expansions: * and ** are implemented in restic, I believe...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-10-06 10:45 UTC, moritzdietz commented
So I just updated the text to include that restic itself handles `*` and `**`.
Also changed the wording to indicate that other expansions are handled by the shell - as there are so many other expansions. I believe in bash there are at least 8.

Happy for more feedback and input :)

2018-10-06 10:55 UTC, fd0 commented
This is related to https://github.com/restic/restic/issues/2030#issuecomment-427564483

For backup targets given to restic as arguments on the CLI, neither glob expansion nor shell variable replacement is done, so if restic is called as `restic backup '*' '$HOME'`, it'll try to archive the literal files/dirs `*` and `$HOME`. This is important :)

Globbing is only expanded for lines read via `--files-from`, the code is here: https://github.com/restic/restic/blob/master/cmd/restic/cmd_backup.go#L314

Environment variables are not expanded in the file read via `--files-from`.

2018-10-06 11:00 UTC, fd0 requested changes

2018-10-06 11:00 UTC, fd0 commented on doc/faq.rst
> +Glob expansions like ** or * on the other hand are being handled by restic directly.
Unfortunately that's not the case: `*` is expanded for paths read via `--files-from`, `restic backup '*'` will try to backup the literal file called `*`. Double-star `**` is not expanded at all.

2018-10-06 11:00 UTC, fd0 commented
FYI, I also forgot most of this and had to look it up in the code :/

2018-10-06 11:01 UTC, moritzdietz commented on doc/faq.rst
> +A user wants to run the following ``restic forget`` command
Yikes, you are right! Will fix this.

2018-10-06 11:04 UTC, moritzdietz commented
> This is related to [#2030 (comment)](https://github.com/restic/restic/issues/2030#issuecomment-427564483)
> 
> For backup targets given to restic as arguments on the CLI, neither glob expansion nor shell variable replacement is done, so if restic is called as `restic backup '*' '$HOME'`, it'll try to archive the literal files/dirs `*` and `$HOME`. This is important :)
> 
> Globbing is only expanded for lines read via `--files-from`, the code is here: https://github.com/restic/restic/blob/master/cmd/restic/cmd_backup.go#L314 This will only handle `*`, not `**` (which is a custom extension we implemented for exclude files...)
> 
> Environment variables are not expanded in the file read via `--files-from`.

I pulled the part regarding * and ** from here https://forum.restic.net/t/solved-exclude-with-doesnt-work-on-fixed-path/991/8?u=moritzdietz.
But your answer here includes way more information which is great and helps me understand it better.
I will go from here and work on the wording.

2018-10-06 11:09 UTC, fd0 commented
Oh, indeed, that can be misunderstood. I've amended the forum post :)

2018-10-06 14:04 UTC, moritzdietz commented
Ok so I just commited the suggested changes and fixed the typos and minor corrections with the syntax.

2018-10-07 08:31 UTC, fd0 approved these changes
LGTM, thanks!

2018-10-07 10:11 UTC, fd0 commented
Merged in de9136b29f86216bd3e41397d19b25f26b578833, thanks!

2018-10-07 10:11 UTC, closed without merging