Add options for case insensitive includes & excludes
restic/restic pull request #2032
Opened 2018-10-07 12:03 UTC by j6s

What is the purpose of this change? What does it change?
--------------------------------------------------------
This change adds the option `--exclude-insensitive` to the `backup` and `restore` commands and the `--include-insensitive` option to the `restore` command.

These options allow for case insensitive filtering in those commands.
Take the following directory structure:
```
restic_source/file1.txt
restic_source/ignore_me/file2.txt
restic_source/IGNORE_ME/file3.txt
```

Running `$ restic backup --exclude 'ignore_me'` would ignore `file2.txt` but not `file3.txt` as the paths do not match.

Using the new flag and running `$ restic backup --exclude 'ignore_me' --exclude-insensitive` would ignore both paths as the exclude patter is now insensitive.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
Resolves #1985 

Additional Questions
------------------------
This turned out to be a more in-depth PR than I would have thought. This PR implements these options in the commands themselves - however it may be better to move this kind of case-insensitive option to the filter methods.

Also: Should I implement a test for these flags? 
I don't really know how testing in go works but I would try my best.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

2018-10-07 12:08 UTC, rawtaz commented
What about less redundantly named options, like `--iexclude` and `--iinclude`? There's a lot of repeating in the above examples.

2018-11-25 12:45 UTC, fd0 requested changes
Thank you very much for your contribution! Most looks great already, there are a few things that I think needs changes, I've added a few comments. Please let me know if you need any help!

I've also taken the liberty of rebasing on the latest master branch and resolving the merge conflict there.

2018-11-25 12:45 UTC, fd0 commented on cmd/restic/cmd_restore.go
> +		matchedInsensitive, _, err := filter.InsensitiveList(opts.InsensitiveExclude, item)
Unfortunately this is inefficient and does not work:
 * The function has a side effect of converting all strings in `opts.InsensitiveExclude` to lower case over and over again for every file that is to be restored
 * The `item` needs to be converted to lower case before passing it to the function

I suggest removing `InsensitiveList`, converting `opts.InsensitiveExclude` to lower case once, and then using `filter.List(opts.InsensitiveExclude, strings.ToLower(item)` instead. Thoughts?

2018-11-25 12:45 UTC, fd0 commented on cmd/restic/cmd_restore.go
> +		matchedInsensitive, childMayMatchInsensitive, err := filter.InsensitiveList(opts.InsensitiveInclude, item)
Same as above for include.

2018-11-25 12:45 UTC, fd0 commented on cmd/restic/exclude.go
> +		return rejectByPattern(patterns)(strings.ToLower(item))
For every file that is to be tested during backup, `rejectByPattern()` creates a new function that is instantly evaluated. What about creating the function just once, outside the closure, and then use it inside?
```suggestion
	rejFunc := rejectByPattern(patterns)
	return func(item string) bool {
		return rejFunc(strings.ToLower(item))
```

2018-11-25 12:45 UTC, fd0 commented on internal/filter/filter.go
> +func InsensitiveList(patterns []string, str string) (matched bool, childMayMatch bool, err error) {
I'd remove this as per my suggestion above and just use one list.

2019-01-06 19:45 UTC, fd0 commented
Hey, are you still interested in working on this?

2019-01-06 22:37 UTC, j6s commented
Sorry -

totally forgot about this PR.
Will make the requested changes shortly.

2019-01-07 07:12 UTC, fd0 commented
Awesome, thanks!

2019-02-10 11:40 UTC, fd0 approved these changes
LGTM, thanks!

2019-02-10 11:40 UTC, merged