Fix reading password from stdin
restic/restic pull request #2221
Opened 2019-03-26 15:37 UTC by pschultz

What is the purpose of this change? What does it change?
--------------------------------------------------------

Reading the password from non-terminal stdin used io.ReadFull with a
byte slice of length 1000.

We are now using a Scanner to read one line of input, independent of its
length.

Additionally, if stdin is not a terminal, the password is read only
once instead of twice (in an effort to detect typos).

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

https://github.com/restic/restic/issues/2203

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2019-03-26 15:55 UTC, pschultz commented
I just realized that changing readPassword isn't necessary if we're only reading once from stdin. The second ReadFull call returns EOF, not ErrUnexpectedEOF. EOF isn't handled, and that causes the problem.

So there are a few options:
- Leave the PR as-is anyway
- Fix only the error handling in readPassword and continue reading the password twice, even from non-terminals (I find this very unintuitive)
- Revert the change to readPassword and keep the change to ReadPasswordTwice

2019-04-13 12:07 UTC, fd0 commented
> Let me know if you want me to revert the change to readPassword.

Please leave it, I think it's much cleaner than what we had before :)

2019-04-13 12:15 UTC, fd0 requested changes
The code looks great, just a few minor things in the changelog. Afterwards it can be merged by a maintainer. Thanks for solving this issue!

2019-04-13 12:15 UTC, fd0 commented on changelog/unreleased/issue-2203
> +without having to pad the input to 1000 characters.
Please leave out the second half of the sentence, we're trying to write the changelog for users, and that's a (rather obscure) implementation detail :)

2019-04-13 12:15 UTC, fd0 commented on changelog/unreleased/issue-2203
> +Additionally the password is now only read once from non-terminal stdin.
I'd also leave the last two paragraphs out of the changelog. Reading the password from stdin for most commands did not work properly (or it was very hard to get it working), so I think this isn't used by anybody. Also, the code is very old and it was only reported recently...

2019-04-15 08:06 UTC, pschultz commented
@fd0, I amended the commit with the updated changelog.

2019-04-22 18:59 UTC, fd0 approved these changes
LGTM, thanks!

2019-04-22 19:00 UTC, merged