find command: don't abort on tree load errors
restic/restic pull request #2231
Opened 2019-03-30 01:01 UTC by cdhowie

What is the purpose of this change? What does it change?
--------------------------------------------------------
As per #2224, this changes find not to abort when a tree can't be found.  Instead, the tree ID and referent snapshot ID are displayed.  This makes it easier to recover a broken repository by forgetting any snapshots that refer to missing objects.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
A few times on the forum:

* https://forum.restic.net/t/repository-damaged-after-accidentally-deleting-data-files/1516/17
* https://forum.restic.net/t/unable-to-check-or-prune/1239/12

Checklist
---------
- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

Comments on above:

* There's a few cursory tests for find, but not ones that use many of the options.  This is also a particularly hard change to construct a test repository for, at least automatically.
* It was not documented before that find stops on a tree load error, so there aren't really any sensible changes to be made.

2019-04-13 12:47 UTC, fd0 requested changes
Thank you very much for your contribution! The code looks great, just a minor thing: I'd like to suggest using `Warnf()` instead of `Printf()`, so the warning is printed to stderr instead of stdout. What do you think?

2019-04-13 12:47 UTC, fd0 commented on cmd/restic/cmd_find.go
> +			Printf("Unable to load tree %s\n ... which belongs to snapshot %s.\n", parentTreeID, sn.ID())
```suggestion
			Warnf("Unable to load tree %s\n ... which belongs to snapshot %s.\n", parentTreeID, sn.ID())
```

2019-04-13 12:47 UTC, fd0 commented on cmd/restic/cmd_find.go
> +			Printf("Unable to load tree %s\n ... which belongs to snapshot %s.\n", parentTreeID, sn.ID())
```suggestion
			Warnf("Unable to load tree %s\n ... which belongs to snapshot %s.\n", parentTreeID, sn.ID())
```

2019-04-13 20:33 UTC, cdhowie commented
I think this one could go either way.  Here is my take on it.

The point of having stdout and stderr is so that output can be separated from diagnostic information, particularly in the case where the output needs to be read by another program.

I'm not sure how find works with `--json` (I admittedly did not test it before submitting the PR).  If it supports that, then we have to decide if this is diagnostic information for humans (it should go to stderr) or it's relevant results from the operation (it should be added to the JSON structure).

Not running in JSON mode, the same question applies: are these errors considered important output from the requested operation, or a diagnostic that should be relegated to a side-channel?

IMO, if you're running find with `--blob` or `--tree` then your repository has problems and you're trying to figure out why.  In that case, I think that these warnings are directly related to the purpose of the command: someone is asking "what is wrong with my repository?" and therefore they should be part of the output.

But I will not argue if you'd rather have them on stderr because I think a case can be made for both options.

2019-04-14 17:30 UTC, fd0 commented
You made a good point and I agree, let's leave it on stdout for now. Thanks!

2019-04-14 17:30 UTC, fd0 approved these changes

2019-04-14 17:38 UTC, merged