Mention Cache Directoy Tagging Standard in man page and help text
restic/restic pull request #2232
Opened 2019-04-02 14:01 UTC by jacksgt

What is the purpose of this change? What does it change?
--------------------------------------------------------
This patch makes it more explicit what is meant by the CACHEDIR.TAG file
by referring to the "Cache Directory Tagging Standard".
It not only has to have this particular name, but also a specific content
(described at http://bford.info/cachedir/spec.html), which is not immediately
obvious to the user.

At least I did not realize right away that the CACHEDIR.TAG file is supposed to contain a Signature header and was confused by the error messages restic printed ("unexpected end of file").

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

No.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] (NOT RELEVANT) I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [ ] (NOT RELEVANT) There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] (NOT RELEVANT) I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2019-04-02 14:02 UTC, jacksgt commented
I hope I have added the link to all relevant files, if not please let me know.

2019-04-13 12:17 UTC, fd0 requested changes
Great, thanks a lot! It should not have been necessary to make the change in the manpages, because those are generated automatically, but it does not hurt. Accepted! :)

2019-04-13 12:17 UTC, fd0 commented
Ah, pressed the wrong button. Sorry about that.

2019-04-13 12:17 UTC, fd0 approved these changes

2019-04-13 12:44 UTC, merged