docs: switch to gopher favicon
restic/restic pull request #2337
Opened 2019-07-13 17:33 UTC by rfjakob

What is the purpose of this change? What does it change?
--------------------------------------------------------

The favicon on restic.readthedocs.io still contained the old
superman-style logo.

This changes it to the 32x32 icon also used on https://forum.restic.net/ ,
just converted to .ico using Gimp.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Yes, https://forum.restic.net/t/new-logo-for-restic/394

Checklist
---------

- [Y] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [N] I have added tests for all changes in this PR
- [N] I have added documentation for the changes (in the manual)
- [N] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [N] I have run `gofmt` on the code in all commits
- [Y] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [Y] I'm done, this Pull Request is ready for review

2019-08-11 21:10 UTC, moritzdietz commented
Thanks for this PR! Quick question: Did you convert the `.ico` file yourself or did you copy the one used for the forum?
I am not sure if this is actually worth of mentioning in a changelog entry as it does not affect restic itself. It doesn't hurt but I am also not sure if it's actually needed/wanted by the maintainers.

2019-08-12 06:03 UTC, rfjakob commented
The forum uses a png, i took the png and converted to ico with gimp.

2019-08-12 11:12 UTC, moritzdietz reviewed
So if the maintainers decide to keep this CHANGELOG entry, I would word it differently.
See my suggested change. I don't think it is relevant how you modified the `.png` to get the favicon.

2019-08-12 11:12 UTC, moritzdietz commented on changelog/unreleased/pull-2337
> +The favicon on restic.readthedocs.io still contained the old
```suggestion
The favicon used on restic.readthedocs.io was still the old
```

2019-08-12 11:12 UTC, moritzdietz commented on changelog/unreleased/pull-2337
> +We changed it to the 32x32 gopher icon also used on https://forum.restic.net/ ,
```suggestion
We changed it to the 32x32 gopher icon also used on https://forum.restic.net/
```

2019-08-12 11:12 UTC, moritzdietz commented on changelog/unreleased/pull-2337
> +just converted to .ico using Gimp.
```suggestion
```

2019-11-20 22:52 UTC, rawtaz requested changes
Wow, there certainly seems to be *a lot* to take into account with favicon, if you read https://stackoverflow.com/a/23734416. For constructive reasons I think we can just replace the file for now, if there's trouble with it down the road, let's address it then.

@rfjakob I agree with @moritzdietz that for this type of change, an entry in the changelog adds little value. Can you please remove those changes (keeping only the new favicon file), and amend/squash so there's just one commit? Let us know if you need help 👍 

Thanks!

2020-02-12 23:14 UTC, rawtaz approved these changes
I removed the changelog file (not needed for documentation changes), thank you very much for this nice little piece of contribution! :)

2020-02-12 23:14 UTC, merged