Tip to configure antivirus on Windows
restic/restic pull request #2358
Opened 2019-08-01 08:05 UTC by filippobottega

What is the purpose of this change? What does it change?
--------------------------------------------------------
Added a tip to configure antivirus to exclude restic process.
Just a little improvement of the documentation.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Checklist
---------

- [ ] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [X] I'm done, this Pull Request is ready for review

2019-08-11 20:16 UTC, moritzdietz requested changes
Hey! Thanks for taking the time to update the docs.
I have added some suggestions to fix some grammar issues as well as keep the general style of writing with the previous sentence.
I also removed the bracketed part as antivirus programs sometimes require the full path and sometimes just the name etc. so we just can't know if it is the full path. By saying that one has to add the restic binary to an exclusions list, there is no issue with the wording.

Other than that, LGTM.

2019-08-11 20:16 UTC, moritzdietz commented on doc/faq.rst
> +In some cases the real-time protection of antivirus software can interfere with restic's operations. If you are experiencing bad performance you can try to temporarily disable your antivirus software
```suggestion
In some cases the real-time protection of antivirus software can interfere with restic's operations. If you are experiencing bad performance you can try to temporarily disable your antivirus software to find out if it is the cause for your performance problems. If you are certain that the antivirus software is the cause for this and you want to gain maximum performance, you have to add the restic binary to an exclusions list within the antivirus software.
```

2019-11-12 09:26 UTC, hickford commented
Windows Defender is the default and most common antivirus software on Windows. This worked for me:

![image](https://user-images.githubusercontent.com/105314/68659033-d483c600-0536-11ea-8b69-77cac0a9bb93.png)

2019-11-13 16:42 UTC, ProactiveServices commented
@hickford I'd suggest that it would be more useful to diagnose and resolve why Windows Defender is causing problems with restic. I haven't come across this myself, with that combination, on several machines. There's a mention of it [here](https://forum.restic.net/t/windows-defender-causes-10x-slowdown/925/13) but that's over a year old.

2019-11-13 16:58 UTC, moritzdietz commented
Honestly, I don't think restic can do anything about this.
If you google windows defender problems in regard to slowdowns this is a topic that comes up with lots of other applications.

2019-11-20 21:56 UTC, rawtaz requested changes
I don't think this addition will do any harm, so let's merge it. But before we do that, can you please squash all the commits into one? Thanks!

2019-11-29 17:36 UTC, filippobottega commented
Sorry, I don't understand if I have to do something or not...
What does it means "squash all the commits into one"? How can I do it?

2019-11-29 19:28 UTC, fd0 commented
I've squashed the commits and merged this as 6c700f95b5dd54a5fac47fc12253828462a5f8b2, thanks for your contribution!

2019-11-29 19:28 UTC, closed without merging