Clarify docs for Backblaze B2 support
restic/restic pull request #2368
Opened 2019-08-11 01:32 UTC by rlue

What is the purpose of this change? What does it change?
--------------------------------------------------------

Clarifies the access privileges required for Backblaze B2 application keys.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Issue #2293 

Checklist
---------

Most items not applicable, since the proposed change is to documentation only.

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2019-08-11 20:06 UTC, moritzdietz requested changes

2019-08-11 20:06 UTC, moritzdietz commented on doc/030_preparing_a_new_repo.rst
> +.. note:: As of version 0.9.2, restic supports both master and non-master `application keys <https://www.backblaze.com/b2/docs/application_keys.html>`__. If using a non-master application key, ensure
Small typo in there. You are missing a `t` in the sentence.  
Also added the info that the RW access is for the bucket.
```suggestion
.. note:: As of version 0.9.2, restic supports both master and non-master `application keys <https://www.backblaze.com/b2/docs/application_keys.html>`__. If using a non-master application key, ensure that it is created with at least **read and write** access to the B2 bucket. On earlier versions of restic, a master application key is required.
```

2019-08-11 20:07 UTC, moritzdietz commented
Other than that LGTM.

2019-11-20 22:23 UTC, rawtaz requested changes
@rlue I like it. But can you please squash the two commits into one, before we merge? Let me know if you need help. Thanks.

2019-11-21 02:56 UTC, rlue commented
Done!

2019-11-21 21:04 UTC, rawtaz requested changes
It seems like the two latest commits in this PR are from https://github.com/restic/restic/pull/2394 and unrelated to this PR. I guess something got messed up.

@rlue Can you please remove the two latest commits in this PR, so it only contains the one commit with relevant changes?

2019-11-22 10:09 UTC, rlue commented
Dunno how that happened! We're back to one commit on this PR now.

2019-11-22 10:10 UTC, rawtaz approved these changes
LGTM!

2019-11-22 10:10 UTC, merged