Support IPv6 in SFTP backend
restic/restic pull request #2592
Opened 2020-02-19 15:15 UTC by greatroar

What is the purpose of this change? What does it change?
--------------------------------------------------------

IPv6 addresses can now be used in sftp backend specifiers. Also, setting port numbers for sftp is documented and ssh command lines are more in line with the OpenSSH manual.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

#1952 tried to achieve the same, but in a more complicated way.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2020-02-29 16:53 UTC, fd0 commented
Thank you very much! Just to confirm: all the changes here are backwards-compatible, right?

2020-02-29 17:28 UTC, greatroar commented
Yes, they are.

2020-03-01 09:41 UTC, fd0 requested changes
LGTM, only a changelog entry is missing. I would have done that, but it seems you have disabled  [allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) :)

2020-03-01 10:05 UTC, greatroar commented
I had actually prepared an entry, but forgot to push it. It's on the branch now.

2020-03-01 18:38 UTC, fd0 commented
Ok, cool! I'm curious though: did you disable "edits from maintainers" on pupose?

2020-03-01 18:38 UTC, fd0 approved these changes

2020-03-01 18:38 UTC, merged

2020-03-01 20:06 UTC, greatroar commented
Yes, but mostly because I was too lazy to read up what it allowed. I'll probably leave it on next time.