Add --insecure-skip-tls-verify flag to disable SSL cert verification
restic/restic pull request #2657
Opened 2020-03-20 15:46 UTC by mansam

What is the purpose of this change? What does it change?
--------------------------------------------------------

This adds a flag to disable TLS certificate verification for self-signed certificates as described in https://github.com/restic/restic/issues/2656.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Closes https://github.com/restic/restic/issues/2656

Checklist
---------

- [ ] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

2020-04-28 18:05 UTC, apollotonkosmo commented
@mansam this is indeed very useful. I used your repo/branch on my machine and it works. Why isn't this still merged?

2021-07-26 13:32 UTC, ofinto commented
I agree with @apollotonkosmo, this is a very useful feature. I tried to use restic with self-signed certs and for that I needed to create PKI with CA, that's more difficult than ignoring ssl. Many people can use restic in privat network with minio.

2021-07-30 21:31 UTC, MichaelEischer requested changes

2021-07-30 21:31 UTC, MichaelEischer commented on cmd/restic/global.go
> +	f.BoolVar(&globalOptions.InsecureSkipTLSVerify, "insecure-skip-tls-verify", false, "skip TLS certificate verification when connecting to the repo (insecure)")
Please rename the flag to `--insecure-tls`. Although technically correct, the current name is rather hard to parse.

2021-07-30 21:31 UTC, MichaelEischer commented on changelog/unreleased/issue-2656
> +https://github.com/restic/restic/issues/2656
Please also add a link to this PR.

2021-09-19 12:52 UTC, MichaelEischer commented
@mansam Are you still interested in getting this PR merged? I wanted to make the cleanups myself, but wasn't allowed to push to your branch.

2021-09-21 14:32 UTC, mansam commented
@MichaelEischer Apologies for the delay in responding to this. I am, I'll update the PR shortly.

2021-09-22 19:39 UTC, MichaelEischer approved these changes
LGTM. Thanks for the cleanup!

2021-09-22 19:40 UTC, merged

2023-08-25 09:56 UTC, lucasmlousada-scality reviewed
Thanks :)