Add JSON documentation
restic/restic pull request #2740
Opened 2020-05-16 04:48 UTC by metalsp0rk

What is the purpose of this change? What does it change?
--------------------------------------------------------

Adds JSON documentation to the "scripting" section of the docs.  

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Yes, issue #2107

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR 
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2020-05-16 05:41 UTC, metalsp0rk commented
Hmmm, the Linux builds passed, OSX didn't.  This seems like a fluke.

2020-05-24 22:49 UTC, metalsp0rk commented
rebased on latest master

2020-06-11 18:26 UTC, MichaelEischer requested changes
The current description does not detail on what the overall output structure looks like. Is it one line per element, a large entry or a stream of individual JSON elements as in the backup command?

The style of describing a field must be identical across different commands. Currently there are at least two different ways to word a field description.

The explanations seem to cover all commands except the `forget` command. I didn't verify that each description block includes all existing fields. As mentioned in the comments at least some fields are missing.

2020-10-08 15:18 UTC, MichaelEischer commented
Any progress here?

2020-11-26 07:16 UTC, metalsp0rk commented
Picking this up again, expect some commits in the next couple days.  I'm marking concerns resolved as I address them.

2020-11-26 07:35 UTC, metalsp0rk commented on doc/075_scripting.rst
> +| ``excludes``   | contains a list of paths and globs that were excluded from the backup. |
Has this been fixed?  If not, I'll make a PR for it, since that's a bug, I suspect we might want to leave that as is and just get a fix in.

2020-11-26 07:52 UTC, metalsp0rk commented on doc/075_scripting.rst
> +
The forget command doesn't seem to output any JSON:

```
$ ./restic snapshots -r ~/test_repo
repository a0989999 opened successfully, password is correct
ID        Time                 Host        Tags        Paths
------------------------------------------------------------------------------
75e03da4  2020-11-25 22:44:28  monolith                /home/kbrennan/Videos

5224a5e0  2020-11-25 22:44:56  monolith                /home/kbrennan/Pictures
                                                       /home/kbrennan/pics

c1983770  2020-11-25 22:46:11  monolith                /home/kbrennan/vids

b80b8e20  2020-11-25 23:40:50  monolith                /home/kbrennan/vids

955cad15  2020-11-25 23:40:55  monolith                /home/kbrennan/vids
------------------------------------------------------------------------------
5 snapshots
$ ./restic forget --json -r ~/test_repo 955cad15 | jq
$ ./restic snapshots -r ~/test_repo
repository a0989999 opened successfully, password is correct
ID        Time                 Host        Tags        Paths
------------------------------------------------------------------------------
75e03da4  2020-11-25 22:44:28  monolith                /home/kbrennan/Videos

5224a5e0  2020-11-25 22:44:56  monolith                /home/kbrennan/Pictures
                                                       /home/kbrennan/pics

c1983770  2020-11-25 22:46:11  monolith                /home/kbrennan/vids

b80b8e20  2020-11-25 23:40:50  monolith                /home/kbrennan/vids
------------------------------------------------------------------------------
4 snapshots

```

Given the non-json output for forget, I presume this is not intended.

```
$ restic forget  -r ~/test_repo d332874a
repository a0989999 opened successfully, password is correct
[0:00] 100.00%  1 / 1 files deleted
```

2020-11-26 09:46 UTC, aawsome commented on doc/075_scripting.rst
> +
Is this the issue #3117?

2022-09-13 20:38 UTC, rawtaz commented
Seriously, is this worth the work? I mean, anyone wanting to consume the JSON output from whatever command can simply run it and see what the actual output and JSON structure is. This is the most accurate way of knowing what it looks like, more so than looking at some hopefully up to date documentation. Even if you were to do that, you'd still want to inspect the *actual* output when you configure the consumer of it..

2023-06-06 21:42 UTC, davidjade commented
While I also think keeping a document like this up to date could be a challenge, just running Restic to see what output to expect also has issues. As someone who is looking at writing a client that uses json output as a stream, what I am most interested in is knowing what the range of output is that I can expect to see and act on. The normal run path is easy - do as was suggested - run it and examine the output and write something to deal with it. 

But what about error conditions? How can someone know what to expect for errors if it is not documented somewhere? Other than trying to trigger errors, some of which might not be trigger-able externally, what would be left other than spelunking through the code to try and find all the error paths to see what json output might result?

Some sort of spec is needed.

2023-06-08 23:02 UTC, MichaelEischer commented
I've extended  to documentation to (hopefully) cover most commands that provide JSON output. Having to maintain the documentation manually isn't ideal, but I don't see how we could generate it automatically.

What's not documented so far is the data type of each field and whether it is optional.

2023-07-08 21:33 UTC, MichaelEischer approved these changes
LGTM. The documentation can still be expanded later on, but should be good enough as a starting point.

2023-07-08 21:34 UTC, merged