Add zip support to the `dump` command
restic/restic pull request #3081
Opened 2020-11-10 01:55 UTC by DRON-666

What does this PR change? What problem does it solve?
-----------------------------------------------------

This PR loosely based on @brentadamson PR [#2433](https://github.com/restic/restic/pull/2433), the main difference is splitting walk and tar/zip logic.
I also added some tests (copy-pasted from tar part) and fix some bugs.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

https://forum.restic.net/t/restoring-files-directly-into-a-single-compressed-archive/968/13

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2020-11-10 02:13 UTC, DRON-666 commented
I would be grateful if someone execute `go test -v -run TestWriteZip` on Linux and post the results.

2020-11-11 08:45 UTC, dimejo commented
@DRON-666:

> I would be grateful if someone execute go test -v -run TestWriteZip on Linux and post the results.

That's the only output I see after the test ran for ~3 minutes:
`?   	github.com/restic/restic	[no test files]`

2020-11-11 12:52 UTC, DRON-666 commented
Thank you and I'm sorry that I was not too specific: you should run it from `<restic repo>/internal/dump/` or use `go test -v -run TestWriteZip github.com/restic/restic/internal/dump` instead.

2020-11-11 13:07 UTC, dimejo commented
```
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/pkg/xattr v0.4.1
go: downloading github.com/restic/chunker v0.4.0
go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
go: downloading golang.org/x/sync v0.0.0-20200625203802-6e8e738ad208
go: downloading github.com/pkg/errors v0.9.1
go: downloading gopkg.in/tomb.v2 v2.0.0-20161208151619-d5d1b5820637
go: downloading github.com/cenkalti/backoff/v4 v4.0.2
go: downloading github.com/dchest/siphash v1.2.2
go: downloading github.com/elithrar/simple-scrypt v1.3.0
go: downloading golang.org/x/sys v0.0.0-20201007082116-8445cc04cbdf
=== RUN   TestWriteZip
=== RUN   TestWriteZip/single_file_in_root
    testing.go:30: using low-security KDF parameters for test
    config.go:65: disabling check of the chunker polynomial
    zip_test.go:74: chdir to /tmp/restic-test-319287848
    zip_test.go:149: Mode is -rw-r----- [000001a0] for file
    zip_test.go:90: chdir back to /home/alex/Github/restic/restic/internal/dump
=== RUN   TestWriteZip/multiple_files_in_root
    testing.go:30: using low-security KDF parameters for test
    config.go:65: disabling check of the chunker polynomial
    zip_test.go:74: chdir to /tmp/restic-test-671586865
    zip_test.go:149: Mode is -rw-r----- [000001a0] for file1
    zip_test.go:149: Mode is -rw-r----- [000001a0] for file2
    zip_test.go:90: chdir back to /home/alex/Github/restic/restic/internal/dump
=== RUN   TestWriteZip/multiple_files_and_folders_in_root
    testing.go:30: using low-security KDF parameters for test
    config.go:65: disabling check of the chunker polynomial
    zip_test.go:74: chdir to /tmp/restic-test-402272110
    zip_test.go:149: Mode is -rw-r----- [000001a0] for file1
    zip_test.go:149: Mode is -rw-r----- [000001a0] for file2
    zip_test.go:149: Mode is drwxr-x--- [800001e8] for firstDir/
    zip_test.go:149: Mode is -rw-r----- [000001a0] for firstDir/another
    zip_test.go:149: Mode is drwxr-x--- [800001e8] for secondDir/
    zip_test.go:149: Mode is -rw-r----- [000001a0] for secondDir/another2
    zip_test.go:90: chdir back to /home/alex/Github/restic/restic/internal/dump
=== RUN   TestWriteZip/file_and_symlink_in_root
    testing.go:30: using low-security KDF parameters for test
    config.go:65: disabling check of the chunker polynomial
    zip_test.go:74: chdir to /tmp/restic-test-459097730
    zip_test.go:149: Mode is -rw-r----- [000001a0] for file1
    zip_test.go:149: Mode is Lrwxrwxrwx [080001ff] for file2
    zip_test.go:90: chdir back to /home/alex/Github/restic/restic/internal/dump
--- PASS: TestWriteZip (0.02s)
    --- PASS: TestWriteZip/single_file_in_root (0.00s)
    --- PASS: TestWriteZip/multiple_files_in_root (0.00s)
    --- PASS: TestWriteZip/multiple_files_and_folders_in_root (0.00s)
    --- PASS: TestWriteZip/file_and_symlink_in_root (0.01s)
PASS
ok  	github.com/restic/restic/internal/dump	0.028s
```

2020-12-18 22:04 UTC, MichaelEischer requested changes
I've noticed a few smaller things which require some of cleanup. Please also rebase this branch to the current master.

2020-12-18 23:15 UTC, DRON-666 commented on doc/050_restore.rst
> +output the contents in the tar (default) or zip formats:
Fixed.

2020-12-18 23:15 UTC, DRON-666 commented on changelog/unreleased/pull-3081
> +Enhancement: Allow whole folder dump in ZIP format
Fixed.

2020-12-18 23:15 UTC, DRON-666 commented on changelog/unreleased/pull-3081
> +in the tar format. The `dump` command now have a new flag to change output
Fixed.

2020-12-18 23:15 UTC, DRON-666 commented on internal/dump/zip.go
> +var _ dumper = tarDumper{}
Fixed.

2020-12-18 23:15 UTC, DRON-666 commented on internal/dump/zip.go
> +		return errors.Wrap(err, "ZipHeader ")
Fixed.

2020-12-18 23:16 UTC, DRON-666 commented on internal/dump/zip_test.go
> +func TestWriteZip(t *testing.T) {
Done.

2020-12-18 23:16 UTC, DRON-666 commented on internal/dump/zip.go
> +		dmp.w.Close()
This will require adding a `Close` method to the `Dumper` interface and would result in more lines of code with no benefit.

2020-12-18 23:17 UTC, DRON-666 commented on changelog/unreleased/pull-3081
> +Previously, restic can dump the contents of a whole folder structure only
Fixed.

2020-12-18 23:47 UTC, DRON-666 commented on internal/dump/zip.go
> +		dmp.w.Close()
Never mind, I fixed it anyway.

2020-12-19 10:33 UTC, MichaelEischer approved these changes
LGTM. Thanks!

2020-12-19 10:33 UTC, merged