Init command JSON output
restic/restic pull request #3132
Opened 2020-11-28 10:06 UTC by metalsp0rk

What does this PR change? What problem does it solve?
-----------------------------------------------------

Enablement of JSON output on the init command.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Fixes #3124

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2020-11-29 18:41 UTC, MichaelEischer requested changes
I've added a few minor comments to the PR. However, there's one point which requires discussion: All other places in restic just return the standard error message when an error happens and don't encode those as JSON. It might for now be better to stay consistent with the other commands.

2020-11-29 18:41 UTC, MichaelEischer commented on cmd/restic/cmd_init.go
> +				Status     string `json:"status"`
Please extract the definition into a single place.

2020-11-29 18:41 UTC, MichaelEischer commented on cmd/restic/cmd_init.go
> +			return errors.Fatalf(toJSONString(status))
Please use `errors.Fatal(...)` here.

2020-11-29 18:41 UTC, MichaelEischer commented on cmd/restic/cmd_init.go
> +			Id:         s.Config().ID[:10],
The JSON output should contain the full ID.

2020-11-29 18:41 UTC, MichaelEischer commented on cmd/restic/cmd_init.go
> +		Warnf("Could not encode JSON string")
I think it's better to `panic` here. The warning would garble the (non-existent) JSON output.

2020-11-29 18:41 UTC, MichaelEischer commented on changelog/unreleased/issue-3124
> +https://github.com/restic/restic/issues/3124
This should also link to the PR.

2020-11-29 18:41 UTC, MichaelEischer commented on cmd/restic/cmd_init.go
> +			Id         string `json:"id"`
The standard capitalization for `ID` of variables names in restic is all caps (The JSON field name is fine).

2020-11-29 19:17 UTC, metalsp0rk commented
>there's one point which requires discussion: All other places in restic just return the standard error message when an error happens and don't encode those as JSON. It might for now be better to stay consistent with the other commands.

So my rationale here is that it would benefit us to output errors as a JSON object because if a wrapper script is expecting JSON output, the script will not be able to easily handle non-JSON output errors.  Of course, it could just panic and alert the user, but in some cases, issues that cause failure could be automatically solved by a wrapper script.

I'm okay with staying consistent with other commands for now.  Maybe roll those error handling changes into another PR if we decide we want that, down the line.

2021-09-07 19:58 UTC, metalsp0rk commented
I'm ready to merge this.  Can I get another review on this?

2022-10-21 20:37 UTC, MichaelEischer commented
> I'm ready to merge this. Can I get another review on this?

I totally forgot about this PR. It's now rebased and slightly cleaned up. The `status` field is now called `message_type` as that is also used to identify the message type in other places.

The remaining part is to decide on a `message_type` name. Right now, it is `repository_created`, although something shorter like `summary` might also be suitable.

2022-12-02 20:33 UTC, MichaelEischer approved these changes
LGTM.

2022-12-02 20:49 UTC, merged