Add option to limit snapshots list
restic/restic pull request #3167
Opened 2020-12-16 09:52 UTC by renard

This patch adds a `--limit` option to limit snapshots list to the n
last snapshots. It is very similar to the `--last` one but does not
limit to one entry.

Output example:

    $ restic snapshots --limit 2
    repository 0d3eb989 opened successfully, password is correct
    ID        Time                 Host        Tags        Paths
    ------------------------------------------------------------
    5a33bdcc  2020-12-14 12:30:00  local                   /home
    73887d8e  2020-12-15 12:30:00  local                   /home
    ------------------------------------------------------------
    2 snapshots

To keep compatibility with previous version a new function has been
added: FilterSnapshotsWithLimit. This function that filters a list of
snapshots to only return the N last entries for each hostname and
path. FilterLastSnapshots calls FilterSnapshotsWithLimit(list, 1).

Signed-off-by: Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>

What does this PR change? What problem does it solve?
-----------------------------------------------------

`--last` option limit to the very last snapshot for each hosts. In
some case you want to show the n last snapshots. For example if you
want a weekly report of daily snapshot do cannot have this but by
using shell tools and wont report the corect number of snapshots.

This PR adds a `--limit` to limit display of the n last snapshots (see
above).

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

No.

Checklist
---------

- [X] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [X] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [X] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [X] I have run `gofmt` on the code in all commits
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

2020-12-16 10:07 UTC, renard commented
I didn't want to do deep changes with this patch. I am not sure that *cobra* allows to have flags with optional value.

Ideally it would be better to reuse the `--last` with following behavior:

* not set: list all snapshosts
* `--last`: only list last snapshot (current behavor)
* `--last 10`: only list last 10 snapshots (what `--limit actually does).

2020-12-16 11:57 UTC, rawtaz commented
I agree that reusing the `--last` option is better than introducing a `--limit` option.

2020-12-16 14:05 UTC, renard commented
What would be the best option then?

I can convert `--last` to take an integer argument. I am not sure I can define it to act like I suggested above.
Or I can make it require an argument but this may break existing scripts.

OTOH is it a problem to change `FilterLastSnapshots` to accept a `limit` argument? or would it be better to introduce the `FilterSnapshotsWithLimit` like I did?

Thanks for your feedback.

2020-12-30 16:08 UTC, MichaelEischer requested changes
It would be possible to get `--last=n` as parameter type. However, that looks like it could cause a lot of confusion, as we only use that variant for `--verbose`.

After discussing with @rawtaz we arrived at the following suggestion: Name the parameter `--latest n` instead of `limit` and deprecate `--last`, but make sure that it still works. Cobra supports this via something like `f.MarkDeprecated("last", "use --latest 1")`.

2021-03-29 14:23 UTC, renard commented on cmd/restic/cmd_snapshots.go
>  			list = FilterLastSnapshots(list)
Done. An add comment about `--last` deprecation.

2021-03-29 14:24 UTC, renard commented on doc/bash-completion.sh
> +    flags+=("--limit")
Fixed in both bash and zsh completion files.

2021-03-29 14:24 UTC, renard commented on changelog/unreleased/pull-3167
> +Enhancement: allow to limit snapshots list
Done.

2021-03-29 14:24 UTC, renard commented on changelog/unreleased/pull-3167
> +Now the `--limit n` allows to list the last n snapshots.
Done.

2021-05-13 18:20 UTC, MichaelEischer approved these changes
LGTM. I've removed the man page modification and rebased the commit to the current master branch.

2021-05-13 18:26 UTC, merged