Bump cobra and add completions for fish
restic/restic pull request #3312
Opened 2021-03-01 02:24 UTC by soraxas

This PR bumps the version of `cobra` to utilise it's new completion feature for fish (introduced in v1.0.0).

What does this PR change? What problem does it solve?
-----------------------------------------------------

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Checklist
---------

- [ ] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [ ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [ ] I'm done, this Pull Request is ready for review

2021-03-04 20:17 UTC, MichaelEischer requested changes
This PR needs further work:
- The `fish-completion.fish` should be autogenerated on release.
- In addition the way the file content currently looks, I don't understand why / whether it works. Is there some fish magic involved?
- There needs to be documentation on how to use / install the completions.
- Please add a changelog entry.
- Please fix the linter error.

I'm not too thrilled to update cobra as that leads to a way uglier manpage formatting than before. But cobra 1.1.3 seems to have at least fixed the manpage headers.

Does anyone know how to correctly update `contrib/restic.spec`?

2021-03-04 20:17 UTC, MichaelEischer commented on doc/fish-completion.fish
> +# fish completion for restic                               -*- shell-script -*-
That completion file should be generated during the release process. Please extend `helpers/prepare-release/main.go` accordingly and remove this file.

2021-03-04 20:17 UTC, MichaelEischer commented on cmd/restic/cmd_generate.go
> +	fs.StringVar(&genOpts.FishCompletionFile, "fish-completion", "", "write fish completion `file`")
Please move that option above the zsh completion file

2021-03-04 20:17 UTC, MichaelEischer commented on cmd/restic/cmd_generate.go
> +and the auto-completion files for bash and zsh, fish).
This should be `bash, fish and zsh`.

2021-03-04 20:17 UTC, MichaelEischer commented on cmd/restic/cmd_generate.go
> +	Short: "Generate manual pages and auto-completion files (bash, zsh, fish)",
Please sort the shells alphabetically

2021-03-04 20:17 UTC, MichaelEischer commented on cmd/restic/cmd_generate.go
> +func writeFishCompletion(file string) error {
Please move that function above the one for zsh.

2021-03-04 20:17 UTC, MichaelEischer commented on cmd/restic/cmd_generate.go
> +	if genOpts.FishCompletionFile != "" {
Same here

2021-03-06 04:39 UTC, soraxas commented
Hi @MichaelEischer thank you for your review and detail instruction. I've addressed all of the mentioned issues, including amending `contrib/restic.spec` for installing the completion file.

Regarding your second question, it's cobra magic where it has a hidden internal subcommand `<CMD>  __complete` (e.g. `restic __complete`) where it's used by the completion scripts to auto-complete.

With the current lint failed test, I can't seems to pin point what's causing it. I've ran `go mod tidy` on my local machine and committed that change but it's still complaining.

2021-05-15 10:09 UTC, MichaelEischer commented
Sorry, for the late reply. Could you squash the commits and then rebase them to the current master branch? Running `go mod tidy` with go 1.16 should fix the lint errors.

2021-05-21 03:50 UTC, soraxas commented
Yep squashed and rebased

2021-05-23 11:58 UTC, MichaelEischer approved these changes
LGTM. Thanks!

2021-05-23 11:58 UTC, merged