Display 'created new cache in ' message only if output is terminal
restic/restic pull request #3343
Opened 2021-03-19 11:45 UTC by hluup

What does this PR change? What problem does it solve?
-----------------------------------------------------
Makes sure that `created new cache in ` is printed only in terminals. Fixes piping output to tar without existing cache directory.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
https://forum.restic.net/t/tar-dump-without-cache/3682
https://github.com/restic/restic/issues/3334

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

2021-03-20 19:03 UTC, MichaelEischer requested changes
Thanks for the PR. The changelog entry need a few small fixes, see below.

2021-03-20 19:03 UTC, MichaelEischer commented on changelog/unreleased/issue-3334
> +if cache directory didn't exist.
Please add a (positive) final sentence which either states `This has been fixed` or something more specific like `The message is now only printed on a terminal`.

2021-03-20 19:03 UTC, MichaelEischer commented on changelog/unreleased/issue-3334
> +https://github.com/restic/restic/issues/3334
Please also include a link to this PR:
`https://github.com/restic/restic/pull/3343`

2021-03-22 09:33 UTC, hluup commented
Thank you for the review. Corrected the changelog with the proposed changes.

2021-03-27 11:43 UTC, MichaelEischer approved these changes
LGTM.

2021-03-27 11:43 UTC, merged