Document AWS_PROFILE support
restic/restic pull request #3507
Opened 2021-09-10 13:23 UTC by ahmgithubahm

What does this PR change? What problem does it solve?
-----------------------------------------------------
Since restic (or whatever library it is using) seems to respect/use AWS_PROFILE, it's worth documenting this.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
I don't think so.

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

2021-09-12 14:04 UTC, rawtaz requested changes
I requested a few changes, can you please squash it all into one single commit after they're made? 👍

2021-09-12 14:04 UTC, rawtaz commented on doc/040_backup.rst
> +    AWS_PROFILE                         Amazon credentials profile (can be used instead of the keys and region)
Can you please do the following:

- Remove "of the" in your description for `AWS_PROFILE`.
- Add also the `AWS_SHARED_CREDENTIALS_FILE` one.

2021-11-13 21:49 UTC, MichaelEischer commented
@ahmgithubahm Any progress here?

2022-02-18 22:37 UTC, rawtaz approved these changes
Thank you!

2022-02-18 22:40 UTC, merged