Support for specifying amount of data in read-data-subset
restic/restic pull request #3548
Opened 2021-10-12 09:52 UTC by gum3ng

What does this PR change? What problem does it solve?
-----------------------------------------------------
To check the data users have to use `restic check --read-data-subset=`. The read-data-subset flag does not currently support specifying a random subset of X bytes. This PR adds support for the same. 

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Fixes #3490 

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [ ] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

2021-10-24 16:28 UTC, MichaelEischer requested changes
I've added quite a few comments that must be addressed. Please also make sure to run `gofmt`.

2021-10-29 21:20 UTC, janosgyerik commented on cmd/restic/cmd_check.go
> +	}
How about simply:
```suggestion
	return err == nil
```

2021-10-29 21:20 UTC, janosgyerik commented on doc/045_working_with_repos.rst
> +Use ``--read-data-subset=SB`` to check a randomly choosen subset of the
Typo fix:
```suggestion
Use ``--read-data-subset=SB`` to check a randomly chosen subset of the
```

2021-10-29 21:20 UTC, janosgyerik commented on doc/045_working_with_repos.rst
> +of the total repository size. The behaviour of the check command following this conversion will be the same as the percentage option above.
This line seems too wide. It's 139 characters. The rest of the file seems to try to stay under 80.

2021-10-29 21:20 UTC, janosgyerik commented on cmd/restic/cmd_check.go
> -
Why remove these lines? I think it's better to only touch what's necessary for your change.

2021-10-30 07:55 UTC, gum3ng commented
I have made the necessary changes. Please let me know if any more changes are required.

2021-10-30 21:52 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +		} else if isFileSizeSuffix(opts.ReadDataSubset) {
I'd prefer to check whether `ReadDataSubset` is a percentage by looking for whether the parameter ends with `%`.

2021-10-30 21:52 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +					errors.Fatal("Could not get the file size of repo")
This line is currently a no-op. The error _must_ be returned to have any effect on the control flow. The also applies to the default case.

2021-10-30 21:52 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +
Please always run `gofmt` for every change! I'd recommend to configure it to run automatically.

2021-10-30 21:52 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +				repositorySize, err := getRepositorySize(gopts.Repo)
Just sum up all entries in the `packs` map.

2021-10-30 22:00 UTC, MichaelEischer commented
Please mark comments that have been addressed as resolved. From what I can see there are still few comments left that are still open.

Then rebase the commits on top of the current master branch and squash them (unless there's a reason to have separate commits). The PR is currently also missing a changelog entry, please add one based on the [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE) .

2021-11-01 08:21 UTC, gum3ng commented
I have rebased and squashed the commits. Please review and let me know if any more changes are required.

2021-11-01 16:12 UTC, MichaelEischer requested changes
I've a few more comments regarding the changelog. And regarding `determineReadDataSubsetType` my impression is that this method should simply be inlined.

2021-11-01 16:12 UTC, MichaelEischer commented on changelog/unreleased/issue-3490
> +Enhancement: Support for specifying file size in read-data-subset
I'd change this to
```
Support for specifying file size in `check --read-data-subset`
```
That wait it is much more obvious which command is affected by this change.

2021-11-01 16:12 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +func determineReadDataSubsetType(readDataSubset string) (DataSubsetType, error) {
I think this method should be inlined. Parsing everything twice only looks like it adds more code.

2021-11-01 16:12 UTC, MichaelEischer commented on changelog/unreleased/issue-3490
> +pack files. I have added a third method to select pack files - By specifying
Please write `We have added ...` here to better match the usual changelog style.

2021-11-01 16:12 UTC, MichaelEischer commented on changelog/unreleased/issue-3490
> +https://restic.readthedocs.io/en/latest/045_working_with_repos.html
Please remove the link to the documentation.

2021-11-01 16:12 UTC, MichaelEischer commented on changelog/unreleased/issue-3490
> +file size. This new option is available with the 'restic check' command.
The `check` command should be mentioned in the first sentence of the changelog. Otherwise it will be hard for a user to understand the explanations.

2021-11-02 04:37 UTC, gum3ng commented
I have edited the changelog and also refactored the switch such that the determineReadDataSubsetType() method is no longer needed, along with the constants for readDataSubsetType. Kindly review

2021-11-02 09:57 UTC, gum3ng commented
I have made the suggested changes. Kindly review

2021-11-05 22:28 UTC, MichaelEischer approved these changes
LGTM. Thanks for implementing the feature and keeping up with all the review rounds :-) .

2021-11-05 22:28 UTC, merged

2021-11-06 09:18 UTC, ShadowJonathan commented
Thank you so much! ❤️