Add json output for diff command
restic/restic pull request #3592
Opened 2021-12-08 09:17 UTC by vgt

What does this PR change? What problem does it solve?
-----------------------------------------------------

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Checklist
---------

- [ ] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [ ] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I have run `gofmt` on the code in all commits.
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2021-12-13 10:43 UTC, vgt commented
I am not sure about test cases for the change. Since this is the first time I use go, and there are no preexisting test cases for the diff command, I am not able to cheat myself out of this.
For the documentation in the manual, I checked how the --json flag is documented in other commands and it is only referenced in the general "--json outputs json for all supported commands".
Can someone give me some feedback on what needs to be added for this PR to be even considered?

2021-12-27 18:09 UTC, MichaelEischer requested changes
Are you aware of #2542? As explained in https://github.com/restic/restic/pull/2542#issuecomment-877796807 I don't think the output format is suitable for snapshots with lots of files in them. Please see the comment in https://github.com/restic/restic/issues/2508#issuecomment-1001683455 for my output format suggestion.

2022-01-04 19:32 UTC, vgt commented on cmd/restic/cmd_diff.go
> +		make([]Change, 0)
I did not see that point, but it makes a lot of sense.

2022-01-04 21:42 UTC, vgt commented on cmd/restic/cmd_diff.go
> +		make([]Change, 0)
I have changed the implementation to be more like what I found in the ls command. Not really happy that the output is not a valid JSON, but it is at least "consistent",

2022-01-04 21:43 UTC, vgt commented on changelog/unreleased/issue-2508
> +Enhancement #2508: Support JSON output for diff
Changed that to be the same as other changes. :)

2022-01-22 14:07 UTC, MichaelEischer requested changes
I guess my reference regarding the output format in https://github.com/restic/restic/issues/2508#issuecomment-1001683455 was not explicit enough, sorry. Please follow that format unless there is a (good) reason not to.

Once you're finished, please also squash the commits (unless you want to split the changes into several steps).

2022-01-22 14:07 UTC, MichaelEischer commented on cmd/restic/cmd_diff.go
> +		printDiffStats = func(stats *DiffStats) {
Please inline the `printDiffStats` methods and just add an if at the end of `runDiff`.

2022-01-22 14:08 UTC, MichaelEischer commented on cmd/restic/cmd_diff.go
> +		make([]Change, 0)
It is not a single JSON document. But rather a stream of JSON documents separated by new lines. That type of streaming format is rather common. Tools like `jq` also provide explicit support for it.

2022-02-05 21:51 UTC, MichaelEischer approved these changes
LGTM. Thanks for implementing this feature!

2022-02-06 10:52 UTC, vgt commented
> LGTM. Thanks for implementing this feature!

Thanks for your patience guiding through my first ever open source contribution. I just fixed a minor thing lint complained about in integration_test.go. Though it seems I cannot start the workflow to run again as far as I can tell.

2022-02-07 20:33 UTC, merged

2022-02-07 20:35 UTC, MichaelEischer commented
> Though it seems I cannot start the workflow to run again as far as I can tell.

Github has a restriction since several months that ci test for a merge request are not run automatically if it is the first contribution to a repository. This restriction is probably in place to fend of people trying to use the Github CI to mine some crypto coins.