Add support for CreationTime attribute in Windows
restic/restic pull request #3622
Opened 2022-01-06 18:56 UTC by mchowdhury

What does this PR change? What problem does it solve?
-----------------------------------------------------
File created time (an NTFS specific attribute) doesn't get backed up or restored on Windows backups. See issue #3478 

Since we don't want to modify ctimes (because it's used for file change comparison #2212) we store it as an extended attribute and restore the creation time value when the file is restored.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

This issue was filed in #3478
A related issue is #1401 for backing up entire NTFS extended attributes. This uses microsoft provided go-winio library. In the future this would be a better approach but would be a significant re-write. See this comment: https://github.com/restic/restic/issues/1401#issuecomment-392959322

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

2022-01-06 20:16 UTC, DRON-666 commented
Can you add windows attributes as well? This would solve issue #2075.

2022-01-06 21:54 UTC, mchowdhury commented
> Can you add windows attributes as well? This would solve issue #2075.

Ideally it would be nice to have all the missing attributes included. This can be done what's described in https://github.com/restic/restic/issues/1401#issuecomment-392959322

It's more effort but can be done. I would probably need some assistance with the implementation.

2022-01-07 01:27 UTC, DRON-666 commented
>Ideally it would be nice to have all the missing attributes included.

I fully agree, but adding standard attributes to you PR is just the use of `SetFileAttributes` instead of `SetFileTime`.

>This can be done what's described in #1401 (comment)

I don't think that `BackupRead/Write` API is compatible with `restic` architecture. It does not allow you to choose the type of requested information. Anyway `BackupRead/Write` is just a [userland code with bunch of NT-function calls](https://github.com/KernelPanic-OpenSource/Win2K3_NT_base/blob/master/win32/client/backup.c#L1628) and you don't need to use it.

2022-01-07 07:51 UTC, mchowdhury commented
> I fully agree, but adding standard attributes to you PR is just the use of `SetFileAttributes` instead of `SetFileTime`.

This was a good idea. I updated and tested the PR with saving and restoring file attributes in addition to creation time

2022-01-07 14:04 UTC, DRON-666 commented on internal/restic/node_windows.go
> +			return creationTime.Bytes(), nil
I don' think you need all this conversions and encoding. Simple `binary` conversion is enough:
```          
var creationTime [8]byte
binary.LittleEndian.PutUint32(creationTime[0:4], s.CreationTime.LowDateTime)
binary.LittleEndian.PutUint32(creationTime[4:8], s.CreationTime.HighDateTime)
return creationTime[:], nil
```

2022-01-07 14:05 UTC, DRON-666 commented on internal/restic/node_windows.go
> +		if err := syscall.SetFileTime(h, &c, nil, nil); err != nil {
Same as above:
```
var creationTime syscall.Filetime
creationTime.LowDateTime = binary.LittleEndian.Uint32(data[0:7])
creationTime.HighDateTime = binary.LittleEndian.Uint32(data[4:8])
if err := syscall.SetFileTime(h, &creationTime, nil, nil); err != nil {
```

2022-01-07 14:05 UTC, DRON-666 commented on internal/restic/node_windows.go
> +		}
And here too:
```
attrs := binary.LittleEndian.Uint32(data)
```

2022-01-11 19:06 UTC, mchowdhury commented
@DRON-666 Thanks again for the feedback. I made the necessary changes and tested them.
Let me know if you have any other suggestions.

2022-01-19 20:43 UTC, mchowdhury commented
@DRON-666 What else needs to be done to get this merged?

2022-01-23 15:18 UTC, hgraeber commented
It would be nice to add security information the same. Would mean to use GetFileSecurity and SetFileSecurity the get and set the DACL. Converting the descriptor to/from SDDL string representation would be even better. ConvertSecurityDescriptorToStringSecurityDescriptor and ConvertSecurityDescriptorFromStringSecurityDescriptor are helpful for that.

Maybe you consider to use a readable representation for the other attributes, too.

2022-12-16 05:10 UTC, mchowdhury commented
> It would be nice to add security information the same. Would mean to use GetFileSecurity and SetFileSecurity the get and set the DACL. Converting the descriptor to/from SDDL string representation would be even better. ConvertSecurityDescriptorToStringSecurityDescriptor and ConvertSecurityDescriptorFromStringSecurityDescriptor are helpful for that.
> 
> Maybe you consider to use a readable representation for the other attributes, too.

@hgraeber GetFileSecurity and SetFileSecurity are not currently supported by the standard go syscall library. I'm open to other suggestions. Otherwise, should we make a separate issue for file security attributes and get this merged?

2022-12-16 21:18 UTC, MichaelEischer requested changes
Mapping the creationTime / fileAttributes in to xattrs feels wrong, please just add new (optional) fields to the `Node` struct. I'd also prefer to store the creationTime as a regular timestamp and not some Windows specific timestamp format. Btw, the creationTime is known as birthTime on Linux, so it might be more appropriate to use that name (or short `btime` for the json attribute). Even though we can't write that timestamp on Linux.

The FileAttributes should also be accessible from the struct returned at https://github.com/restic/restic/blob/cccc17e4e91facdaf710dc82a59653c5c0de3156/internal/restic/node_windows.go#L56 . Adding two redundant syscalls (the two os.Stat) calls will likely hurt performance.

Judging from https://learn.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants I'm not sure whether it's a good idea to blindly store and restore arbitrary file attributes. But I'm not familiar enough with the Windows API to accurately judge that.

Restoring access permissions etc. definitely doesn't belong into this PR.

2022-12-16 21:51 UTC, mchowdhury commented
@MichaelEischer I can move the creation time directly to `ctim()` since we already make the fileattributes syscall in the struct.


For Windows file attributes, these are essentially the same as Linux extended attributes and should be backed up and restored. I figured adding it here would be the cleanest way.

How do you propose we integrate and restore them if they are added as optional attributes to the node struct?

2022-12-17 10:28 UTC, hgraeber commented
> Judging from https://learn.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants I'm not sure whether it's a good idea to blindly store and restore arbitrary file attributes. 

I think the file attributes shall not be copied blindly, because they may have some side effect and cannot be simply restored. (https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileattributesa). It is necessary to set flags on file creation or using special functions to reach the desired effect.

2022-12-17 10:31 UTC, hgraeber commented
@mchowdhury

> GetFileSecurity and SetFileSecurity are not currently supported by the standard go syscall library. I'm open to other suggestions. Otherwise, should we make a separate issue for file security attributes and get this merged?

Agreed. I will write an issue for this. There we can discuss how to implement backup of windows file security information.

2022-12-17 22:59 UTC, mchowdhury commented
@hgraeber I don't quite understand the approach you are describing, and unsure how to implement it without impacting other platforms (node.go). Should creationTime follow the same approach? If not, we can separate file attributes to a separate PR and just focus on creationTime.

Would be happy to have your help on the implementation if you have bandwidth.

2022-12-18 03:27 UTC, ProactiveServices commented
Have you considered the more unusual attributes and what happens if they cannot be restored, or what might unexpected behaviour might occur if they are restored? There's a host of weird and wonderful attributes other than the usual hidden/read-only/system. How is the restoration of a sparse file handled? What about attributes that only kernel-level code can restore? Will a restore apply to a file marked as temporary? How are you handling EFS-encrypted data? Files that have attributes that are not supported on the target filesystem?

2022-12-18 04:46 UTC, mchowdhury commented
@MichaelEischer After more research, I like your suggestion with `btime` adding it to the node, also since darwin also supports btime. I will make a new PR to support creationTime on windows and os x.  

Let's leave this PR open to discuss File Attributes on Windows. File attributes got pulled into this PR from @DRON-666 suggestion to fix issue https://github.com/restic/restic/issues/2075.

2023-04-08 15:14 UTC, heapxor commented
hello,
is that merge request stable and tested? thanks

2023-06-07 19:46 UTC, hanacchi commented
any progress on getting this merged? i would love to use restic but lack of creation time support on windows is holding me back

2023-12-07 16:49 UTC, Dobatymo commented
A file copy using the Windows Explorer doesn't preserve file creation dates (only modification dates). So I don't think restic should restore them either.

2023-12-26 12:23 UTC, tszynalski commented
> A file copy using the Windows Explorer doesn't preserve file creation dates (only modification dates). So I am not sure restic should restore them either.

Copying a file is not the same as restoring a file from backup. When you copy a file, you create a second file with the same contents – but it's not the _same_ file, so the creation date should be different. When you back up a file, you want to be able to "turn back time" and go back _to the way things were_ in the event of failure. If something is lost (such as a piece of metadata), then the restore was not complete.

2024-01-06 22:01 UTC, MichaelEischer commented
After taking a look at https://github.com/restic/restic/pull/4611 , I think we should follow that approach. The `GenericAttributes` suggested there just look like what I had in mind.

Sorry for not finding time to discuss this PR!

2024-01-06 22:01 UTC, closed without merging