Switch to azblob sdk
restic/restic pull request #4028
Opened 2022-11-20 09:58 UTC by ekarlso

This is the start to fix #3698 since that requires to take a `cred`
struct into many of the client New methods

What does this PR change? What problem does it solve?
-----------------------------------------------------

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Checklist
---------

- [ ] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [ ] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I have run `gofmt` on the code in all commits.
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2022-11-20 14:23 UTC, MichaelEischer requested changes
Thanks for the PR. Switching to the newer azure sdk is a good idea. Most comments are smaller issues, the only larger one is the `Save` method.

I'm a bit undecided how the `Save` method should look like. We basically have three options:
- change the case with <256MB files to stage and commit a block similar to saveLarge. The main difference would be that the expected md5 hash of the block is retrieved from rd.Hash()
- Always use `saveLarge`
- Always use `UploadStream`

The simplest way would be to use UploadStream, however, then we'd loose the end-to-end integrity checks for uploaded blocks. My current preference would be to use the first option, even though it's slightly more code.

2022-11-20 17:39 UTC, ekarlso commented on internal/backend/azure/azure.go
> +		urlWithSAS := fmt.Sprintf("%s/%s?%s", url, cfg.Container, sas)
That's if you are not acting on a container client directly I think (Though I can certainly test this)

2022-11-20 17:45 UTC, ekarlso commented on internal/backend/azure/azure.go
> -		if sas[0] == '?' {
Yes, point! I added it back

2022-11-20 17:52 UTC, ekarlso commented on internal/backend/azure/azure.go
> +		_, err = bc.UploadStream(ctx, azureAdapter{rd}, &blockblob.UploadStreamOptions{
> Thanks for the PR. Switching to the newer azure sdk is a good idea. Most comments are smaller issues, the only larger one is the `Save` method.
> 
> I'm a bit undecided how the `Save` method should look like. We basically have three options:
> 
>     * change the case with <256MB files to stage and commit a block similar to saveLarge. The main difference would be that the expected md5 hash of the block is retrieved from rd.Hash()
> 
>     * Always use `saveLarge`
> 
>     * Always use `UploadStream`
> 
> 
> The simplest way would be to use UploadStream, however, then we'd loose the end-to-end integrity checks for uploaded blocks. My current preference would be to use the first option, even though it's slightly more code.

I went the route you said and duplicated the saveLarge behaviour

2022-11-20 17:54 UTC, ekarlso commented on internal/backend/azure/azure.go
> +		cred, err := azidentity.NewDefaultAzureCredential(nil)
Removed from this PR

2022-11-20 17:57 UTC, ekarlso commented on internal/backend/azure/azure.go
> +		_, err = blockBlobClient.StageBlock(ctx, id, streaming.NopCloser(reader), &blockblob.StageBlockOptions{})
Thanks, added.

2022-11-20 17:57 UTC, ekarlso commented on internal/backend/azure/azure.go
> +				BlobContentMD5: []byte(rd.Hash()),
Removed UploadStream usage all together and duplicated code in saveLarge as you appointed.

2022-11-20 18:03 UTC, ekarlso commented on internal/backend/azure/azure.go
> +			return restic.FileInfo{}, nil
Removed the specifc BlobNotFound case

2022-11-23 08:42 UTC, ekarlso commented on internal/backend/azure/azure.go
> +		urlWithSAS := fmt.Sprintf("%s/%s?%s", url, cfg.Container, sas)
I fixed this and tested using SAS and it works fine.

2022-11-25 21:23 UTC, MichaelEischer commented
I've fixed the remaining review comments. Apparently the azure SDK requires golang 1.18, which would be major bump in the required golang version...

2022-11-26 19:53 UTC, ekarlso commented
@MichaelEischer idk what's up here but I get 
```
debug log file test.log
debug enabled
Fatal: create key in repository at azure:test:/ failed: StageBlock: PUT https://xxxblob.core.windows.net/test/keys/5a09ec71a89cf36911982a9de23ce53639436830a4114662fe2c457937917c9c
--------------------------------------------------------------------------------
RESPONSE 400: 400 The MD5 value specified in the request did not match with the MD5 value calculated by the server.
ERROR CODE: Md5Mismatch
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?><Error><Code>Md5Mismatch</Code><Message>The MD5 value specified in the request did not match with the MD5 value calculated by the server.
RequestId:afd69da6-501e-0038-77cf-01c51e000000
Time:2022-11-26T19:43:01.9531956Z</Message><UserSpecifiedMd5>MBrCsbYtOgytzT9iexEK4w==</UserSpecifiedMd5><ServerCalculatedMd5>H1A55QvWaykMVmhNhVDGwg==</ServerCalculatedMd5></Error>
```

Seems we're calculating or giving a mismach of the MD5?

2022-11-27 14:30 UTC, MichaelEischer commented on internal/backend/azure/azure.go
> +		buf := make([]byte, saveLargeSize)
The buffer is never filled with data. It should probably be:

```suggestion
		buf := make([]byte, rd.Length())
		_, err = io.ReadFull(rd, buf)
		if err != nil {
			return errors.Wrap(err, "ReadFull")
		}
```

2022-11-27 21:21 UTC, ekarlso commented
So now it's working that far but now it hangs on:
```processed 1 files, 8.232 KiB in 0:00
snapshot 709fadfc saved
``` 

I guess it's due to one of the locks not releasing?

2022-11-28 20:32 UTC, MichaelEischer commented
> So now it's working that far but now it hangs on:
> 
> ```
> snapshot 709fadfc saved
> ```
> 
> I guess it's due to one of the locks not releasing?

Without more context that's usually pretty hard to tell. In case of a hanging golang program it's often helpful to send a SIGQUIT to the program (ctrl+\). Then the runtime prints a stacktrace of all goroutines and exits. Here it was probably caused by a leaked token in the `Save` method.

2022-11-29 10:46 UTC, ekarlso commented
No but I well def use it before pushing more code! Thanks for the tip

2022-12-01 20:30 UTC, MichaelEischer commented
> goroutine 43 [chan send]:
> github.com/restic/restic/internal/backend/sema.Semaphore.GetToken(...)
>         /home/ekarlso/projects/evry/dds/infrastructure/docker-images/restic/internal/backend/sema/semaphore.go:27
> github.com/restic/restic/internal/backend/azure.(*Backend).List(0xc00011d290, {0xc39138, 0xc00019e140}, 0x1, 0xc0004f4080)
>         /home/ekarlso/projects/evry/dds/infrastructure/docker-images/restic/internal/backend/azure/azure.go:426 +0x35e

I have no idea which version of the code that is. But it looks like it does not include the last three bugfix commits which I've added to this PR (otherwise the line number doesn't make sense).

2022-12-04 18:30 UTC, ekarlso commented
@MichaelEischer all tests are green and the branch has been updated. Thanks for your help!

2022-12-07 20:52 UTC, MichaelEischer approved these changes
LGTM. I've squashed the commits (the bugfix commits probably aren't useful anyways) and removed the changelog.

2022-12-07 20:58 UTC, merged