gs: support other regions than us
restic/restic pull request #4226
Opened 2023-02-27 07:01 UTC by Sohalt

What does this PR change? What problem does it solve?
-----------------------------------------------------

Add an option to set the region for a bucket in google cloud storage.

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2023-04-07 13:19 UTC, MichaelEischer commented on internal/backend/gs/config.go
> +	Region      string `option:"region" help:"region for the bucket (default: us)"`
From what I understand, the region is only used when creating a bucket. That should be reflected in the help text.

2023-04-07 13:21 UTC, MichaelEischer requested changes
The code is fine, except for the one remark below. Please also add a short changelog entry and a short remark in https://github.com/restic/restic/blob/master/doc/030_preparing_a_new_repo.rst#google-cloud-storage that it's now possible to configure the region in which a new bucket is created.

2023-05-18 19:27 UTC, MichaelEischer commented
@Sohalt  are you still interested in finishing this PR?

2023-05-18 20:58 UTC, Sohalt commented
Sorry for taking so long. I hope it's fine like this.

2023-05-26 17:48 UTC, MichaelEischer approved these changes
LGTM. Thanks!

2023-05-26 17:54 UTC, MichaelEischer commented
I've rebased the PR and fixed the test failures.

2023-05-26 18:28 UTC, merged