add --stdin-from-command flag to backup command
restic/restic pull request #4254
Opened 2023-03-16 07:33 UTC by sebhoss

What does this PR change? What problem does it solve?
-----------------------------------------------------

This fixes #4251 by providing the requested `--stdin-from-command` flag to the `restic backup` command. It skips snapshot creation in case the given commands fails as determined by `exec.Cmd.Wait()` and returns the stderr of the given command as an error message back to the user.

I have not written any tests, nor documentation because I get some feedback first, whether the path taken here wrt. upstream inclusion. I am seeing various test failures in existing tests but these seem to be unrelated and might just occur because I'm building/testing the project within a container. Using these changes locally does look promising though:

```
$ ./restic backup --stdin-from-command --repo ./backup -- pg_dump -h foobar
enter password for repository: 
repository 55e7d5a0 opened (version 2, compression level auto)
using parent snapshot cc6e1dec
error: read /stdin: no data read
Fatal: unable to save snapshot: pg_dump: error: connection to database "root" failed: could not translate host name "foobar" to address: No address associated with hostname
```

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Closes #4251

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2023-03-28 21:42 UTC, Enrico204 commented
LGTM! I think that this option should be strongly suggested in the documentation in place of the current "stdin procedure".

Maybe we want to unset some sensible environment variables? (e.g., `RESTIC_PASSWORD`)

2023-03-29 05:49 UTC, sebhoss commented
Thanks for the review!

That's a good point about environment variables - I completely missed that requirement from the original ticket and thus the current code executes without any environment variables. However inheriting them and unsetting some sensible ones makes sense to me!

2023-03-29 06:35 UTC, Enrico204 commented
AFAIK, `exec.CommandContext` is creating a `exec.Cmd` with the default value (`nil`) in the `.Env` field. According to the documentation, a `nil` value in `.Env` will instruct Go to inherit the current environment set. So, the current code is already passing all env to the child process ([which seems that Borg does](https://github.com/borgbackup/borg/commit/00b09370c0078b3a6c8f522c0e6ebeea265d100c)).

A very rough way might be to remove [all prefixed variables indicated in the documentation](https://restic.readthedocs.io/en/stable/040_backup.html#environment-variables):

```diff
diff --git a/cmd/restic/cmd_backup.go b/cmd/restic/cmd_backup.go
index ee355bb42..2068d5e6b 100644
--- a/cmd/restic/cmd_backup.go
+++ b/cmd/restic/cmd_backup.go
@@ -608,6 +608,20 @@ func runBackup(ctx context.Context, opts BackupOptions, gopts GlobalOptions, ter
                        if err != nil {
                                return err
                        }
+
+                       for _, v := range os.Environ() {
+                               if !strings.HasPrefix(v, "RESTIC_") &&
+                                       !strings.HasPrefix(v, "AWS_") &&
+                                       !strings.HasPrefix(v, "ST_") &&
+                                       !strings.HasPrefix(v, "OS_") &&
+                                       !strings.HasPrefix(v, "B2_") &&
+                                       !strings.HasPrefix(v, "AZURE_") &&
+                                       !strings.HasPrefix(v, "GOOGLE_") {
+
+                                       command.Env = append(command.Env, v)
+                               }
+                       }
+
                        if err := command.Start(); err != nil {
                                return err
                        }
```

Note: I haven't tested this code.

Other options include:
- resetting the environment variables list to a safe default; or
- remove specific variables (e.g. `RESTIC_PASSWORD`), leaving others untouched

I'd argue that the the first option is too restrictive, and the second is too much maintenance burden (maintainers/developers need to remember to add new sensitive variables in the list). So, resetting variables by their prefix may be a tradeoff.

What do you think?

2023-03-29 07:19 UTC, sebhoss commented
Ah nice, I guess I misread the docs - thanks again!

Thinking about unsetting variables a bit more I'm concerned that it might be too magical for users since they cannot influence it directly. So maybe another option like `--inherit-env=true|false` would make sense? Using this flag, users could control wheher the command they are executing inherits all or none of the availble env variables.

2023-03-29 13:39 UTC, Enrico204 commented
While I agree that it might seem magical, I think too many knobs are equally bad. I don't see any use case for `RESTIC_*` variables to be passed to the child program, and, in any case, one can still "restore" variables for the child command using `env`. For example:

```sh
$ restic backup \
   --stdin-from-command \
   --repo ./backup \
   -- env RESTIC_REPOSITORY=$RESTIC_REPOSITORY pg_dump -h foobar
```

So, if a variable is removed, it can be re-added explicitly (it's safe - a pattern might match more/fewer variables tomorrow).

This needs to be clearly documented, of course :-)

2023-03-30 05:30 UTC, sebhoss commented
Yeah I agree that too many knobs do not feel that good either. I think in the end I would probably just leave this as-is given that 1) borg seems to be fine with that 2) the current `--stdin` procedure works like that as well and 3) users can overwrite/unset variables as you have shown in your last snippet anyway.

2023-04-03 12:15 UTC, Enrico204 commented
I am testing your branch for some real world backup in my personal/lab. For now, everything is working as expected :-)

2023-04-07 14:48 UTC, MichaelEischer requested changes
I'm in favor of adding a `--stdin-from-command` option (or maybe `--content-from-command`). Implementation-wise, it shouldn't be necessary to modify the archiver at all; the `fs.FS` interface should be generic enough to abstract away everything.

2023-04-07 14:48 UTC, MichaelEischer commented on cmd/restic/cmd_backup.go
> +		if len(args) > 0 && opts.StdinCommand == false {
please use `&& !opts.StdinCommand`

2023-04-07 14:48 UTC, MichaelEischer commented on internal/archiver/archiver.go
> +		errBytes, _ := io.ReadAll(opts.CommandStderr)
This will deadlock if a process writes too much data to stderr. Please handle stderr similar as in the rclone/sftp backend.

2023-04-07 14:48 UTC, MichaelEischer commented on cmd/restic/cmd_backup.go
> +		CommandStderr:  stderr,
There's no need to modify the archiver. Instead, the `Close() error` part of the `ReadCloser` of `fs.Reader` should wait for the command to exit and return an error if necessary.

2023-04-07 14:48 UTC, MichaelEischer commented on internal/archiver/archiver.go
> +			return nil, restic.ID{}, errors.New(string(errBytes))
`cmdErr` should not be dropped. It should at least be part of the returned error message.

2023-04-07 14:48 UTC, MichaelEischer commented on cmd/restic/cmd_backup.go
> +			command = exec.CommandContext(ctx, args[0], args[1:]...)
Please move as much of the code that sets up the stdinCommand as possible out of `runBackup`. The latter function is already _far_ too long.

2023-04-07 14:48 UTC, MichaelEischer commented on cmd/restic/cmd_backup.go
> +	f.BoolVar(&backupOptions.StdinCommand, "stdin-from-command", false, "execute command and store its stdout")
I wonder whether `--content-from-command` (as in Borg) would be a better name or not. stdin-from-command somewhat contradicts its own description...

2023-04-08 07:32 UTC, sebhoss commented
> Implementation-wise, it shouldn't be necessary to modify the archiver at all; the fs.FS interface should be generic enough to abstract away everything.

Ok thanks for the pointer - that was exactly what I was looking for! So the idea here would be to :

1. create an implementation of `fs.FS` that handles command execution and related errors 
2. refactor the code in `runBackup` to create an instance of that implementation 
3. pass it in as the `targetFS` to the existing archiver methods

Is that correct? Should that `fs.FS` implementation live in the same `fs` package? Is [this](https://github.com/restic/restic/blob/master/internal/backend/rclone/backend.go#L43-L61) and [that](https://github.com/restic/restic/blob/master/internal/backend/sftp/sftp.go#L60-L70) how you would like to handle stderr output?

2023-04-14 21:17 UTC, MichaelEischer commented
> Ok thanks for the pointer - that was exactly what I was looking for! So the idea here would be to :
> 
>     1. create an implementation of `fs.FS` that handles command execution and related errors

Judging from https://github.com/restic/restic/pull/4254/files#diff-30d8672eafa9c0585766b6f437530377563cd1aac5606674c366f3ede4abea9eR618 an `fs.FS` implementation that wraps `fs.Reader` might work here.

>     2. refactor the code in `runBackup` to create an instance of that implementation
> 
>     3. pass it in as the `targetFS` to the existing archiver methods

Yes.

> Should that `fs.FS` implementation live in the same `fs` package? Is [this](https://github.com/restic/restic/blob/master/internal/backend/rclone/backend.go#L43-L61) and [that](https://github.com/restic/restic/blob/master/internal/backend/sftp/sftp.go#L60-L70) how you would like to handle stderr output?

The `fs` package is probably the best place for now. And yep, I was referring to the goroutine that reads from stderr of the subprocess.

2023-07-09 18:37 UTC, MichaelEischer commented
@sebhoss Are you still interested in working on this PR?

2023-07-10 12:37 UTC, Enrico204 commented
I can take over this PR. I am using the code here on a daily basis at home for backups, and I will be happy to have it merged :-)

However, don't I think I will be able to continue in this PR as the branch is from @sebhoss's repo, so maybe I can fork & create a new pull request with the same code, and then apply the suggestions from @MichaelEischer. What do you think?

2023-07-14 20:19 UTC, MichaelEischer commented
@Enrico204 Sounds good. Go ahead and create a new PR, I'll close the old PR afterwards.

2023-07-22 21:55 UTC, MichaelEischer commented
Superseded by #4410.

2023-07-22 21:55 UTC, closed without merging