Issue#2468
restic/restic pull request #4387
Opened 2023-06-27 15:48 UTC by arjunajesh

What does this PR change? What problem does it solve?
-----------------------------------------------------
Restic backups on azure only worked for storages on the global domain `core.windows.net`. This meant that backups to other domains such as Azure China (`core.chinacloudapi.cn') were not supported. Restic now allows overriding the global domain using the environment variable `AZURE_DOMAIN'.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Closes #2468 

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2023-07-01 16:36 UTC, MichaelEischer requested changes
Thanks for working on this issue! The PR currently still needs a bit of polishing, see the comments below. The comments also explain where to add documentation. For testing it should be sufficient to manually verify that the parameter works as intended and does not change the current behavior is no other azure endpoint is specified.

2023-07-01 16:36 UTC, MichaelEischer commented on internal/backend/azure/config.go
> +	Domain      string
In the azure documentation, the parameter is called (storage) endpoint suffix.
https://learn.microsoft.com/en-us/azure/storage/common/storage-powershell-independent-clouds#get-endpoint-using-get-azenvironment

What about renaming it to `EndpointSuffix` and adjusting the environment variable name accordingly?

2023-07-01 16:36 UTC, MichaelEischer commented on internal/backend/azure/azure.go
> +	fmt.Println(url)
Please remove the debug statement.

2023-07-01 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_backup.go
> +		fmt.Println("loading index now")
Please revert the changes in this file.

2023-07-01 16:36 UTC, MichaelEischer commented on changelog/unreleased/issue-2468
> +https://github.com/restic/restic/issues/2468
Please add a link to this PR.

2023-07-01 16:36 UTC, MichaelEischer commented on changelog/unreleased/issue-2468
> +Issue: Compatibility with non global azure domain
The prefix must be `Enhancement:`. I'd also reword the summary to `Enhancement: Add support for non-global Azure clouds`.

2023-07-01 16:36 UTC, MichaelEischer commented on internal/backend/azure/config.go
> +		cfg.Domain = os.Getenv("AZURE_DOMAIN")
The environment variable should be included in the list in `doc/040_backup.rst`.

2023-07-01 16:36 UTC, MichaelEischer commented on changelog/unreleased/issue-2468
> +Restic backups on azure only worked for storages on the global domain `core.windows.net`. This meant that backups to other domains such as Azure China (`core.chinacloudapi.cn') were not supported. Re
A similar description is also necessary in the Azure setup instructions in `doc/030_preparing_a_new_repo.rst`.

2023-07-01 16:36 UTC, MichaelEischer commented on .DS_Store
Please remove the .DS_Store files from the PR.

2023-07-02 04:10 UTC, arjunajesh commented
I have fixed everything you mentioned. Thanks for the help!

2023-07-07 21:11 UTC, MichaelEischer approved these changes
LGTM. Thanks!

I've squash the commits and added a few further tweaks.

2023-07-07 21:17 UTC, merged