backend/sftp: Add sftp.args option
restic/restic pull request #4519
Opened 2023-10-18 01:27 UTC by adamantike

What does this PR change? What problem does it solve?
-----------------------------------------------------

Allow setting custom arguments for the `sftp` backend, by using the `sftp.args` option. This is similar to the approach already implemented in the `rclone` backend, to support new arguments without requiring future code changes for each different SSH argument.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Closes #4241

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2023-10-19 09:25 UTC, quite approved these changes

2023-10-19 20:04 UTC, MichaelEischer requested changes

2023-10-19 20:04 UTC, MichaelEischer commented on internal/backend/sftp/sftp.go
> +	if cfg.Args != "" {
Please extend `if cfg.Command != "" {` to return an error if both the command and args parameters are set.

2023-10-20 00:21 UTC, adamantike commented on doc/030_preparing_a_new_repo.rst
> + * ``-o sftp.connections`` specifies the number of parallel connections to use, the default value is ``5``
Good call!

2023-10-21 17:29 UTC, MichaelEischer approved these changes
LGTM.

I've rebased and squashed the commits and added a negative test case to test that args and command cannot be set at the same time.

2023-10-21 17:49 UTC, merged