retry: Do not retry Load() if file does not exist
restic/restic pull request #4520
Opened 2023-10-18 18:57 UTC by awannabeengineer

What does this PR change? What problem does it solve?
-----------------------------------------------------
It changes the behavior of retry for Load by not retrying if file does not exist.
This will prevent retrying Load in a situation where no matter the number of retries, Load will not succeed. 
ex: loading the lock file placed in repo by another host that has since been deleted.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
fixes #4515

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2023-10-19 19:49 UTC, MichaelEischer requested changes
I vaguely seem to remember that some (broken) storage services can sometimes return a "not found" error even for files that actually exist. But I didn't find relevant issues during a quick search. So, I guess we can give this PR a try. (Especially, as we'll definitely need this change to properly implement #1141)

For lock files it's somewhat important to retry a few times if files disappear in the meantime (https://github.com/restic/restic/issues/1523#issuecomment-1221352459). But apparently, I've already implemented that as part of https://github.com/restic/restic/blob/495982232cf1af184eac0a97871ef8161e8708ee/internal/restic/lock.go#L166 .
However, it might be a good idea to modify `ForAllLocks` to skip loading a lock file once it has successfully loaded it once. Although, we can defer that to a separate PR.


Regarding this PR, it definitely needs a changelog entry, see the link in the PR template. Please use `Change` as categorization.

2023-10-19 19:49 UTC, MichaelEischer commented on internal/backend/retry/backend_retry.go
> +	err = be.retry(ctx, fmt.Sprintf("Load(%v, %v, %v)", h, length, offset),
Please keep the `return` statement on this line.

2023-10-19 19:49 UTC, MichaelEischer commented on internal/backend/retry/backend_retry.go
> +			innerError = be.Backend.Load(ctx, h, length, offset, consumer)
`err := ...` would also work here as it declares a new variable that shadows the outer `err`.

2023-10-22 19:13 UTC, awannabeengineer commented
Thanks for the feedback! I amended the commit with your suggested changes and added a changelog entry. If separate commits are preferred, please let me know.

2023-10-25 20:36 UTC, MichaelEischer approved these changes
LGTM. Thanks!

2023-10-25 20:52 UTC, merged