Fix dangerous forget-all operation which drops all snapshots
restic/restic pull request #4568
Opened 2023-11-18 23:12 UTC by schoettl

What does this PR change? What problem does it solve?
-----------------------------------------------------

```
restic forget --keep-tag=SomeUnusedTag --dry-run
```

This command would drop all snapshots. This is very dangerous and probably unwanted.

A suggested fix (see forum) is to only allow `--keep-tag` together with other `--keep-*` options.

While working on this, I noticed that another if case seem to have no effect, see comment in diff.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

See also https://forum.restic.net/t/delete-all-snapshots-in-one-command-is-this-feature-intentional/6923/3

Checklist
---------

- [ ] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [ ] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I have run `gofmt` on the code in all commits.
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2023-11-19 19:18 UTC, arberg commented
Hi Jakob, 

Thank you for working on this. I'm the original issue OP. I've never looked at restic code before, but I have a few comments, though of cause they may be misplaced, as I have only looked at this tiny part of the code.

1) lines 148-152 looks like it contains a bug (which would be a prevous bug), namely that it is missing withinWeekly in the check, both the old and your new copy. Probably called `d.Weekly`. Also there's the `--keep-within duration`, though it possible the duration type cannot be negative.

2) line 159, the ending if, should also allow the `--keep-within duration` which isn't matched by your two new allKeep*Undefined. Or add keep-within to the `allKeepWithinXUndefined`

3) It might make sense to keep the initial if-check even if handled elsewhere as well, or maybe convert it into some kind of assert. That makes this method self-contained in its requirement of valid options. I mean just by reading this small method, one can verify that regardless of what goes on elsewhere in the sourcecode, this method does not allow --keep-* with negative values or with missing positives. 

Best Alex

2023-11-19 21:48 UTC, schoettl commented
Hey Alex, thanks for the great feedback and the catched bugs! :-)

I'll fix that in the next commits on this PR. But today it's too late.

I'm happy to get more feedback later on! It's also my first time contributing to restic and first time using the go language ^^

In case you're not familiar to github PRs, note that you can also add comments to the code in the "Files changed" tab.

2023-11-22 21:56 UTC, schoettl commented on cmd/restic/cmd_forget.go
> +		if d.Hours != 0 || d.Days != 0 || d.Months != 0 || d.Years != 0 {
@arberg regarding 1.: these lines should be correct. `d` is a `Duration` which is defined as
```
type Duration struct {
	Hours, Days, Months, Years int
}
```
The duration specification has no week.

2023-11-22 21:58 UTC, schoettl commented on cmd/restic/cmd_forget.go
> +		if d.Hours != 0 || d.Days != 0 || d.Months != 0 || d.Years != 0 {
... and each `opts.Within*` option has such a duration specification as argument. That's my understanding.

2023-11-22 22:03 UTC, schoettl commented on cmd/restic/cmd_forget.go
> +	if len(opts.KeepTags) > 0 && allKeepXUndefined && allKeepWithinXUndefined {
Regarding 2.: Why do you think it doesn't cover `--keep-within`? It should be covered by `allKeepWithinXUndefined` which takes `opts.Within` into account.
```
	f.VarP(&forgetOptions.Within, "keep-within", "", "keep snapshots that are newer than `duration` (eg. 1y5m7d2h) relative to the latest snapshot")
```
Should be fine, right?

2023-11-22 22:25 UTC, schoettl commented
I should try to add some tests in `cmd_forget_*test.og`...

2023-11-25 17:13 UTC, schoettl commented on cmd/restic/cmd_forget_test.go
> +		{ForgetOptions{KeepTags: []restic.TagList{[]string{"tag1"}}}, keepTagsAloneMsg},
Maybe the TagLists can be created in a more concise way? I don't know go lang.

2023-12-25 17:53 UTC, schoettl commented
Happy Christmas! May I just ping on this PR? Maybe someone has time for review over the holidays :)

2024-04-03 20:01 UTC, MichaelEischer requested changes
Enforcing that `--keep-tag` is always used together with another keep option feels wrong. In particular, it will lead unwanted side effects if the snapshots with the specified tags are not the latest snapshots in the snapshot group. Then both the latest snapshot and the tagged snapshots in the snapshot group would be kept, which breaks the expected semantics.

I'd like to propose a different approach:
- Fix the current behavior by adding a check that `forget` refuses to work, if any snapshot group would end up with zero snapshots. This check would necessarily have to happen at runtime of the command, and cannot be checked before hand.
- Add an `--unsafe-allow-remove-all` option for the `forget` command. This will disable the above check.
- To prevent the worst cases of fat fingering, `--unsafe-allow-remove-all` must refuse to work unless a host/path/tag filter is specified or any other `--keep-*` option. This adds a new feature: users can then delete all snapshots from a specific host using e.g. `restic forget --host old-host --unsafe-allow-remove-all`.

Are you still interested in adapting and finishing this PR or should I take over?

2024-04-03 20:42 UTC, schoettl commented
Oh, that sounds like a more complicated fix. I'd be happy if you take over, I'm afraid I don't have the expertise and time, currently.

2024-04-07 17:10 UTC, arberg commented
Michael I also like that option, and as I can recall from the forum, some would indeed appreciate that delete-all option. I think its fine with the '--unsafe-allow-remove-all', though adding the extra requirement of path/host/tag also sounds good. 

I also won't have time at the moment and have yet evolved my go-mastery.

2024-04-15 20:28 UTC, MichaelEischer commented
I've opened https://github.com/restic/restic/pull/4764 as a replacement for this PR. Different from my previous suggestion that PR currently always forbids the complete deletion of a whole snapshot group if any `--keep-*` policy was specified. This means that `forget --keep-tag invalid` will always result in an error, even if `--unsafe-allow-remove-all` was specified.

2024-04-15 20:28 UTC, closed without merging