Added json logging for check.
restic/restic pull request #4581
Opened 2023-12-05 05:53 UTC by perjahn

What does this PR change? What problem does it solve?
-----------------------------------------------------

Adding json logging to the check command, in a similar fashion how the init command outputs json.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

No

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

2023-12-05 14:12 UTC, perjahn commented
How do I update the manual at readthedocs.io?

2023-12-24 11:13 UTC, MichaelEischer requested changes
Sorry to be blunt. The PR completely ignores all error messages (see all `Printf` statements). As a consequence the JSON output would break once the `check` command actually detects an error, thus making the current changes pointless. This is worse than the current state of no JSON output at all.

Thus either convert everything (we can discuss how to handle stderr) or drop the PR.

2023-12-24 11:13 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +			bar := newProgressMax(!gopts.Quiet, 0, "snapshots")
With this change, `chkr.Structure` uses the wrong instance of the `bar` variable.

2023-12-24 11:13 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +			ID:          repo.Config().ID,
The `ID` and `Repository` URL aren't really relevant here and thus should be removed.

2023-12-29 10:38 UTC, darkdragon-001 commented
Thanks for working on this! I think a single summary output in the end might be enough for many use cases (including mine of running restic from a script). Although one should reliably receive (at least) one json message (in both success and failure cases).

2023-12-29 15:06 UTC, MichaelEischer commented
> I think a single summary output in the end might be enough for many use cases (including mine of running restic from a script).

Its far simpler to just inspect the exit code of the `check` command. If it is `0` then everything is fine, otherwise there's some problem. That's exactly the same information currently provided by the JSON output.

2024-01-20 10:22 UTC, MichaelEischer commented
Closing as this PR needs a full rework anyways, feel free to open a new one if you're interested in addressing the review feedback.

2024-01-20 10:22 UTC, closed without merging