Fix: Stop archiving metadata
restic/restic pull request #4584
Opened 2023-12-05 18:31 UTC by elkemper

What does this PR change? What problem does it solve?
-----------------------------------------------------
It fixes issue when you upload snapshot to S3 Glacier, and metadata isn't available from any machine without cache.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Closes #4583

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2023-12-24 11:19 UTC, MichaelEischer requested changes
I don't understand how this PR is supposed to work. The directory metadata of a snapshot is also stored in pack files and consequently there's no chance for the backend to distinguish data and metadata.

2023-12-24 15:05 UTC, elkemper commented
Hey @MichaelEischer, thanks for picking the PR!

Here's my line of thought when I investigated this issue.
I figured, that because of everything in the repository - is _just files_ then there should be one function, the sole responsibility of which is - save **any** file to the backend. Also, searching for the `StorageClass` argument, i decided, that `Save` function is what i'm looking for. And looking through the call queue - it appeared the last stand of Restic before handling the operation to the Minio dependency. 
Knowing that - I looked to the arguments of the function and understood that `h Handle` could help me to determine what is being saved right now. And thanks to all of you, it had a parameter Type, which corresponds to the enum with all object types. So I thought that is safe to assume, that I can filter for the `PackFile`.

Well, after your question, I've done some more digging and went up on call stack and found that it used in all `Flush` functions - for data and for indexes. And handlers with datatype are passed down to it. 

Also, as a proof of work - here's bunch of screenshots of S3 when I tried this code. (saving just one small text file)
Config (and keys) are stored in `Standard` because when I `init`-ed the repo I didn't use StorageClass option (not sure even will it have any effect thou). And you can mention the date of files created.
The Snapshots, Index and Data are created few minutes later, and you can see that they have different Storage Classes
<details> 
<summary>Screenshots</summary>
<img width="1943" alt="image" src="https://github.com/restic/restic/assets/21986537/7a03e497-db2e-4d36-8169-17a05c346e3c">
<img width="1952" alt="image" src="https://github.com/restic/restic/assets/21986537/4d20f9e2-4113-4bb4-8d85-2320ccd9d3d4"><img width="1936" alt="image" src="https://github.com/restic/restic/assets/21986537/c56f5673-4ce4-48bc-a0ec-e4b90afa5c13">
<img width="1936" alt="image" src="https://github.com/restic/restic/assets/21986537/7b9a83e2-5e9a-40c1-b280-f8ab39505da3">
<img width="1951" alt="image" src="https://github.com/restic/restic/assets/21986537/19f6e605-abc1-4791-88c6-ce46e50480ca">
<img width="1961" alt="image" src="https://github.com/restic/restic/assets/21986537/7d4d899d-54c1-47f0-b798-c07c84a1dd78">
</details>

And in opposite, here's my first attempts of saving to the Glacier, when I didn't know about issue.
<details>
<summary>Screenshots of my tries and errors</summary>
<img width="1932" alt="image" src="https://github.com/restic/restic/assets/21986537/db1b3acd-b713-4a0e-8b61-42bcbfe079e7">
<img width="1957" alt="image" src="https://github.com/restic/restic/assets/21986537/60870547-2066-4cb6-a7d6-577a386445e6">
<img width="1922" alt="image" src="https://github.com/restic/restic/assets/21986537/5ca56183-a20a-4eb3-8b24-14aa5ae47eb6">
</details>

Hope this helps.

2024-01-06 21:42 UTC, MichaelEischer commented
A pack file can contain either tree or data blobs. To allow a second host without a prefilled cache to use the repository for backups, the second host must also be able to retrieve the tree blobs. However, both tree and data blobs are stored in pack files. To see what I mean just try the following (while using your PR):

```
restic -o s3.storage-class=GLACIER backup some-small-folder
restic -o s3.storage-class=GLACIER backup --no-cache some-small-folder
```
The second backup run will use the snapshot from the first backup run as its parent snapshot. And it will try to download the corresponding tree blobs, which will fail.

For that to work a pack file must also not be archived if `h.IsMetadata` in `h backend.Handle` is true.

I'm not entirely sure how you intend the `restore` procedure to work. Do I have to retrieve the whole backup archive?

2024-01-06 21:46 UTC, MichaelEischer commented on internal/backend/s3/s3.go
> +func (be *Backend) PassStorageClass(h backend.Handle) bool {
that method name should start with a lower case letter and probably be called `useStorageClass`

2024-01-06 21:46 UTC, MichaelEischer commented on internal/backend/s3/s3.go
> +	var res bool = h.Type == backend.PackFile || notArchive
I'd prefer something like
```
isDataFile := h.Type == backend.PackFile && !h.IsMetadata
return isDataFile || notArchiveClass
```

2024-01-06 21:51 UTC, MichaelEischer commented on changelog/unreleased/issue-4583
> +https://github.com/restic/restic/issues/3202
This PR does not add full blown support for archive storage. As such it should be clear after reading that there is _no_ official support for cold storages.

2024-01-13 17:43 UTC, elkemper commented
Thanks for the comments.
You are right @MichaelEischer, I didn't know this about packfiles. I tried to add to the test backup made with my first build and it couldn't get snapshot metadata.
After accepting your snippets I rechecked updating the backup as well as forget and prune and everything worked as expected.

As of how I'm expecting to use this backups - to make it the "1" from "3-2-1" backup strategy. I want a cheap storage for valuable media only in case of failures of local copies and raid setup. So yeah, if I will restore it, it will be a full restore.

2024-01-20 10:19 UTC, MichaelEischer approved these changes
LGTM.

I've reworded the changelog and made a few additional minor cleanups.

2024-01-20 10:36 UTC, merged