Properly report the ID of newly added keys
restic/restic pull request #4657
Opened 2024-01-25 09:42 UTC by ls-initiatives

What does this PR change? What problem does it solve?
-----------------------------------------------------

Other commands like key list and key remove show the key's ID.

Showing the ID here lets users easily reuse the ID as a key hint for subsequent commands. In particular, a key hint is needed when the repository has many keys - otherwise opening the repository may fail with "Fatal: maximum number of keys reached" even when a proper password is provided.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Fixes #4656

- [X] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [ ] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I have run `gofmt` on the code in all commits.
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2024-01-26 21:42 UTC, MichaelEischer requested changes
The ideal solution would be to add JSON support to `key add`. But I agree that the current output is not useful. So I'm fine with changing it, I just just have a few small remarks as commented below.

2024-01-26 21:42 UTC, MichaelEischer commented on cmd/restic/cmd_key.go
> +	Verbosef("saved new key as %s\n", id.ID())
Let's change the message a bit: `saved new key with ID %s`

2024-01-26 21:42 UTC, MichaelEischer commented on changelog/unreleased/issue-4656
> +When adding a key to a repository, we had no "easy" way to know the new key's ID.
Please shorten this to something similar to the following:
```
`restic key add` now reports the ID of a newly added key. This simplifies
selecting a specific key using the `--key-hint keyID` option.
```

2024-01-29 09:18 UTC, ls-initiatives commented
Updates following your suggestions, thanks.
I agree that JSON output would be nice to have, though I can't write the patch for it. I'll file an issue about that if you want.

2024-01-31 20:58 UTC, MichaelEischer commented
> I agree that JSON output would be nice to have, though I can't write the patch for it. I'll file an issue about that if you want.

That would be great.

2024-01-31 20:58 UTC, MichaelEischer approved these changes
LGTM.

2024-01-31 21:06 UTC, merged