Move key add, list, remove and passwd as separate sub-commands
restic/restic pull request #4685
Opened 2024-02-04 14:46 UTC by konidev20

What does this PR change? What problem does it solve?
-----------------------------------------------------
Restic previously used command line args to figure out the command to be executed for the `key` command. The documentation of the key command was limited. 

@MichaelEischer requested the key command to be split into their own sub-commands like how the `repair` command is structured.

This PR has split the `key` command into their respective sub-commands using spf13/cobra's sub-command feature. 

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Closes #4676 

> We should split the key command into multiple subcommands, similiar to the repair command.
> 
> "add" create a new key. "passwd" replaces the current key with a new one using the new password.

Checklist
---------

- [ ] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [ ] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I have run `gofmt` on the code in all commits.
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2024-02-05 19:33 UTC, MichaelEischer requested changes
Thanks for working on this! I like the change in general, but I found a few problems that were introduced while refactoring the code.

2024-02-05 19:33 UTC, MichaelEischer commented on cmd/restic/cmd_key_add.go
> +type NewPasswordOptions struct {
There is no longer a reason to keep this as a separate struct. Please inline it into `AddKeyOptions`.

2024-02-05 19:33 UTC, MichaelEischer commented on cmd/restic/cmd_key_add.go
> +func runKeyAdd(ctx context.Context, gopts GlobalOptions, opts AddKeyOptions) error {
now that we can do so in a clean way, please return an error if any `args` are passed to `key add`. Please also make the corresponding change to the other commands.

2024-02-05 19:33 UTC, MichaelEischer commented on cmd/restic/cmd_key_remove.go
> +	id, err := restic.Find(ctx, repo, restic.KeyFile, args[0])
The `restic.Find` call should be part of `deleteKey`.

2024-02-05 19:33 UTC, MichaelEischer commented on cmd/restic/cmd_key_remove.go
> +	id, err := restic.Find(ctx, repo, restic.KeyFile, args[0])
`len(args)` must equal `1` otherwise this could crash.

2024-02-05 20:23 UTC, konidev20 commented on cmd/restic/cmd_key_integration_test.go
> +}
@MichaelEischer I've added this new integration test to check for the invalid parameters for the sub-commands.

2024-02-08 19:56 UTC, MichaelEischer approved these changes
LGTM.

I've fixed the integration test. `key list` returned an error for the wrong reason.

2024-02-08 20:06 UTC, merged