Add support for specifying --host via environment variable
restic/restic pull request #4734
Opened 2024-03-18 20:22 UTC by maouw

What does this PR change? What problem does it solve?
-----------------------------------------------------

This PR adds the ability to set the hostname for most commands that accept the `--host` flag via the `RESTIC_HOST` environment variable. This allows the user to set the hostname once and not have to specify it for every command. Commands that accept `--host` but do not work on snapshots (e.g. `restic key ...`) are not affected by this change. The `--host` flag is still accepted and takes precedence over the `RESTIC_HOST` environment variable.

The changes are in `cmd_backup.go` for the `backup` command and `find.go` for commands that use the `restic.SnapshotFilter` options.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Closees #4733

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [x]  There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2024-03-18 20:24 UTC, maouw commented
I have a question to the maintainers -- where and/or how would you suggest putting the proper tests for this feature? Most of the tests related to this area seem to circumvent option processing, so I can't find a good example to follow. I am a golang beginner.

2024-03-29 21:52 UTC, MichaelEischer requested changes
Thanks for the PR! I only have a few comments, see below.

The best way for testing is probably to use something like the following. That simply creates a new flagSet, configures it, then parses a test string and verifies the outcome:
```
set := pflag.NewFlagSet("test", pflag.PanicOnError)
flt := &restic.SnapshotFilter{}
initMultiSnapshotFilter(set, flt, false)
err := set.Parse([]string{"--host", "abc"})
rtest.OK(t, err)
// assert on flt.Hosts
```

2024-03-29 21:52 UTC, MichaelEischer commented on changelog/unreleased/issue-4733
> +https://github.com/restic/restic/issues/4733
Please also add a link to this PR.

2024-03-29 21:52 UTC, MichaelEischer commented on cmd/restic/find.go
> +	if len(filt.Hosts) == 0 {
Wrapping the following code in the if is unnecessary. The cli flag configuration and the cli parsing are two separate steps. At this point, `filt.Hosts` is always empty.

It does still work, as cobra internally tracks whether it has already applied an option or whether `filt.Hosts` still has its default value. So, just remove the `if len(filt.Hosts) == 0 {` check. The same also applies for `initSingleSnapshotFilter`.

2024-04-24 19:53 UTC, MichaelEischer approved these changes
LGTM. I've applied my suggestions and added a short test.

2024-04-24 20:07 UTC, merged

2024-04-30 20:48 UTC, maouw commented
Thank you for taking care of the test. Very happy to see this coming through, it will be a great help.

2024-08-12 14:38 UTC, ahmgithubahm commented
Hi.  On the release BLOG [1], there is this line:

Support for specifying hostname via [environment variable](https://restic.readthedocs.io/en/stable/040_backup.html#environment-variables) RESTIC_HOST.

It links to the env var docs, but the docs don't appear to mention RESTIC_HOST.

thanks!

[1] https://restic.net/blog/2024-07-26/restic-0.17.0-released/