Return different exit code if repo is locked or does not exist
restic/restic pull request #4884
Opened 2024-06-30 17:14 UTC by MichaelEischer

What does this PR change? What problem does it solve?
-----------------------------------------------------
Return exit code 4 if a repository cannot be locked and exit code 5 if the repository does not exist. The existence check relies on the presence of the `config` files. Other errors like an invalid password still result in exit code 1.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Address two use cases from https://github.com/restic/restic/issues/956 .

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2024-07-10 19:50 UTC, MichaelEischer commented
I've changed the exit codes to 10 and 11. With a bit of luck this might allow establishing at least a minimal kind of ordering in the exit codes.

2024-07-10 19:55 UTC, MichaelEischer reviewed
LGTM.

2024-07-10 19:56 UTC, rawtaz requested changes, later dismissed

2024-07-10 19:56 UTC, rawtaz commented on doc/075_scripting.rst
> +perhaps to prevent your script from trying to initializing a repository multiple
```suggestion
perhaps to prevent your script from trying to initialize a repository multiple
```

2024-07-10 20:13 UTC, MichaelEischer commented on doc/075_scripting.rst
> +perhaps to prevent your script from trying to initializing a repository multiple
fixed. thanks!

2024-07-12 19:05 UTC, MichaelEischer reviewed
LGTM.

2024-07-12 19:05 UTC, merged