Dump multiple paths
restic/restic pull request #5062
Opened 2024-09-15 17:02 UTC by phillipp

What does this PR change? What problem does it solve?
-----------------------------------------------------

Before this change, `dump` accepted one path to dump, now multiple paths are accepted.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

#4173

Checklist
---------

- [X] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [ ] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I have run `gofmt` on the code in all commits.
- [ ] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

2024-09-15 17:18 UTC, phillipp commented
The tests are not passing right now because the dumper does not need to allow passing an `io.Writer` anymore as this is not required, we could keep this around but idk, seems odd to me to pass a field as an argument.

2024-12-01 14:26 UTC, MichaelEischer requested changes
Sorry for the very late review.

I found a few conceptual issues which we have to sort out first:
- what should happen if a user passes `/file1` and `/file2` as paths? My expectation would be an archive containing both paths.
- an archive with a `/file` and `/dir` path should similarly store the file in the archive instead of writing it verbatim to the output.
- What should happen when dumping `/dir` and `/other/dir`? Mixing both directories as would happen now feels wrong. But also including the prefix in the path is also somewhat weird as we'd either have to break backwards compatibility or only add the prefix when there are multiple paths.

2024-12-01 14:26 UTC, MichaelEischer commented on cmd/restic/cmd_dump.go
> +func preparePathList(pathComponentsList []string) [][]string {
Please add a short description how this function works. It took me a while to reverse engineer the underlying idea: first all paths are stored in a pathSet in sanitized form. The filtered set then only contains paths, for which no prefix already exists in the pathSet. This ensures that the order in which paths are processed does not matter.

2024-12-01 14:26 UTC, MichaelEischer commented on cmd/restic/cmd_dump.go
> +					break out
a simple `break` after the switch statement has the same effect. Then `dumpedNodes` can also move out of the switch statement.

2024-12-01 14:26 UTC, MichaelEischer commented on cmd/restic/cmd_dump.go
> +			l := len(pathComponents)
`item` and `l` should only be calculated inside the `if` block

2024-12-01 14:26 UTC, MichaelEischer commented on cmd/restic/cmd_dump.go
> +					d.WriteNode(ctx, node)
This behaves incorrectly when a user specifies multiple file paths. `WriteNode` only dumps the file content without any metadata. Also a combination of a directory + file path results in a corrupted output.

2024-12-01 14:26 UTC, MichaelEischer commented on cmd/restic/cmd_dump.go
> +			return fmt.Errorf("path %q not found in snapshot", filepath.Join(prefix, item[0]))
Should use `path.Join`

2026-06-27 20:39 UTC, MichaelEischer commented
I'll close the PR for now as it needs larger changes before we could consider merging it. Feel free to open a new PR if you want to continue with the PR.

2026-06-27 20:39 UTC, closed without merging