forget: report count of deleted files correctly
restic/restic pull request #5179
Opened 2024-12-15 08:16 UTC by konidev20

What does this PR change? What problem does it solve?
-----------------------------------------------------
* fix the issue where the progress counter would be incorrectly updated even when the file deletion failed in append-only mode discussed in #5140 
* I moved the progress increment function to before the report function, which may absorb the error

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Closes #5140 #5140

Checklist
---------

- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I'm done! This pull request is ready for review.

2024-12-18 18:25 UTC, konidev20 commented
```
func ParallelRemove(ctx context.Context, repo RemoverUnpacked, fileList IDSet, fileType FileType, report func(id ID, err error) error, bar *progress.Counter) error {
```

Hey @MichaelEischer, 

I want to remove the dependence on `*progress.Counter` from here, I believe the report function can update the bar as well since it's a dependency injected from outside. 

This will allow restic internal methods to be tested independently of the progress reporting.

2025-01-26 15:51 UTC, MichaelEischer requested changes
The removal of the `bar.SetMax` call is a significant regression and not necessary as mentioned in the below comments.

> I want to remove the dependence on `*progress.Counter` from here, I believe the report function can update the bar as well since it's a dependency injected from outside.
> 
> This will allow restic internal methods to be tested independently of the progress reporting.

I don't understand the testing argument. In fact the test case no longer tests the behavior of `ParallelRemove` but rather of `ParallelRemove` + custom progress bar calls in `report` function. For consistent behavior, it feels more reasonable to have progress bar updates handled by `ParallelRemove`. I don't see a technical reason why that wouldn't work.

2025-01-26 15:51 UTC, MichaelEischer commented on internal/repository/prune.go
>  		printer.VV("removed %v/%v\n", fileType, id)
That log output is also wrong if the file deletion failed, but `ignoreError` is set.

2025-01-26 15:51 UTC, MichaelEischer commented on internal/restic/parallel.go
> -	bar.SetMax(uint64(len(fileList)))
Loosing the information about the total number of files that should be removed is a major problem in my opinion.

In fact, it's not necessary to remove the progress.Counter handling from ParallelRemove. The changed `report` functions are equivalent to the following change in `ParallelRemove`:
```go
err := repo.RemoveUnpacked(ctx, fileType, id)
if err != nil {
    bar.Add(1)
}
if report != nil {
    err = report(id, err)
}
```

2025-02-02 14:08 UTC, konidev20 commented
> I don't understand the testing argument. In fact the test case no longer tests the behavior of ParallelRemove but rather of ParallelRemove + custom progress bar calls in report function. For consistent behavior, it feels more reasonable to have progress bar updates handled by ParallelRemove. I don't see a technical reason why that wouldn't work.

I was thinking that the reporting and progress counters must be together. I can revert the change to the fix I had made earlier. 

Thanks for the review. I will think about this more before making any major changes.

2025-02-02 14:15 UTC, MichaelEischer commented
> I was thinking that the reporting and progress counters must be together. I can revert the change to the fix I had made earlier.

Yes, please revert the changes from https://github.com/restic/restic/pull/5179/commits/94ad25e8d35149bf0e690b48f7add71138f19547 . The implementation from https://github.com/restic/restic/pull/5179/commits/5e64578b15e15e5e069eb8754acc7e34db385365 is what I had in mind. The added tests should still work with minor modifications.

I don't think it's worth the trouble to introduce other abstractions, let's just keep using the progress counter.

2025-02-02 14:49 UTC, konidev20 commented
> The added tests should still work with minor modifications. 

I have made the modifications, let me know if I have missed something.

2025-02-02 16:18 UTC, MichaelEischer approved these changes
LGTM. Thanks!

Have you seen https://github.com/restic/restic/issues/5140#issuecomment-2629144531 ? Do you want to address that in this PR or should we consider this a separate issue?

2025-02-02 16:30 UTC, konidev20 commented
We can address the concerns on a separate PR after discussion.

2025-02-02 19:14 UTC, merged