issue 4179: create ability to sort output of restic ls -l by name, size, atime, ctime, mtime, time(=mtime)
restic/restic pull request #5182
Opened 2024-12-16 14:42 UTC by wplapper

Enhancement: create ability to sort output of restic ls -l by name, size, atime, ctime, mtime, time(=mtime), X(=extension), extension

https://github.com/restic/restic/issues/4179

What does this PR change? What problem does it solve?
-----------------------------------------------------
Ability to sort output of restic ls -l by name, size, atime, ctime, mtime, time(=mtime)

Add 2 local parameters to sort command: --sort and --reverse, so that the output can be sorted by one of the above named possibilities.
Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

https://github.com/restic/restic/issues/4179
Checklist
---------

- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I'm done! This pull request is ready for review.

2025-01-26 16:36 UTC, MichaelEischer requested changes
Thanks for working on this feature and the other PRs (I'll slowly dig through those).

I've left a few comments below. Please also add a basic test. You can look at `TestRunLsNcdu` for inspiration.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +	flags.BoolVarP(&lsOptions.Reverse, "reverse", "R", false, "reverse sorted output")
`reverse` only works in combination with `--sort`. Return an error if `--sort` wasn't specified.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +	outputSort := true
The data format of restic guarantees that the output is implicitly sorted by name. There's no need to store all output in memory in that case.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +	flags.StringVarP(&lsOptions.Sort, "sort", "s", "name", "sort output by [name|size|time(=mtime)|atime|ctime|mtime|X(=extension)|extension]")
When invalid values are passed to `--sort`, the `ls` command must fail with an error. Take a look at `CompressionMode` in `internal/repository/repository.go` how a clean solution would look like.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +			for ix, item := range collector {
Is there a reason for using `ix` instead of the standard `i`?

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +				return cmp.Or(
cmp.Or is not yet available in Go 1.21 (the current minimum Go version supported by restic). But we could just as well bump the minimum required go version to 1.22.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +			type ToSortExt struct {
Using a `map[string]string` that maps the nodepath to the file extension would allow getting rid of these back and forth copies.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +	if outputSort {
Please extract the sorted output code into a helper function. `runLs` is already far, far too long.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +		if opts.Sort == "size" {
Use `switch opts.Sort {` here.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +	flags.StringVarP(&lsOptions.Sort, "sort", "s", "name", "sort output by [name|size|time(=mtime)|atime|ctime|mtime|X(=extension)|extension]")
Where does `X` originate from? The other values largely match those offered by the unix `ls` command (`none, size, time, version, extension, width`). But `X` isn't part of that list.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +	flags.BoolVarP(&lsOptions.Reverse, "reverse", "R", false, "reverse sorted output")
`-R` means `--recursive` for the `ls` command. So I'm wondering whether it makes sense to have a `-R` with a rather different meaning here.

2025-01-26 16:36 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +sort specifiers '[name|size|time|atime|ctime|mtime]'.
`extension` is missing from the description.

2025-01-26 16:40 UTC, MichaelEischer commented on cmd/restic/cmd_ls.go
> +	flags.StringVarP(&lsOptions.Sort, "sort", "s", "name", "sort output by [name|size|time(=mtime)|atime|ctime|mtime|X(=extension)|extension]")
The general idea with parameter validation is that unsupported/invalid parameters must result in an error. That will allow us to support new values in the future without breaking existing behavior.

As a random example: For example `--sort mode` would right now sort by name as it isn't supported. But when we for some reason want to support `mode` in the future, then that would change the behavior for everyone who's for some reason already using `--sort mode`. By just returning an error when an invalid value was specified, we can ensure that nobody uses those invalid values and therefore are able to redefine the without problems in the future.

2025-01-26 22:36 UTC, wplapper commented on changelog/unreleased/issue-4179
> +ls: create ability to sort output of restic ls -l by one of the following list
done

2025-01-26 22:36 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +	flags.StringVarP(&lsOptions.Sort, "sort", "s", "name", "sort output by [name|size|time(=mtime)|atime|ctime|mtime|X(=extension)|extension]")
done

2025-01-26 22:37 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +	flags.BoolVarP(&lsOptions.Reverse, "reverse", "R", false, "reverse sorted output")
fixed

2025-01-26 22:37 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +	outputSort := true
check for name removed

2025-01-26 22:38 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +	flags.StringVarP(&lsOptions.Sort, "sort", "s", "name", "sort output by [name|size|time(=mtime)|atime|ctime|mtime|X(=extension)|extension]")
implemented

2025-01-26 22:38 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +	if outputSort {
done

2025-01-26 22:38 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +		if opts.Sort == "size" {
yep, done

2025-01-26 22:38 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +	flags.StringVarP(&lsOptions.Sort, "sort", "s", "name", "sort output by [name|size|time(=mtime)|atime|ctime|mtime|X(=extension)|extension]")
X removed

2025-01-26 22:40 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +	flags.BoolVarP(&lsOptions.Reverse, "reverse", "R", false, "reverse sorted output")
removed short option -R

2025-01-26 22:41 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +sort specifiers '[name|size|time|atime|ctime|mtime]'.
extension has been added.

2025-01-27 08:09 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +				return cmp.Or(
I prefer to be able to use SortStableFunc over Sort, since it is generic and also allows to use cmp.Or().

2025-01-27 08:10 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +			type ToSortExt struct {
done. Got rid of the copy-in copy-out.

2025-01-27 08:28 UTC, wplapper commented
Regards testing: you have touched a sore point. Is there anywhere a document or a set of documents which describes the restic testing machinery? I am looking at TestRunLsNcdu and can see that it runs a backup to repo `env.testdata+"/0"`. from ".". What is `env.testdata+"/0"` and where does "." point to? Eventually the test function runs a couple of `runLs(context.TODO(), opts, gopts, args)` from the backup just generated.

I would like to create a test scenario where I backup 2 or 3 files with different names, extension and sizes. Then I can sort by name, time, size and extension and compare against the expected output.

Any pointers? Thanks!

2025-01-28 07:27 UTC, wplapper commented on changelog/unreleased/issue-4179
> +ls: create ability to sort output of restic ls -l by one of the following list
4 basic tests added. I had to expand `backup-data` to get some useful filenames with extensions. Ran all tests with the modified `backup-data` structure.

2025-01-29 05:03 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +			for ix, item := range collector {
code not longer there.

2025-02-01 18:16 UTC, MichaelEischer requested changes
I have a few more nits. Can you add a short note about the new sort mode to `doc/045_working_with_repos.rst`?

I'll refactor the code a bit after merging, but it's harder to explain what I have in mind than making those changes.

2025-02-02 14:17 UTC, MichaelEischer commented
https://github.com/restic/restic/pull/5232 will bump the minimum go version to 1.22, this should fix the failing test in Go 1.21.

2025-02-02 17:30 UTC, wplapper commented on changelog/unreleased/issue-4179
> +Enhancement: add capability sort output by one of given options
done.

2025-02-02 17:31 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +func PrintSortedOutput(printer lsPrinter, opts LsOptions, sortMode SortMode, collector []ToSortOutput) {
done.

2025-02-02 17:32 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +type ToSortOutput struct {
done.

2025-02-02 17:49 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +type ToSortOutput struct {
done

2025-02-02 17:51 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +	if opts.Sort != "" {
removed the if cause.

2025-02-02 18:03 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +sort specifiers '(name|size|atime|ctime|mtime=time|extension)'.
I hope I changed it to be the same.

2025-02-02 21:33 UTC, wplapper commented on cmd/restic/cmd_ls.go
> +func PrintSortedOutput(printer lsPrinter, opts LsOptions, sortMode SortMode, collector []ToSortOutput) {
done.

2025-02-03 20:44 UTC, MichaelEischer commented
I've rebased the PR (to have Go 1.22 as minimum version), and made a few cleanups.

2025-02-03 20:44 UTC, MichaelEischer approved these changes

2025-02-03 21:07 UTC, merged

2025-02-03 21:17 UTC, MichaelEischer commented
Thanks for keeping up with all the review comments :-) . I've opened https://github.com/restic/restic/pull/5235 in case you're interested in the refactorings I had in mind.