Issue 5109: Selection of packs to repack based on size
restic/restic pull request #5183
Opened 2024-12-16 15:03 UTC by wplapper

cmd_prune: Selection of packs to repack based on size. Add option --small-pack-size so prune can repack all packfiles smaller than small-pack-size bytes.

What does this PR change? What problem does it solve?
-----------------------------------------------------

Add option --small-pack-size so prune can repack all packfiles smaller than small-pack-size bytes.
The new option is passed onto internal/repository/prune.go.
A new decision has been added to "decide what to do" to
move the intended packfiles onto the repackSmallCandidates queue.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
https://github.com/restic/restic/issues/5109

Checklist
---------

- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I'm done! This pull request is ready for review.

2025-01-26 19:35 UTC, MichaelEischer requested changes
The change in `internal/repository/prune.go` is more complex than it needs to be. It should be sufficient to just set the  `targetPackSize` to the user specified value. The current approach feels like a duplication of the existing selection of small packs.

The PR also must be rebased onto the current master branch as we generally don't merge PRs that contain merge commits. (See the `git rebase` command / the [git book](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)).

I'd also like to have a small test for the new option, although I can also help with that. The test should probably use an approach similar to that of https://github.com/restic/restic/pull/5212/files .

2025-01-26 19:35 UTC, MichaelEischer commented on cmd/restic/cmd_prune.go
> +	f.StringVar(&pruneOptions.MaxRepackSize, "max-repack-size", "", "maximum `size` to repack (allowed suffixes: k/K, m/M, g/G, t/T)")
Please revert this change, the wording has somewhat recently changed to `stop after repacking this much data in total` to improve the clarity of the description.

2025-01-26 19:35 UTC, MichaelEischer commented on cmd/restic/cmd_prune.go
> +	f.StringVar(&pruneOptions.SmallPackSize, "small-pack-size", "0", "pack `below-limit` packfiles smaller than (allowed suffixes: k/K, m/M, g/G, t/T)")
The default value should be an empty string.

2025-01-26 19:35 UTC, MichaelEischer commented on cmd/restic/cmd_prune.go
> +	ctx, repo, unlock, err := openWithExclusiveLock(ctx, gopts, false)
Please revert this change.

2025-01-26 19:35 UTC, MichaelEischer commented on internal/repository/prune.go
> -
unnecessary whitespace change.

2025-01-26 19:35 UTC, MichaelEischer commented on internal/repository/prune.go
> +		//wpl 2024-11-08 - repack when packSize is smaller than opts.SmallPackBytes
There is no need to manually mark who and when some logic was changed, git already takes care of that automatically.

2025-01-26 19:35 UTC, MichaelEischer commented on internal/repository/prune.go
> +	}) // end repo.List(ctx, restic.PackFile ...)
Unnecessary comment.

2025-01-26 19:35 UTC, MichaelEischer commented on internal/repository/prune.go
> +	SmallPackSize  string
There's no point in passing the string version of SmallPackSize to `prune` as it only needs `SmallPackBytes`.

2025-01-26 19:35 UTC, MichaelEischer commented on internal/repository/prune.go
> +	SmallPackBytes uint64
Please add a check to prune that `SmallPackBytes <= repo.packSize()`

2025-01-26 19:35 UTC, MichaelEischer commented on internal/repository/prune.go
> +		case opts.RepackSmall && (uint64(packSize) <= opts.SmallPackBytes):
I don't think we need a special case here. Just set `targetPackSize` to `opts.SmallPackBytes` if the latter is non-zero and `opts.RepackSmall` is set.

2025-01-26 19:35 UTC, MichaelEischer commented on internal/repository/prune.go
> +	if len(repackSmallCandidates) >= 10 || opts.RepackSmall && (uint64(sizeRepackSmallCandidates) >= maxUnusedSizeAfter) {
Please revert this change. If users set `--max-unused 0`, your change causes repeated prune executions to repack the same data each time. The point of repacking small files is reduce the number of files, but a few files more or less won't matter. If `--max-unused` yields a large value (>= 1.28GB to be precise), then the new clause is irrelevant as `len(repackSmallCandidates) >= 10` will always be true first.

2025-01-26 19:35 UTC, MichaelEischer commented on changelog/unreleased/issue-5109
> +Issue #5109 - Selection of packs to repack based on size
Please follow the template from https://github.com/restic/restic/blob/master/changelog/TEMPLATE .
The changelog for this PR should look something like the following:
```
Enhancement: Make small pack size configureable for `prune`

The `prune` command now supports the `--small-pack-size` option that
allows repacking pack files smaller than the given size.

https://github.com/restic/restic/issues/5109
https://github.com/restic/restic/pull/5183
```

The changelog entries for restic are intended for end users. Those likely only know the CLI but have no knowledge of any internal code.

2025-01-29 08:22 UTC, wplapper commented on cmd/restic/cmd_prune.go
> +	f.StringVar(&pruneOptions.MaxRepackSize, "max-repack-size", "", "maximum `size` to repack (allowed suffixes: k/K, m/M, g/G, t/T)")
done

2025-01-29 08:22 UTC, wplapper commented on cmd/restic/cmd_prune.go
> +	f.StringVar(&pruneOptions.SmallPackSize, "small-pack-size", "0", "pack `below-limit` packfiles smaller than (allowed suffixes: k/K, m/M, g/G, t/T)")
done

2025-01-29 08:23 UTC, wplapper commented on cmd/restic/cmd_prune.go
> +	ctx, repo, unlock, err := openWithExclusiveLock(ctx, gopts, false)
done

2025-01-29 08:25 UTC, wplapper commented on internal/repository/prune.go
> -
done

2025-01-29 08:25 UTC, wplapper commented on internal/repository/prune.go
> +		//wpl 2024-11-08 - repack when packSize is smaller than opts.SmallPackBytes
comment removed.

2025-01-29 08:27 UTC, wplapper commented on internal/repository/prune.go
> +	SmallPackSize  string
SmallPackSize removed

2025-01-29 08:42 UTC, wplapper commented on internal/repository/prune.go
> +	SmallPackBytes uint64
added check in decidePackAction

2025-01-29 14:34 UTC, wplapper commented on internal/repository/prune.go
> +	}) // end repo.List(ctx, restic.PackFile ...)
comment removed

2025-01-29 14:34 UTC, wplapper commented on internal/repository/prune.go
> +	SmallPackSize  string
field SmallPackSize   removed

2025-01-29 14:45 UTC, wplapper commented on changelog/unreleased/issue-5109
> +Issue #5109 - Selection of packs to repack based on size
done.

2025-01-29 21:50 UTC, MichaelEischer requested changes
Thanks, I found a few more nits

2025-01-29 21:50 UTC, MichaelEischer commented on internal/repository/prune.go
> +	SmallPackBytes uint64
That check should happen right at the start of `PlanPrune`. `decidePackAction(...)` is too late as prune can have performed a significant amount of processing up to that point.

2025-01-29 21:50 UTC, MichaelEischer commented on internal/repository/prune.go
> +		if opts.SmallPackBytes > 0 && opts.RepackSmall {
Please move that to the point where `targetPackSize`  is initially computed (that is after line 336)

2025-01-29 21:50 UTC, MichaelEischer commented on cmd/restic/cmd_prune.go
> +	size, err := ui.ParseBytes(smallPackSize)
This needs a special case to not fail if  `smallPackSize` is an emtpy string.

2025-01-30 08:04 UTC, wplapper commented on internal/repository/prune.go
> +		if opts.SmallPackBytes > 0 && opts.RepackSmall {
done

2025-01-30 08:04 UTC, wplapper commented on cmd/restic/cmd_prune.go
> +	size, err := ui.ParseBytes(smallPackSize)
fixed the bug.

2025-01-30 08:25 UTC, wplapper commented
I added logic to the case `p.unusedBlobs == 0 && p.tpe != restic.InvalidBlob && !mustCompress`: in case we deal with `--repack-small` and have `--small-pack-size`with a non-zero value, these packs get all dropped into the repackSmallCandidates` bucket.

2025-01-30 10:28 UTC, wplapper commented
> I'd also like to have a small test for the new option, although I can also help with that. The test should probably use an approach similar to that of https://github.com/restic/restic/pull/5212/files .

The plan for the test is as follows:
1.) create repository  with packsize of 2M.
2.) create enough data for 3 packfiles, something in the range of 7-8 M.
3.) run a `repository.PlanPrune(...)` with a packsize of 16M (current default).
4.) run `plan.Execute(...)`, extract `pan.Stats()`.
5.) The result should be 2 packfiles, one for TreeBlobs and one for DataBlobs.
6.) Check that all blobs are contained in the new packfiles.

2025-01-30 18:09 UTC, wplapper commented
> 1.) create repository with packsize of 2M.
> 2.) create enough data for 3 packfiles, something in the range of 7-8 M.
> 3.) run a `repository.PlanPrune(...)` with a packsize of 16M (current default).
> 4.) run `plan.Execute(...)`, extract `plan.Stats()` and check.
> 5.) The result should be 2 packfiles, one for TreeBlobs and one for DataBlobs.
> 6.) Check that all blobs are contained in the new packfiles.

The reason why I change the packsize is the simulation to larger packsizes. There might be other methods of forcing repacking of smaller packfiles, but that's what I did :)

2025-02-01 17:31 UTC, MichaelEischer requested changes
I found a few issues with the test, see below. We also have to discuss the method name, in the linked issue the suggestion was to use `--repack-smaller-than`.

```
if packSize >= int64(targetPackSize) && opts.SmallPackBytes == 0 && !opts.RepackSmall {
```
As mentioned in the comment, I have no clue what this is supposed to do.

2025-02-01 17:31 UTC, MichaelEischer commented on cmd/restic/cmd_prune.go
> +	f.StringVar(&pruneOptions.SmallPackSize, "small-pack-size", "", "pack `below-limit` packfiles smaller than (allowed suffixes: k/K, m/M, g/G, t/T)")
I just noticed that the original issue suggested `--repack-smaller-than` as option. Is there a particular reason to deviate from that?

P.S. the description should be  (pack -> repack, packfiles -> pack files)
```
"repack pack files smaller than `below-limit` (allowed suffixes: k/K, m/M, g/G, t/T)"
```
We could also drop the `t/T` suffix as it will always lead to an error. `g/G` currently is also always an error as the pack size is still limited to 128MB, but that could change in the future.

2025-02-03 13:15 UTC, wplapper commented on internal/repository/prune.go
> +	if opts.SmallPackBytes > 0 && opts.RepackSmall {
done.

2025-02-03 13:15 UTC, wplapper commented on internal/repository/prune.go
> +			if packSize >= int64(targetPackSize) && opts.SmallPackBytes == 0 && !opts.RepackSmall {
removed faultt if-clause.

2025-02-03 13:16 UTC, wplapper commented on internal/repository/repository.go
> +func (r *Repository) SetPackSize(size uint) {
method removed.

2025-02-03 13:17 UTC, wplapper commented on internal/repository/prune_test.go
> +	_ = plan
assignment is gone.

2025-02-03 13:17 UTC, wplapper commented on internal/repository/prune_test.go
> +	rtest.Equals(t, stats.Size.Used <= stats.Size.Repack, true, "all sizes ...")
still working on the tests.

2025-02-03 17:19 UTC, wplapper commented on internal/repository/prune_test.go
> +	rtest.Equals(t, stats.Size.Used <= stats.Size.Repack, true, "all sizes ...")
tests are improved, The checks should be more easily to understand.

2025-02-03 21:32 UTC, MichaelEischer commented
I've rebased the PR (and tried to fix the merge conflicts while rebasing) to remove the clutter from the "files changes" tab on Github.

2025-02-04 08:04 UTC, wplapper commented
Hi Michael,

Thank you for hard work on this PR. As I indicated earlier, I still don't
know much about git and github, and therefore make too many unforced
mistakes. I would appreciate a few hints, what to do, what to avoid.

Thanks again,
Winfried

On Mon, 3 Feb 2025 at 21:32, Michael Eischer ***@***.***>
wrote:

> I've rebased the PR (and tried to fix the merge conflicts while rebasing)
> to remove the clutter from the "files changes" tab on Github.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/restic/restic/pull/5183#issuecomment-2632122928>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEO7MGKEXVY6ILWUNHJDHDD2N7N77AVCNFSM6AAAAABTWK65N2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMZSGEZDEOJSHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-02-04 18:03 UTC, MichaelEischer commented
> Thank you for hard work on this PR. As I indicated earlier, I still don't know much about git and github, and therefore make too many unforced mistakes. I would appreciate a few hints, what to do, what to avoid.

No problem, it was basically "just" a matter of rebasing the PR. However, due to the merge conflicts that required a bit of experience with `git rebase`. The "files added" tab on Github doesn't seem to handle merge commits particularly well,  such that it also shows changes that already exist in the repository. The best way to avoid that is to not add merge commits in a PR in the first place, but instead to rebase it once there's a conflict with other changes in the repository. (having merge commits in a PR is allowed by Github, but frowned upon by many projects including restic)

`git rebase` allows modifying and cleaning up the commit history, which can be useful when the PR evolves over time. By removing unnecessary changes from the commit history, this also reduces the chance of having a merge commit that has to be addressed. Although that is probably already advanced git territory.

2025-02-04 18:21 UTC, MichaelEischer commented
Judging from the "rebase" commits in https://github.com/restic/restic/pull/5185 you're holding `git rebase` very wrong. I can recommend reading through the first few chapters of https://git-scm.com/book/en/v2 and trying out the examples along the way. `git rebase` is supposed to take the existing changes and apply them on top of a different (newer) state of the repository. Rebasing does not create additional commits  (I'm ignoring advanced git rebase usages here). Pushing those changes to Github also requires using `git push --force-with-lease`.

2025-02-05 07:40 UTC, wplapper commented
I understand now why my `git rebase` went so utterly wrong: I have a paper version of the ProGit book and it contains a critical omission in the `rebase` section and does not mention 
`$ git checkout master; $ git merge experiment` at all.

2025-02-07 20:50 UTC, MichaelEischer commented
Please stop pushing merge commits into your PRs.

2025-02-16 15:18 UTC, wplapper commented
I messed up git again, so I did a hard reset and activated all addition and changes.

2025-02-18 08:11 UTC, wplapper commented
Will be reworking the PR based on commit 8c12291f5

2025-03-22 14:36 UTC, MichaelEischer approved these changes
LGTM.

I've changed the `--repack-smaller-than` option to work independently of the `--repack-small` option. My goal is to eventually get rid of `--repack-small` so let's not tie those options together.

[Edit]See https://github.com/restic/restic/issues/5293 for more context on that[/Edit]

2025-03-22 14:43 UTC, merged