Issue 4433: bility to define sort order for output of find command
restic/restic pull request #5184
Opened 2024-12-16 15:20 UTC by wplapper

cmd_find: ability to define sort order for output of find command: Add option --reverse

What does this PR change? What problem does it solve?
-----------------------------------------------------
Added ability to sort output of find command.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

https://github.com/restic/restic/issues/4433
Checklist
---------

- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I'm done! This pull request is ready for review.

2025-01-26 19:46 UTC, MichaelEischer requested changes
Thanks for taking a look at this. The change is simpler than I've initially expected :-) .
A small test case in `cmd/restic/cmd_find_integration_test.go` would also be nice.

As in https://github.com/restic/restic/pull/5183 please rebase the PR instead of adding merge commits.

2025-01-26 19:46 UTC, MichaelEischer commented on changelog/unreleased/issue-4433
> +find: define sorting order of command find.
Please follow the format from https://github.com/restic/restic/blob/master/changelog/TEMPLATE

2025-01-26 19:46 UTC, MichaelEischer commented on cmd/restic/cmd_find.go
> +	f.BoolVarP(&findOptions.Reverse, "reverse", "R", false, "reverse sort order newest->oldest")
`"reverse sort order from newest to oldest"`

2025-01-26 19:46 UTC, MichaelEischer commented on cmd/restic/cmd_find.go
>  		return filteredSnapshots[i].Time.Before(filteredSnapshots[j].Time)
It feels more elegant to let the comparator here check whether `opts.Reverse` is set and directly use the correct order.

2025-01-26 19:46 UTC, MichaelEischer commented on cmd/restic/cmd_find.go
> +	f.BoolVarP(&findOptions.Reverse, "reverse", "R", false, "reverse sort order newest->oldest")
I think we should actually change the default sort order to be from newest to oldest by default. And let the option invert it to the old behavior.

2025-01-27 13:57 UTC, wplapper commented on cmd/restic/cmd_find.go
> +	f.BoolVarP(&findOptions.Reverse, "reverse", "R", false, "reverse sort order newest->oldest")
done.

2025-01-27 13:57 UTC, wplapper commented on cmd/restic/cmd_find.go
>  		return filteredSnapshots[i].Time.Before(filteredSnapshots[j].Time)
done.

2025-01-27 13:58 UTC, wplapper commented on cmd/restic/cmd_find.go
> +	f.BoolVarP(&findOptions.Reverse, "reverse", "R", false, "reverse sort order newest->oldest")
Changed to "oldest to newest".

2025-01-27 13:58 UTC, wplapper commented on changelog/unreleased/issue-4433
> +find: define sorting order of command find.
done. Also pointed out that the default sorting order has changed.

2025-01-27 16:47 UTC, wplapper commented
> As in #5183 please rebase the PR instead of adding merge commits.

@MichaelEischer: as I pointed out before, I don't know how to rebase. I am a really beginner when it comes to git. @rawtaz promised me a chat, but I have no idea how I can contact him.

2025-01-28 09:13 UTC, wplapper commented
Integration test added.

2025-01-28 21:48 UTC, MichaelEischer requested changes
Thanks for the test! I'll unfortunately have to bug you with a bit more tooling, this time gofmt (canonical go code formatting) and golangci-lint (checks for code issues), check the comments for more details.

Regarding rebasing, I can recommend the [git book](https://git-scm.com/book/en/v2/Git-Branching-Rebasing), although I can also rebase the PR in the end if necessary. (I can also make the changes mentioned in the review comments if that's fine for you)

2025-01-28 21:48 UTC, MichaelEischer commented on cmd/restic/cmd_find.go
> +The default sort option for the snapshots is youngest to oldest. One can reverse
Can be shortened to
```
The default sort option for the snapshots is youngest to oldest. To sort the
output from oldest to youngest specify --reverse.`,
```

2025-01-28 21:48 UTC, MichaelEischer commented on changelog/unreleased/issue-4433
> +Enhancement: find: enable sorting of find output, new option --reverse
I'd prefer something like the following:
```
Enhancement: Sort `find` output from newest to oldest and add `--reverse` option
```

2025-01-28 21:48 UTC, MichaelEischer commented on cmd/restic/cmd_find_integration_test.go
> +
Please run `gofmt` on the file. Ideally, set up your editor to automatically format the file when saving it. For example, in VS Code the Go extension even automatically enables auto formatting of files. Thankfully Go has a canonical formatting style so there's no more need to manually format and indent code.

2025-01-28 21:48 UTC, MichaelEischer commented on cmd/restic/cmd_find_integration_test.go
> +	testRunCheck(t, env.gopts)
Running `check` is redundant here. (The existing tests call `check` far often for my taste)

2025-01-28 21:48 UTC, MichaelEischer commented on cmd/restic/cmd_find_integration_test.go
> +	rtest.Assert(t, len(lines) == 2, "expected two files found in repo (%v), found %d", datafile, len(lines))
Please also check that find returns the results in the correct order. (The simplest way is probably to call `testListSnapshots(...)` after creating the first snapshot to get the first ID)

2025-01-28 21:48 UTC, MichaelEischer commented on cmd/restic/cmd_find.go
> +		if opts.Reverse {
Our linter rules expect this to be written as follows:
```go
		if opts.Reverse {
			return filteredSnapshots[i].Time.Before(filteredSnapshots[j].Time)
		}
		return filteredSnapshots[i].Time.After(filteredSnapshots[j].Time)
```

You can manually call `golangci-lint run ./...` to get the linting results (or setup your editor accordingly)

2025-01-28 21:48 UTC, MichaelEischer commented on cmd/restic/cmd_find_integration_test.go
> +type testMatches2 struct {
Please just use the `testMatches` and `testMatch` that already exist.

2025-01-29 20:37 UTC, MichaelEischer approved these changes
LGTM. Thanks for all the tweaks. I've rebased the PR and added a small bugfix for the test case.

2025-01-29 20:44 UTC, merged