Issue: 4942: cmd_rewrite: add snapshot summary data to an existing snapshot.
restic/restic pull request #5185
Opened 2024-12-18 16:39 UTC by wplapper

cmd_rewrite: add capability to add snapshot summary data to an existing snapshot.

Add option --snapshot-summary [-s] to enable this enhancement.

What does this PR change? What problem does it solve?
-----------------------------------------------------
This pull request add the capability of adding snapshot summary data to an existing snapshot.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
https://github.com/restic/restic/issues/4942
closes https://github.com/restic/restic/issues/4942

Checklist
---------

- [x] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [X] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I'm done! This pull request is ready for review.

2024-12-18 16:42 UTC, wplapper commented
There will be a subsequent PR which will allow include filters to be used for the restic rewrite command, see https://github.com/restic/restic/issues/4278 for details.

2024-12-19 18:00 UTC, MichaelEischer requested changes
I found quite a few issues with the code changes, see below for details.

2024-12-19 18:00 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +			if sn.Summary == nil { // change of logic: create summary if it wasn't there before
This comment is only meaningful in the context of this PR, so remove it.

2024-12-19 18:00 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +		// TODO: question: should metadata modification be changed so that
Metadata modifications are expected to be fast operations, so I think we should keep the current behavior.

2024-12-19 18:00 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +			Printf("snapshot %s has already got snapshot summary data\n", sn.ID().Str())
The other options don't print anything for not modified snapshots. Remove the `printf` to be consistent with that behavior.

2024-12-19 18:00 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +			Verbosef("totalFilesProcessed %12d\n", ss.FileCount)
What's the purpose of that debug output?

2024-12-19 18:00 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +	} else if opts.SnapshotSummary {
This if-clause is 90% duplicated code. Merge it with the if-clause above.

2024-12-19 18:00 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +	sn.ProgramVersion = version
Hmm, I'm not sure whether that is a good idea. Keeping the original program version is rather useful to know which restic version created a snapshot, which is the most likely point in time when something can go wrong.

2024-12-19 18:00 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +	if filteredTree == *sn.Tree && newMetadata == nil && sn.Summary == nil {
This breaks the "snapshot %v not modified" check if `rewrite --exclude ...` or `repair snapshots` are used on snapshots that already have a summary section.

2024-12-19 18:00 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +The option --snapshot-summary [-s] creates a new snapshot with snapshot summary data attached.
Let's just describe the long option name here. Please also extend the description to clarify that the snapshot summary is only calculated if it doesn't exist.

2024-12-19 18:00 UTC, MichaelEischer commented on changelog/unreleased/issue-4942
> +https://github.com/restic/restic/issues/4942
Add a link to this PR.

2024-12-19 18:00 UTC, MichaelEischer commented on changelog/unreleased/issue-4942
> +There is a logic change in cmd_rewrite: statistics data will always be attached,
`cmd_rewrite` is an internal filename. The changelog should be written from a user perspective that is use `rewrite` here.

2024-12-19 19:12 UTC, MichaelEischer reviewed
Oh and please change the commit description such that the first line is `cmd_rewrite: add capability to add snapshot summary data to an existing snapshot.`. The `Issue" 4942` part is not useful as summary.

2024-12-19 21:49 UTC, wplapper commented
@MichaelEischer: Thank you for reviewing my code. I have updated the code as you requested. The new tag for creating snapshot summary data is "snap-summary". See changes in PR #5185.

2025-01-25 11:17 UTC, wplapper commented on changelog/unreleased/issue-4942
> +https://github.com/restic/restic/issues/4942
done.

2025-01-25 11:17 UTC, wplapper commented on changelog/unreleased/issue-4942
> +There is a logic change in cmd_rewrite: statistics data will always be attached,
done.

2025-01-25 11:17 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +The option --snapshot-summary [-s] creates a new snapshot with snapshot summary data attached.
done.

2025-01-25 11:18 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +			if sn.Summary == nil { // change of logic: create summary if it wasn't there before
comment has been removed.

2025-01-25 11:18 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +	} else if opts.SnapshotSummary {
code has been restructured.

2025-01-25 11:19 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +			Printf("snapshot %s has already got snapshot summary data\n", sn.ID().Str())
Printf removed.

2025-01-25 11:19 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +			Verbosef("totalFilesProcessed %12d\n", ss.FileCount)
debug output removed.

2025-01-25 11:19 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +		// TODO: question: should metadata modification be changed so that
comment removed.

2025-01-25 11:20 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +	if filteredTree == *sn.Tree && newMetadata == nil && sn.Summary == nil {
code restructured.

2025-01-25 11:20 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +	sn.ProgramVersion = version
removed my code.

2025-01-26 20:25 UTC, MichaelEischer requested changes
Sorry for the review delay and asking for further significant changes.

Revert the addition of the `"snap-summary"` tag. As discussed in the comments it is only applied inconsistently and rather appears to be a hack. The root cause is that the `filter (...)` function currently lacks a way to track modifications of the snapshot summary. So the clean way to implement this change is to add this modification tracking. Also please add an integration test that checks that a snapshot that has a summary is not modified unnecessarily.

Other than that, please rebase the PR onto the latest master branch.

2025-01-26 20:25 UTC, MichaelEischer commented on changelog/unreleased/issue-4942
> +will be non-zero: TotalFilesProcessed and TotalBytesProcessed.
The changelog does not mention that rewritten snapshots without summary also get that information automatically.

2025-01-26 20:25 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +			rewriteTag = "snap-summary"
All other options also use the `rewrite` tag, thus it feels weird to just use it if `--snapshot-summary` is specified, but without excludes. That is, keep the "rewrite" tag as before.

2025-01-26 20:25 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +			selectByName := func(nodepath string) bool {
`selectByName` returns true if `len(rejectByNameFuncs) == 0`. That is the `else` clause below is redundant.

2025-01-26 20:25 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +			if sn.Summary == nil {
Let's implement this properly and change the filter function to return a new `restic.SnapshotSummary`. If that does not match the summary of the snapshot, then the snapshot has to be written. That way the `&& addTag != "snap-summary"` hack is no longer necessary.

2025-01-26 20:25 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +	if opts.SnapshotSummary && sn.Summary != nil {
That check is somewhat unexpected from a user perspective. It should be possible to specify both `--snapshot-summary --exclude /some/file` or `--snapshot-summary --new-host host`.

So the check belongs before `id, err := rewriter.RewriteTree(ctx, repo, "/", *sn.Tree)` and should also account for `rejectByNameFuncs`

2025-01-28 11:41 UTC, wplapper commented on changelog/unreleased/issue-4942
> +Enhancement: create snapshot summary statistics for snapshots which don't have them
done

2025-01-28 11:41 UTC, wplapper commented on changelog/unreleased/issue-4942
> +When restic rewrite is used with the --snapshot-summary option,
done

2025-01-28 11:42 UTC, wplapper commented on changelog/unreleased/issue-4942
> +will be non-zero: TotalFilesProcessed and TotalBytesProcessed.
done

2025-01-28 11:42 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +			rewriteTag = "snap-summary"
`rewriteTag` removed.

2025-01-29 07:17 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +			if sn.Summary == nil {
filter now passes back a restic.SnapshotSummary

2025-01-29 07:19 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +	if opts.SnapshotSummary && sn.Summary != nil {
the check has been reformulated and is now snapshot specific. If only `--snapshot-summary` is specified and nothing else and snapshot already has a summary record, then nothing will happen.

2025-02-01 20:11 UTC, MichaelEischer requested changes
I've added quite a few comments how to fix the implementation and how to remove the SnapshotSummary for a snapshot. Please don't introduce random backwards-incompatible changes in the PR, this will just result in additional work for everyone and reverting those changes.

2025-02-01 20:11 UTC, MichaelEischer commented on cmd/restic/testdata/backup-data.tar.gz
Why did this file change? It looks like the file from the `ls` PR.

2025-02-01 20:11 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	// since we have attached SnapshotSummary to <snap>, the call to runRewrite is a no op
```suggestion
	// since the backup command adds a SnapshotSummary to <snap>, the call to runRewrite is a no op
```

2025-02-01 20:11 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	t.Helper()
Must not be called in the actual test function.

2025-02-01 20:11 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	_, repo, unlock, err := openWithReadLock(context.TODO(), env.gopts, false)
This won't be able to modify the repository.

2025-02-01 20:11 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	// get repo so we can access snapshot strcuture - this is a hackish.
There's no easy way to get rid of the snapshot summary. The cleanest variant is probably to open the repository with an exclusive lock, then call `restic.LoadSnapshot()`, modify it, store it using `restic.SaveSnapshot()` , delete the old one via `repo.RemoveUnpacked()` and directly unlock the repository afterwards.

2025-02-01 20:11 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	sn, _, err := restic.FindSnapshot(context.TODO(), repo, repo, snap.String())
`snap` is already a `restic.ID` so there's no need to use `restic.FindSnapshot`.

2025-02-01 20:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +			if sn.Summary == nil {
This change is too extensive, I've added a comments how to handle this in a cleaner way.

2025-02-02 11:36 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +	re := regexp.MustCompile("^([A-Za-z0-9][[A-Za-z0-9-]+)$")
removed check

2025-02-02 11:36 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +	return strings.Trim(sma.Hostname, " ") == "" && strings.Trim(sma.Time, " ") == ""
removed code

2025-02-02 11:36 UTC, wplapper commented on internal/walker/rewriter.go
> +type FailedTreeRewriteFunc func(nodeID restic.ID, path string, err error) (restic.ID, *restic.SnapshotSummary, error)
code reverted.

2025-02-02 11:36 UTC, wplapper commented on cmd/restic/cmd_repair_snapshots.go
> +			func(ctx context.Context, sn *restic.Snapshot) (restic.ID, *restic.SnapshotSummary, error) {
all changes dropped.

2025-02-02 11:37 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +			summary := &restic.SnapshotSummary{TotalFilesProcessed: ss.FileCount,
implemented your suggestion.

2025-02-02 13:06 UTC, wplapper commented on cmd/restic/cmd_rewrite_integration_test.go
> +	newHost := "new-host" // hostname cannot contain spaces according to Linux !
reverted change.

2025-02-02 13:06 UTC, wplapper commented on cmd/restic/cmd_rewrite_integration_test.go
> +		//{Hostname: "", Time: newTime}, // hostname must be valid !
reverted change.

2025-02-02 13:07 UTC, wplapper commented on cmd/restic/testdata/backup-data.tar.gz
removed from change.

2025-02-02 14:36 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +	// bug: do not destroy old snapshot!
This is once again intended functionality and not a bug, see `restic repair snapshots`. (just look for all callers of `filterAndReplaceSnapshot` and do a bit of tracing the handling of broken trees from there). If a filter unintentionally does not return a filteredTree, then the filter is broken.

Please try to focus on the change this PR intends to make and don't make apparently random changes (at least from my perspective). While the existing code can definitely have bugs, start by assuming that it is sufficiently correct. It's getting annoying that each review round leads to a new bunch of unrelated changes which then have to be reverted.

2025-02-02 14:36 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +	re := regexp.MustCompile("^([A-Za-z0-9][[A-Za-z0-9-]*)$")
Did you push the changes mentioned in the review comments?

2025-02-02 17:03 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +	// bug: do not destroy old snapshot!
Sorry Michael, 
I do not intend to annoy you. Forgive me for erring into areas which I am not supposed to touch. 
I have reverted all the changes and I went back to square one to started fresh.

However I hit a buffer stop, since the changes I have made since upset tests
TestRepairSnapshotsIntact and TestRewriteUnchanged.

The condition `filteredTree == *sn.Tree && newMetadata == nil` is met when option `--snapshot-summary` is active by itself. However I cannot check it there. The only check I can think of is `sn.Summary == nil`.
See lines 
`	//if filteredTree == *sn.Tree && newMetadata == nil && sn.Summary == nil {
	if filteredTree == *sn.Tree && newMetadata == nil {`.
How do I proceed from here?

2025-02-02 17:05 UTC, wplapper commented on cmd/restic/cmd_rewrite.go
> +	re := regexp.MustCompile("^([A-Za-z0-9][[A-Za-z0-9-]*)$")
regexp removed.

2025-02-04 18:53 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +	// bug: do not destroy old snapshot!
I've reworked the PR quite a bit. The summary is now checked for changes via `matchingSummary = sn.Summary != nil && *summary == *sn.Summary`.

2025-02-04 18:55 UTC, MichaelEischer commented
I've reverted a bunch of the changes to an older state and made the refactoring I had in mind during the last round of reviews. I'll take another look for a final review in the next days.

2025-02-05 19:39 UTC, MichaelEischer approved these changes
LGTM. Thanks for proof of concept for the command!

2025-02-05 19:40 UTC, merged