Issue 4278: Enhancement: include filters in command rewrite
restic/restic pull request #5191
Opened 2024-12-23 07:41 UTC by wplapper

What does this PR change? What problem does it solve?
-----------------------------------------------------
The enhancement allows the standard include filter options.

File internal/filter/include.go gained an "Empty() function, and file internal/walker/rewriter.go gained logic to recognize empty subtrees and suppress their creation for include filtering.

cmd_rewite adds code for inclusion filters. Only subtrees which are needed will be created.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
https://github.com/restic/restic/issues/4278

Checklist
---------

- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [X] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I'm done! This pull request is ready for review.

2024-12-23 08:06 UTC, wplapper commented
I have managed to crack the issue of empty subtrees. This change is incorporated in internal/walker/rewriter.go

2025-02-01 20:42 UTC, MichaelEischer requested changes
A few preliminary comments before you try to further work on this PR

2025-02-01 20:42 UTC, MichaelEischer commented on .github/workflows/tests.yml
> +          version: v1.63.4
Please rebase this PR instead of adding merge commits

2025-02-01 20:42 UTC, MichaelEischer commented on cmd/restic/cmd_repair_snapshots.go
> +		RewriteFailedTree: func(_ restic.ID, path string, _ error) (restic.ID, *restic.SnapshotSummary, error) {
How did that change from https://github.com/restic/restic/pull/5185 end up here?

2025-02-01 20:42 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +						includeLink, _ := followSymlink(nodepath, node, include)
Symlinks should be treated like normal files in regard to include patterns. Everything else is unusable.

2025-02-01 20:42 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +						return false
Nope. Those must be handled like normal files. Please follow the behavior of the backup command as closely as possible. Everything else will confuse users.

2025-02-01 20:42 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +		rewriter, querySize = walker.NewSnapshotSizeRewriter(rewriteNode, keepDirectories)
If the include patterns match an empty directory, then that directory must be kept. This cannot be implemented as a boolean flag passed to the rewriter, but must be checked for each individual node.

To quote myself from https://github.com/restic/restic/pull/5188#pullrequestreview-2515978653 :

> The clean solution would be to extend the `TreeRewriter` options with a new `KeepEmtpyDirectory func(path string) bool` field. If it is unset, then the rewriter behaves like before. If the field is set and the filtered tree is empty then `KeepEmtpyDirectory` decides whether to keep the tree or not. If the tree should not be kept, then `RewriteTree` returns an empty restic.ID which also means that the corresponding node should be dropped.

Effectively the only two options here are adding the flag as return value to `rewriteNode` or passing a `KeepEmtpyDirectory` function to the rewriter.

2025-02-01 20:42 UTC, MichaelEischer commented on internal/walker/rewriter.go
> +const EmptyNodeID = `{"nodes":[]}` + "\n"
Drop that constant you won't need it for a clean implementation.

2025-02-02 17:12 UTC, wplapper commented
I put this PR on hold until PR https://github.com/restic/restic/pull/5185 is fully resolved.

2025-03-24 17:12 UTC, MichaelEischer requested changes
Thanks for the changes so far! I have added quite a few comments, but those are mostly small changes and nitpicks. The general approach now looks like what I had in mind.

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +func TestRewriteExcludeNothing(t *testing.T) {
I'm not sure what this test case actually tests. Even `--exclude *` would not remove a snapshot as `KeepEmptyDirectories` is always true for excludes. Or is that what you wanted to check? Then the exclude pattern must be `*`.

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	rtest.Assert(t, err != nil, "You cannot specify include and exclude options simultaneously!")
I'd prefer `"exclude and include patterns are mutually exclusive"` similar to the restore command as error message.

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	err = runRewrite(context.TODO(), RewriteOptions{
This should work IMHO.

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	rtest.Assert(t, count == 1, "there should be 1 empty directory in the snapshot, but there are %d snapshots", count)
```suggestion
	rtest.Assert(t, count == 1, "there should be 1 empty directory in the snapshot, but there are %d directories", count)
```

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	out := testRunLsWithOpts(t, env.gopts, LsOptions{}, []string{newSnapshots[0].String()})
Nice approach

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	rtest.Assert(t, sn.Summary != nil, "snapshot should have a summary attached")
Please additionally use `testRunLsWithOpts` to check that the directory has actually be removed.

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	rtest.OK(t, err)
```suggestion
	rtest.OK(t, err)
	defer unlock()
```

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	unlock()
```suggestion
```

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	rtest.Assert(t, count == 2, "there should be 2 txt files in the snapshot, but there are %d files", count)
Please extract this into a helper function. And also use it for `TestRewriteEmptyDirectory`.

2025-03-24 17:12 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +	_, repo, unlock, err := openWithExclusiveLock(context.TODO(), env.gopts, false)
Same here

2025-10-18 07:54 UTC, wplapper commented
I manually moved all the changed code to the new restic level 0.18.1. Otherwise all requested changes should still be incorporated, The only bit which is somewhat different is ``cmd_rewrite_integration_test.go``.

2025-11-21 14:43 UTC, wplapper commented
Rebased changes onto current development tree.

2025-12-28 17:33 UTC, wplapper commented
Rebased changes onto current development tree.

2026-01-31 21:36 UTC, MichaelEischer approved these changes
LGTM. I've added a few commits that include a bunch of smaller cleanups, add tests for `KeepEmptyDirectory` and change the node filtering to only include directories that have a chance that some file in a subdirectory matches. The latter can speed up rewrite quite a lot, when for example matching against `/data` or some other absolute path.

2026-01-31 21:36 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite.go
> +			if matched && childMayMatch {
TODO

2026-01-31 21:36 UTC, MichaelEischer commented on cmd/restic/cmd_rewrite_integration_test.go
> +			ExcludePatternOptions: filter.ExcludePatternOptions{Excludes: []string{"nothing-whatsoever"}},
This test case doesn't test anything at the moment. It would have to test using pattern `*`. However, then the test fails as it is currently perfectly valid to just exclude all files in a snapshot. For simplicity I think we should just keep it at that and drop this testcase.

2026-02-01 06:16 UTC, wplapper commented
Thanks. It was a long haul.

2026-02-01 10:53 UTC, merged