Json check
restic/restic pull request #5194
Opened 2024-12-30 21:42 UTC by darkdragon-001

What does this PR change? What problem does it solve?
-----------------------------------------------------

Add JSON output to the `check` command.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

#1378
#4581

Checklist
---------

<!--
You do not need to check all the boxes below all at once. Feel free to take
your time and add more commits. If you're done and ready for review, please
check the last box. Enable a checkbox by replacing [ ] with [x].

- [ ] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [ ] I'm done! This pull request is ready for review.

2024-12-30 22:54 UTC, darkdragon-001 commented
I am not sure about the last commit: Do we want to assemble such an extensive summary or are we fine with just wrapping the errors into JSON?

2024-12-31 00:09 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +	NumDataErrors   int      `json:"num_data_errors"`
Should we merge these?
```suggestion
	NumErrors       int     `json:"num_errors"`
```

2024-12-31 00:09 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +	HintPrune       bool     `json:"suggest_prune"`        // run "restic prune"
Do we want these hints?

2024-12-31 00:09 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +	BrokenPacks     []string `json:"broken_packs"`         // run "restic repair packs ID..." and "restic repair snapshots --forget" to remove damaged files
Do we want these IDs in the status or does this encourage people to script such destructive commands?

2025-02-01 21:23 UTC, MichaelEischer requested changes
Letting the `check` command only print a summary just works if a repository is not damaged. For a damaged repository, **all** error messages must also be available in the JSON output, otherwise we'll end up in a situation where all relevant information is missing. The summary by itself is mostly useless when it comes to debug what is wrong with a repository.

I wouldn't be terribly opposed to having an error and warning output message that for now just includes the formatted text output. If necessary, we could introduce an "error_code" field in the future to allow for more automation.

2025-02-01 21:23 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +		result.NumUnusedBlobs = len(unused)
Checking for unused blobs can only be used by tests. So I don't think we should expose that number via the JSON output.

2025-02-01 21:23 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
>  		} else {
The `printer.E` below is not accounted for.

2025-02-01 21:23 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +	NumDataErrors   int      `json:"num_data_errors"`
There's at least the category of snapshot errors missing. The main question here is what one can do with  knowing that there are 5 data errors in contrast to 5 index errors. In regards to index errors one could run `repair index` but giving you that information is the task of `suggest_repair_index`. So, I'm leaning somewhat towards only keeping the overall number of errors.

2025-02-01 21:23 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +	NumDataErrors   int      `json:"num_data_errors"`
What is a `data` error in contrast to a `pack` error? Both refer to pack files.

2025-02-01 21:23 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +	BrokenPacks     []string `json:"broken_packs"`         // run "restic repair packs ID..." and "restic repair snapshots --forget" to remove damaged files
Well, finding the commands in the output is already possible. What I'm more worried about is that the means to repair a repository will likely evolve over time. Although we could just get rid of old JSON fields by stopping to use them once they are no longer relevant.

2025-02-01 21:23 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +		printer = &progress.NoopPrinter{}
Not printing the error message is not an option. Running check without seeing the errors returned by `check` is useless and prevent us and users from debugging the underlying issue.

2025-02-02 12:01 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +	NumDataErrors   int      `json:"num_data_errors"`
I merged this into a single error count.

2025-02-02 12:03 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +	BrokenPacks     []string `json:"broken_packs"`         // run "restic repair packs ID..." and "restic repair snapshots --forget" to remove damaged files
I interpret your message as "keep this information inside the JSON". Resolving.

2025-02-02 12:04 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +	HintPrune       bool     `json:"suggest_prune"`        // run "restic prune"
Same as https://github.com/restic/restic/pull/5194#discussion_r1938346612. Resolving.

2025-02-02 12:10 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +type Printer interface {
There is a [`ui.Message` type](https://github.com/restic/restic/blob/536ebefff44a3278fda42550137ac0f15df8d2fe/internal/ui/message.go#L8-L11) but it is not an interface such that one replace the implementation.
There is the [`progress.Printer` interface](https://github.com/restic/restic/blob/536ebefff44a3278fda42550137ac0f15df8d2fe/internal/ui/progress/printer.go#L8-L15) which also requires `NewCounter(description string) *Counter` method. As we don't need the `NewCounter()` method here, I preferred declaring another interface which is compatible with existing types.

2025-02-02 12:14 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +	result.HintRepairIndex = false
Removed this unnecessary initialization.

2025-02-02 12:18 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +		result.NumUnusedBlobs = len(unused)
Removed this field from the JSON output.

2025-02-02 12:21 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
>  		} else {
I now also increment the unified errors count in the `else` clause.

Would this be the "snapshot error" type as mentioned in https://github.com/restic/restic/pull/5194#discussion_r1938346379?

2025-02-02 12:27 UTC, darkdragon-001 commented on doc/075_scripting.rst
> +The ``check`` command outputs JSON messages with the following format:
I added the `message_type` field.

2025-02-02 12:28 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +	NumDataErrors   int      `json:"num_data_errors"`
I unified the error counts per https://github.com/restic/restic/pull/5194#discussion_r1899856559.

2025-02-02 12:31 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +		printer = &progress.NoopPrinter{}
With the `broken_packs`, `suggest_repair_index` and `suggest_repair_index` fields, the JSON output is actionable without the specific error messages.

As an alternative, in https://github.com/restic/restic/pull/5194#issuecomment-2565986326, I suggested dropping the last commit such that this PR is basically f7d567349b6efc60579e358dc49b52ae53e63311. Please let me know if you prefer to follow this approach.

2025-02-02 12:33 UTC, darkdragon-001 commented
@MichaelEischer Thanks for your review! I acted upon all threads. Please take another look.

2025-02-02 15:25 UTC, MichaelEischer requested changes
Thanks for the changes so far! I have a few more comments.

2025-02-02 15:25 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +		printer = &progress.NoopPrinter{}
> With the `broken_packs`, `suggest_repair_index` and `suggest_repair_index` fields, the JSON output is actionable without the specific error messages.

Only for a few trivial cases. Quite a few of the check errors that show up in forum require manual intervention by the user. But without the detailed error messages that would be impossible to tell. In fact, without the error message, `check` degrades to something that essentially just says that it is broken, but without providing any details. Such settings are incredibly annoying to debug (both for the user themselves and by someone else in the forum). (running `check` as second time without `--json` also isn't an option as errors can be transient)

The `checkError` message from https://github.com/restic/restic/commit/f7d567349b6efc60579e358dc49b52ae53e63311 looks more like what I had in mind. Keeping the more detailed `checkResult` summary message type and such an error message don't exclude each other.

2025-02-02 15:25 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
>  		return errors.Fatal("repository contains errors")
`result` is never printed  in this case.

2025-02-02 15:25 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +		bar := newTerminalProgressMax(!gopts.Quiet && !gopts.JSON, 0, "snapshots", term)
should use `bar := printer.NewCounter("snapshots")`. I forgot to convert the progress bars when switching `check` to `printer.Progress`.

2025-02-02 15:25 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +	MessageType     string   `json:"message_type"`
Add a comment that the expected message type is `summary`.

2025-02-02 15:25 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
>  		} else {
Those error include the "snapshot error" type, but probably also some other errors.

2025-02-02 16:05 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +type Printer interface {
Using `ui.NewMessage()` seems more appropriate and lightweight if we don't need a progress printer.

In f7d567349b6efc60579e358dc49b52ae53e63311 I also added a custom printer type to collect the error messages. I can use a no-op `NewCounter()` method there if you prefer.

2025-02-02 16:08 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +		printer = &progress.NoopPrinter{}
If it requires manual intervention, running the check manually without `--json` seems appropriate (if the errors are transient, there shouldn't be the need for manual intervention).

2025-02-02 16:10 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +	MessageType     string   `json:"message_type"`
Done

2025-02-02 16:35 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +		bar := newTerminalProgressMax(!gopts.Quiet && !gopts.JSON, 0, "snapshots", term)
Done in 2b1686d6694cb0c5f676b9dadbb6c6c443c704f8.

2025-02-02 16:35 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +type Printer interface {
I switched to using the `progress.Printer` interface.

2025-02-02 16:44 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
>  		return errors.Fatal("repository contains errors")
The summary wasn't printed in any of the early returns. I added 1a2b9ba37ed0309d42b2cede8836fe99cf9f9d56 to always print the summary JSON.

2025-02-02 17:33 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +		printer = &progress.NoopPrinter{}
I now keep printing the error messages in JSON as well.

2025-02-02 17:38 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +		bar := newTerminalProgressMax(!gopts.Quiet && !gopts.JSON, 0, "snapshots", term)
FYI: I cannot use this approach for "packs" as this uses `packCount` instead of `0`.

2025-02-02 17:50 UTC, darkdragon-001 commented
@MichaelEischer I addressed all remaining comments. Could you please take another look?

2025-02-05 20:11 UTC, MichaelEischer requested changes
I have a few more small nits, but then we should be done.

2025-02-05 20:11 UTC, MichaelEischer commented on doc/075_scripting.rst
> +| ``message``          | Error message                             |
Please add a warning that the message `May change in arbitrary ways across restic versions`.

2025-02-05 20:11 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +		p := newTerminalProgressMax(!gopts.Quiet && !gopts.JSON, packCount, "packs", term)
```suggestion
		p := printer.NewCounter("packs")
		p.SetMax(uint64(len(packs)))
```

2025-02-05 20:11 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +			term.Print(ui.ToJSONString(summary))
If check fails, then the summary should IMHO always return a non-zero number of errors. I'm pretty sure that everyone is going to check the exit code even though that's absolutely necessary.
```suggestion
			if err != nil && summary.NumErrors == 0 {
				summary.NumErrors = 1
			}
			term.Print(ui.ToJSONString(summary))
```

2025-02-05 21:04 UTC, darkdragon-001 commented on doc/075_scripting.rst
> +| ``message``          | Error message                             |
Done.

_FYI: I previously just copied it from other commands which do not have this addition._

2025-02-05 21:05 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +			term.Print(ui.ToJSONString(summary))
Done.

_FYI: I had this in a previous version but then decided against it and only count errors arising from a broken repository but not from a failing check action._

2025-02-05 21:06 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +		p := newTerminalProgressMax(!gopts.Quiet && !gopts.JSON, packCount, "packs", term)
passing the maximum value to `newTerminalProgressMax` or setting it via `SetMax` is equivalent

2025-02-05 21:08 UTC, MichaelEischer commented on cmd/restic/cmd_check.go
> +			term.Print(ui.ToJSONString(summary))
I'm aware it isn't ideal. But making sure that users noticed failed check runs has priority

2025-02-05 21:08 UTC, darkdragon-001 commented on cmd/restic/cmd_check.go
> +		p := newTerminalProgressMax(!gopts.Quiet && !gopts.JSON, packCount, "packs", term)
I only now noticed the `p.SetMax()` call and fixed it. Done.

2025-02-05 21:10 UTC, MichaelEischer approved these changes
LGTM. Thanks!

2025-02-05 21:15 UTC, merged