Added latest keyword in ls command.
restic/restic pull request #723
Opened 2017-01-12 03:29 UTC by ulziibuyan

The restore command has the special "latest" snapshot keyword. Why not have same for listing files and directories? :-)

2017-01-12 07:55 UTC, fd0 requested changes
Thanks for the PR, please add the options for paths and hostname.

2017-01-12 07:55 UTC, fd0 commented on src/cmds/restic/cmd_ls.go
> +		id, err = restic.FindLatestSnapshot(repo, paths, "")
Have a look at how `FindLatestSnapshot` is used in the restore command. There, you can specify the list of paths and a hostname. I think we should add that here, too, to make the user interface consistent.

2017-01-14 04:56 UTC, ulziibuyan commented
Options added. Should I open issue for this PR? Actually, just read CONTRIBUTING.MD

2017-01-15 11:39 UTC, fd0 commented
It's not necessary to add an additional issue, the PR is enough for now.

2017-01-15 11:42 UTC, fd0 approved these changes

2017-01-15 11:42 UTC, fd0 commented
LGTM, thanks for your work!

2017-01-15 11:42 UTC, merged