Added json ouput of snapshots
restic/restic pull request #751
Opened 2017-01-28 13:11 UTC by ibib

This PR adds json support as requested in [#726](https://github.com/restic/restic/issues/726)

2017-01-29 09:29 UTC, fd0 requested changes
Thanks for your work, please see my review comments.

2017-01-29 09:29 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +	Json  bool
Make this a global option, so we can add it to other commands as well.

2017-01-29 09:29 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +	if opts.Json == true {
The `==` is unneeded, please remove it.

2017-01-29 09:29 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +		jsonoutput(list)
Add a `return` after this and remove the `else` branch.

2017-01-29 09:29 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +func naturaloutput(list []*restic.Snapshot) {
This function needs a new name, all functions in the restic binary share the same namespace. What about `printSnapshots()`?

2017-01-29 09:29 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +	Directory []string `json:"directory"`
Please also use the plural `Directories` here.

2017-01-29 09:29 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +func jsonoutput(list []*restic.Snapshot) error {
This function also needs a different name. What about `printSnapshotsJSON()`?

2017-01-29 09:29 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +	output, _ := json.Marshal(response)
Use a `json.Decoder` here, like `dec := json.NewDecoder(os.Stdout)` and then use its `Decode()` method.

2017-01-29 12:17 UTC, ibib commented
Thank you for your annotations.
Sorry that this PR is a bit ugly, this is my first opensource contribution.

I am working now on the JSON encode thingy and will then look in how to resolve conflicts.

The describing text at the global JSON option was choosen on purpose as it only works with the snapshot option at the moment. `print snapshots in json format`

I cant use `printSnapshots()` as function name as it is already in use [here](https://github.com/restic/restic/blob/master/src/cmds/restic/cmd_forget.go#L63).
Would this be a candidate for refactoration?

2017-02-01 10:24 UTC, fd0 commented
> Sorry that this PR is a bit ugly, this is my first opensource contribution.

Oh, that's great, I'm honored!

> The describing text at the global JSON option was chosen on purpose as it only works with the snapshot option at the moment. print snapshots in json format

Okay, we'll leave it for now.

> I cant use printSnapshots() as function name as it is already in use here.
> Would this be a candidate for refactoration?

Yes, but not in this PR.

I'll add further comments now.

Are you aware that you accidentally merged the master branch in again? I know that git and GitHub are a hard to understand for beginners.

2017-02-01 10:39 UTC, fd0 requested changes

2017-02-01 10:39 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +//printSnapshotsReadable provides human redability
Please describe what the function does, e.g.:

```
// printSnapshotsReadable prints a text table of the snapshots in list to stdout.
```

Also add a space character after the comment (`//`), and make sure that the description is a complete sentence, as described in https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences.

2017-02-01 10:39 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +//Snapshot provides struct to store snapshots
Actually I'd prefer to use the JSON representation we're storing in the repository, it is defined on the `Snapshot` struct here (so you do not need a special struct at all): https://github.com/restic/restic/blob/master/src/restic/snapshot.go#L13-L27

2017-02-01 10:39 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +//printSnapshotsJSON provides machine redability
Add a space after `//`, then describe what the function does, e.g.:
```
// printSnapshotsJSON writes the JSON representation of list to stdout.
```

2017-02-01 10:39 UTC, fd0 commented on src/cmds/restic/cmd_snapshots.go
> +	fmt.Fprint(os.Stdout, "[")
Are you aware that you can just pass a `[]Snapshot` to the encoder? Like this:
```go
err := json.NewEncoder(os.Stdout).Encode(list)
```

The encoder prints the list delimiters (`[` and `]`) automatically.

2017-02-01 10:39 UTC, fd0 commented on src/cmds/restic/global.go
> +	f.BoolVarP(&globalOptions.JSON, "json", "", false, `print snapshots in json format`)
Use double quotes (`"`) for the help text. What do you think about the following help text: `set output mode to JSON for commands that support it`

2017-02-11 09:43 UTC, fd0 commented
Hey, do you have any questions? Is there anything I can do to help you? Or do you just not have any spare time at the moment? :)

2017-02-12 00:36 UTC, ibib commented
I tried to use [`err := json.NewEncoder(os.Stdout).Encode(list)`](https://gist.github.com/ibib/f705fb8982bcf0295f9e75f7c22ce3f1) as suggested but i couldn't work out how to print the id's.
The latest commit should provide the same result.

2017-02-12 09:09 UTC, fd0 commented
You can create a new struct `Snapshot` that [embeds](https://golang.org/ref/spec#Struct_types)  `*restic.Snapshot`, and add an `ID` field like this:
```go
// Snapshot helps to print Snaphots as JSON
type Snapshot struct {
	*restic.Snapshot

	ID string `json:"id"`
}
```

It has all the fields `restic.Snapshot` has, and an additional `ID` field, and you don't even need to repeat all field names!

This new struct can then be used to construct a list of `Snapshot` like this:
```go
	var snapshots []Snapshot
	for _, sn := range list {
		k := Snapshot{
			Snapshot: sn,
			ID:       sn.ID().String(),
		}

		snapshots = append(snapshots, k)
	}
```
Finally, just print this list:
```go
	return json.NewEncoder(os.Stdout).Encode(snapshots)
```

2017-02-12 11:46 UTC, ibib commented
Wow. That is totally more easy. 

Thank you very much for your help.

2017-02-12 16:39 UTC, fd0 approved these changes

2017-02-12 16:45 UTC, fd0 requested changes
Very good! Now before this can get merged, there are a couple of smaller things that need to be done:
 * Squash your changes into one commit
 * Write a short paragraph for the manual, perhaps titled "Scripting restic", which mentions `--json` and shows an example usage with `snapshots`.

Thanks for your work!

2017-02-12 20:22 UTC, closed without merging