Fix restoring files ownership as non-root user
restic/restic pull request #878
Opened 2017-03-10 23:17 UTC by middelink

Like tar, it should be possible to restore files and skip the setting ownership of files for non-root users.

Fixes #655

2017-03-11 09:15 UTC, fd0 requested changes

2017-03-11 09:15 UTC, fd0 commented on src/restic/node.go
> +	if os.Getuid() == 0 {
That's not a good test, `EUID == 0` is sometimes sufficient, or having `CAP_CHOWN` available. I'd just try it last, and return the error (I have no better idea for it).

2017-03-12 10:51 UTC, fd0 requested changes

2017-03-12 10:51 UTC, fd0 commented on src/restic/node.go
> +	if err = lchown(path, int(node.UID), int(node.GID)); err != nil {
For suid files (as in the test that fails), the suid bits are reset when the file is chowned. And the ctime is also changed. So I'd suggest moving `lchown()` to the beginning of the function again, but only return the error at the end.

2017-03-12 14:45 UTC, middelink commented on src/restic/node.go
> +	if err = lchown(path, int(node.UID), int(node.GID)); err != nil {
Yeah, live suxs, i'll look into recoding the recoded code... I got sidetracked a bit by transformation functions.

2017-03-12 15:41 UTC, fd0 commented on src/restic/node.go
> +	if err = lchown(path, int(node.UID), int(node.GID)); err != nil {
You don't need to apologize, thanks for your work!

2017-03-12 15:54 UTC, middelink commented
Done, this works locally to my personal satisfaction :)

2017-03-12 17:14 UTC, fd0 approved these changes

2017-03-12 17:15 UTC, fd0 commented
Thanks!

2017-03-12 17:20 UTC, merged